function FE3dGalaxy(a){a=RClass.inherits(this,a,FE3dRenderable);a._seed=0;a._cellSize=null;a._size=null;a._lineColor=null;a._lineCenterColor=null;a._radius=0;a._vertexSpecialBuffer=null;a._vertexPositionBuffer=null;a._vertexCoordBuffer=null;a._vertexColorBuffer=null;a._vertexSpecialData=null;a._vertexPositionData=null;a._vertexCoordData=null;a._vertexColorData=null;a._indexData=null;a.construct=FE3dGalaxy_construct;a.generatePixel=FE3dGalaxy_generatePixel;a.setup=FE3dGalaxy_setup;return a}
function FE3dGalaxy_construct(){this.__base.FE3dRenderable.construct.call(this);this._cellSize=new SSize2;this._cellSize.set(2,2);this._size=new SSize2;this._size.set(16,16)}
function FE3dGalaxy_generatePixel(a,b,h,d,f,g){var e=4*(this._size.width*h+b);b=g[e++];h=g[e++];g=g[e++];for(var e=1-Math.sqrt(d*d+f*f)/this._radius,l=0;1>l;l++){var c=[d,0,f,e,d,0,f,e,d,0,f,e,d,0,f,e];RFloat.copy(this._vertexSpecialData,16*a,c,0,16);c=[d-.5,0,f+.5,d+.5,0,f+.5,d+.5,0,f-.5,d-.5,0,f-.5];RFloat.copy(this._vertexPositionData,12*a,c,0,12);c=[0,1,1,1,1,0,0,0];RFloat.copy(this._vertexCoordData,8*a,c,0,8);c=[b,h,g,1,b,h,g,1,b,h,g,1,b,h,g,1];RFloat.copy(this._vertexColorData,16*a,c,0,16);
c=4*a;RInteger.copy(this._indexData,6*a,[c+0,c+1,c+2,c+0,c+2,c+3],0,6)}}
function FE3dGalaxy_setup(a){var b=this._graphicContext,h=this._size.width,d=h/2,f=this._size.height,g=f/2,e=this._cellSize.width,l=this._cellSize.height;this._radius=Math.sqrt(d*d+g*g);var c=h/e*(f/l),k=4*c;this._vertexCount=k;this._vertexSpecialData=new Float32Array(4*k);this._vertexPositionData=new Float32Array(3*k);this._vertexCoordData=new Float32Array(2*k);this._vertexColorData=new Uint8Array(4*k);this._indexData=Array(6*c);for(var p=0,m=0;m<f;m+=l)for(var n=0;n<h;n+=e)this.generatePixel(p++,
n,m,n-d,m-g,a);a=this._vertexSpecialBuffer=b.createVertexBuffer();a._name="special";a._formatCd=EG3dAttributeFormat.Float4;a.upload(this._vertexSpecialData,16,k);this._vertexBuffers.set(a._name,a);a=this._vertexPositionBuffer=b.createVertexBuffer();a._name="position";a._formatCd=EG3dAttributeFormat.Float3;a.upload(this._vertexPositionData,12,k);this._vertexBuffers.set(a._name,a);a=this._vertexCoordBuffer=b.createVertexBuffer();a._name="coord";a._formatCd=EG3dAttributeFormat.Float2;a.upload(this._vertexCoordData,
8,k);this._vertexBuffers.set(a._name,a);a=this._vertexColorBuffer=b.createVertexBuffer();a._name="color";a._formatCd=EG3dAttributeFormat.Byte4Normal;a.upload(this._vertexColorData,4,k);this._vertexBuffers.set(a._name,a);b=this._indexBuffer=b.createIndexBuffer();context.capability().optionIndex32?(b._strideCd=EG3dIndexStride.Uint32,b.upload(new Uint32Array(this._indexData),6*c)):(b._strideCd=EG3dIndexStride.Uint16,b.upload(new Uint16Array(this._indexData),6*c));c=this.material().info();c.effectCode=
"galaxy";c.ambientColor.set(1,1,1,1)}function FE3dGalaxyEffect(a){a=RClass.inherits(this,a,FG3dAutomaticEffect);a._code="galaxy.automatic";a.drawRenderable=FE3dGalaxyEffect_drawRenderable;return a}
function FE3dGalaxyEffect_drawRenderable(a,b){var h=this._graphicContext,d=this._program,f=a.calculate(EG3dRegionParameter.CameraPosition),g=b.material(),e=g.info();this.bindMaterial(g);d.setParameter4("vc_rotation",b._seed,0,0,0);d.setParameter("vc_model_matrix",b.currentMatrix());d.setParameter("vc_vp_matrix",a.calculate(EG3dRegionParameter.CameraViewProjectionMatrix));d.setParameter("vc_camera_position",f);d.setParameter4("fc_alpha",e.alphaBase,e.alphaRate,e.alphaLevel,e.alphaMerge);d.setParameter("fc_ambient_color",
e.ambientColor);this.bindAttributes(b);this.bindSamplers(b);h.drawTriangles(b.indexBuffer())}var RE3dDemo=new function(){this._setuped=!1;this.onSetup=RE3dDemo_onSetup;this.setup=RE3dDemo_setup;return this};function RE3dDemo_onSetup(){RConsole.find(FG3dEffectConsole).register("control.control.galaxy",FE3dGalaxyEffect)}function RE3dDemo_setup(){this._setuped||(this.onSetup(),this._setuped=!0)};
