MO.EEaiConstant=new function(){this.ServiceHost="eai.logic.service";return this};MO.EEaiStage=new function(){this.Loading=1;this.Login=2;this.Scene=3;return this};
with(MO)MO.FEaiLogic=function(a){a=RClass.inherits(this,a,FObject);a._code=null;a.makeUrl=FEaiLogicOrganization_makeUrl;a.send=FEaiLogicOrganization_send;return a},MO.FEaiLogicOrganization_makeUrl=function(a,b){return"http://"+MO.RConsole.find(MO.FEnvironmentConsole).findValue(MO.EEaiConstant.ServiceHost)+"/eai/"+this._code+"/"+a},MO.FEaiLogicOrganization_send=function(a,b,c,d){a=this.makeUrl(a,b);a=RConsole.find(FJsonConsole).sendAsync(a);a.addProcessListener(c,d);return a};
with(MO)MO.FEaiLogicAchievement=function(a){a=RClass.inherits(this,a,FEaiLogic);a._code="achievement";a.doGroup=FEaiLogicAchievement_doGroup;a.doSort=FEaiLogicAchievement_doSort;a.doQuery=FEaiLogicAchievement_doQuery;return a},MO.FEaiLogicAchievement_doGroup=function(a,b){return this.send("group",null,a,b)},MO.FEaiLogicAchievement_doSort=function(a,b){return this.send("sort",null,a,b)},MO.FEaiLogicAchievement_doQuery=function(a,b){return this.send("query",null,a,b)};
MO.FEaiLogicConsole=function(a){a=MO.RClass.inherits(this,a,MO.FConsole);a._organization=null;a._achievement=null;a._schedule=null;a.construct=MO.FEaiLogicConsole_construct;a.organization=MO.FEaiLogicConsole_organization;a.achievement=MO.FEaiLogicConsole_achievement;a.schedule=MO.FEaiLogicConsole_schedule;return a};MO.FEaiLogicConsole_construct=function(a){this._organization=MO.RClass.create(MO.FEaiLogicOrganization);this._achievement=MO.RClass.create(MO.FEaiLogicAchievement);this._schedule=MO.RClass.create(MO.FEaiLogicSchedule)};
MO.FEaiLogicConsole_organization=function(){return this._organization};MO.FEaiLogicConsole_achievement=function(){return this._achievement};MO.FEaiLogicConsole_schedule=function(){return this._schedule};with(MO)MO.FEaiLogicOrganization=function(a){a=RClass.inherits(this,a,FEaiLogic);a._code="organization";a.doFetch=FEaiLogicOrganization_doFetch;return a},MO.FEaiLogicOrganization_doFetch=function(a,b){return this.send("fetch",null,a,b)};
with(MO)MO.FEaiLogicSchedule=function(a){a=RClass.inherits(this,a,FEaiLogic);a._code="schedule";a.doFetch=FEaiLogicSchedule_doFetch;return a},MO.FEaiLogicSchedule_doFetch=function(a,b){return this.send("fetch",null,a,b)};MO.FEaiCompanyScene=function(a){return a=MO.RClass.inherits(this,a,MO.FEaiScene)};MO.FEaiCountryScene=function(a){return a=MO.RClass.inherits(this,a,MO.FEaiScene)};MO.FEaiGroupReportScene=function(a){return a=MO.RClass.inherits(this,a,MO.FEaiScene)};
MO.FEaiGroupScene=function(a){return a=MO.RClass.inherits(this,a,MO.FEaiScene)};
with(MO)MO.FEaiScene=function(a){a=RClass.inherits(this,a,FE3dStage);a._mapLayer=null;a._spriteLayer=null;a._faceLayer=null;a.construct=FEaiScene_construct;a.mapLayer=FEaiScene_mapLayer;a.spriteLayer=FEaiScene_spriteLayer;a.faceLayer=FEaiScene_faceLayer;a.active=FEaiScene_active;a.deactive=FEaiScene_deactive;return a},MO.FEaiScene_construct=function(){this.__base.FE3dStage.construct.call(this);var a=this._mapLayer=RClass.create(FDisplayLayer);this.registerLayer("MapLayer",a);a=this._spriteLayer=RClass.create(FDisplayLayer);
this.registerLayer("SpriteLayer",a);a=this._faceLayer=RClass.create(FDisplayLayer);this.registerLayer("FaceLayer",a)},MO.FEaiScene_mapLayer=function(){return this._mapLayer},MO.FEaiScene_spriteLayer=function(){return this._spriteLayer},MO.FEaiScene_faceLayer=function(){return this._faceLayer},MO.FEaiScene_active=function(){this.__base.FE3dStage.active.call(this)},MO.FEaiScene_deactive=function(){this.__base.FE3dStage.deactive.call(this)};
with(MO)MO.FEaiApplication=function(a){a=RClass.inherits(this,a,FApplication);a._stageLoading=RClass.register(a,new AGetter("_stageLoading"));a._stageLogin=RClass.register(a,new AGetter("_stageLogin"));a._stageScene=RClass.register(a,new AGetter("_stageScene"));a.construct=FEaiApplication_construct;a.setup=FEaiApplication_setup;a.dispose=FEaiApplication_dispose;return a},MO.FEaiApplication_construct=function(){this.__base.FApplication.construct.call(this);this._stageLoading=MO.RClass.create(MO.FEaiLoadingStage);
this._stageLogin=MO.RClass.create(MO.FEaiLoginStage);this._stageScene=MO.RClass.create(MO.FEaiSceneStage)},MO.FEaiApplication_setup=function(){},MO.FEaiApplication_dispose=function(){this.__base.FApplication.dispose.call(this)};
with(MO)MO.FEaiCanvas=function(a){a=RClass.inherits(this,a,FE3dCanvas);a._scaleRate=1;a._optionAlpha=!1;a._activeTemplate=null;a._capturePosition=null;a._captureRotation=null;a._stage=null;a.onEnterFrame=FEaiCanvas_onEnterFrame;a.onMouseCaptureStart=FEaiCanvas_onMouseCaptureStart;a.onMouseCapture=FEaiCanvas_onMouseCapture;a.onMouseCaptureStop=FEaiCanvas_onMouseCaptureStop;a.onResize=FEaiCanvas_onResize;a.onTemplateLoad=FEaiCanvas_onTemplateLoad;a.construct=FEaiCanvas_construct;a.build=FEaiCanvas_build;
a.setPanel=FEaiCanvas_setPanel;a.loadByGuid=FEaiCanvas_loadByGuid;a.loadByCode=FEaiCanvas_loadByCode;a.dispose=FEaiCanvas_dispose;return a},MO.FEaiCanvas_onEnterFrame=function(){var a=this._stage;if(a){var b=a.camera(),c=.05,d=RKeyboard.isPress(EKeyCode.W),e=RKeyboard.isPress(EKeyCode.S);d&&!e&&b.doWalk(.5);!d&&e&&b.doWalk(-.5);d=RKeyboard.isPress(EKeyCode.A);e=RKeyboard.isPress(EKeyCode.D);d&&!e&&b.doYaw(c);!d&&e&&b.doYaw(-c);d=RKeyboard.isPress(EKeyCode.Q);e=RKeyboard.isPress(EKeyCode.E);d&&!e&&
b.doFly(.5);!d&&e&&b.doFly(-.5);e=RKeyboard.isPress(EKeyCode.Z);d=RKeyboard.isPress(EKeyCode.X);e&&!d&&b.doPitch(c);!e&&d&&b.doPitch(-c);b.update();if(this._optionRotation){c=this._rotation;a=a.layers();b=a.count();for(d=0;d<b;d++)e=a.value(d).matrix(),e.setRotation(0,c.y,0),e.update();c.y+=.01}}},MO.FEaiCanvas_onMouseCaptureStart=function(a){var b=this._activeTemplate;if(b){var c=this._activeTemplate.region();RConsole.find(FG3dTechniqueConsole).find(this._graphicContext,FG3dSelectTechnique).test(c,
a.offsetX,a.offsetY);this._capturePosition.set(a.clientX,a.clientY);this._captureRotation.assign(b.camera()._rotation)}},MO.FEaiCanvas_onMouseCapture=function(a){if(this._activeTemplate){var b=a.clientX-this._capturePosition.x;a=a.clientY-this._capturePosition.y;var c=this._activeTemplate.camera().rotation(),d=this._captureRotation;c.x=d.x+.003*a;c.y=d.y+.003*b}},MO.FEaiCanvas_onMouseCaptureStop=function(a){},MO.FEaiCanvas_onResize=function(){this.__base.FE3dCanvas.onResize.call(this,event);var a=
this._graphicContext.size(),b=this._activeSpace;b&&(b=b.camera().projection(),b.size().set(a.width,a.height),b.update())},MO.FEaiCanvas_onTemplateLoad=function(a){a=this._activeTemplate;var b=this._graphicContext.size(),c=a.camera().projection();c.size().set(b.width,b.height);c.update();this.processLoadListener(this,a)},MO.FEaiCanvas_construct=function(){this.__base.FE3dCanvas.construct.call(this);this._rotation=new SVector3;this._capturePosition=new SPoint2;this._captureRotation=new SVector3},MO.FEaiCanvas_build=
function(a){this.__base.FE3dCanvas.build.call(this,a);a=this._stage=MO.RClass.create(MO.FEaiStage);a.linkGraphicContext(this);a.region().linkGraphicContext(this);a.selectTechnique(this,FE3dGeneralTechnique);RStage.register("eai.stage",a)},MO.FEaiCanvas_setPanel=function(a){this.__base.FE3dCanvas.setPanel.call(this,a);a=this._stage;var b=a.region().camera(),c=b.projection();c.size().set(this._hCanvas.offsetWidth,this._hCanvas.offsetHeight);c.update();b.position().set(0,0,-10);b.lookAt(0,0,0);b.update();
RStage.register("eai.stage",a)},MO.FEaiCanvas_loadByGuid=function(a){var b=this._graphicContext,c=RConsole.find(FE3dSceneConsole);null!=this._activeTemplate&&c.free(this._activeTemplate);a=c.alloc(this,a);a.addLoadListener(this,this.onTemplateLoad);a.selectTechnique(b,FG3dGeneralTechnique);this._stage=this._activeTemplate=a;RStage.register("stage3d",a)},MO.FEaiCanvas_loadByCode=function(a){var b=this._graphicContext,c=RConsole.find(FE3dTemplateConsole);null!=this._activeTemplate&&c.free(this._activeTemplate);
a=c.allocByCode(b,a);a.addLoadListener(this,this.onTemplateLoad);a.selectTechnique(b,FE3dGeneralTechnique);this._stage=this._activeTemplate=a;RStage.register("stage.template",a)},MO.FEaiCanvas_dispose=function(){var a=this._rotation;a&&(a.dispose(),this._rotation=null);this.__base.FE3dCanvas.dispose.call(this)};MO.FEaiLoadingStage=function(a){return a=MO.RClass.inherits(this,a,MO.FEaiStage)};MO.FEaiLoginStage=function(a){return a=MO.RClass.inherits(this,a,MO.FEaiStage)};
MO.FEaiSceneStage=function(a){return a=MO.RClass.inherits(this,a,MO.FEaiStage)};
with(MO)MO.FEaiStage=function(a){a=RClass.inherits(this,a,FE3dStage);a._mapLayer=RClass.register(a,new AGetter("_mapLayer"));a._spriteLayer=RClass.register(a,new AGetter("_spriteLayer"));a._faceLayer=RClass.register(a,new AGetter("_faceLayer"));a.construct=FEaiStage_construct;a.active=FEaiStage_active;a.deactive=FEaiStage_deactive;return a},MO.FEaiStage_construct=function(){this.__base.FE3dStage.construct.call(this);var a=this._mapLayer=RClass.create(FDisplayLayer);this.registerLayer("MapLayer",a);
a=this._spriteLayer=RClass.create(FDisplayLayer);this.registerLayer("SpriteLayer",a);a=this._faceLayer=RClass.create(FDisplayLayer);this.registerLayer("FaceLayer",a)},MO.FEaiStage_active=function(){this.__base.FE3dStage.active.call(this)},MO.FEaiStage_deactive=function(){this.__base.FE3dStage.deactive.call(this)};MO.Eai=new function(){};MO.Eai.setup=function(){MO.Eai.Application=MO.RClass.create(MO.FEaiApplication);MO.Eai.Application.setup()};
