MO.EEaiChapter=new function(){this.Loading="loading";this.Login="login";this.Scene="scene";this.Chart="chart";return this};MO.EEaiConstant=new function(){this.ServiceHost="eai.logic.service";return this};MO.EEaiRate=new function(){this.Line=0;this.Map=1;return this};
MO.EEaiScene=new function(){this.Group="group";this.GroupReport="group.report";this.Company="company";this.Country="country";this.ChartHistory="chart.history";this.ChartIndustry="chart.industry";this.ChartInvestment="chart.investment";this.ChartCustomer="chart.customer";return this};MO.Eai=new function(){this.Canvas=this.Application=null;return this};with(MO)MO.FEaiEntity=function(a){return a=RClass.inherits(this,a,FObject)},MO.FEaiEntity_dispose=function(){this.__base.FObject.dispose.call(this)};
with(MO)MO.FEaiCityResource=function(a){a=RClass.inherits(this,a,FObject);a._provinceCode=RClass.register(a,new AGetter("_provinceCode"));a._code=RClass.register(a,new AGetter("_code"));a._label=RClass.register(a,new AGetter("_label"));a._level=RClass.register(a,new AGetter("_level"));a._location=RClass.register(a,new AGetter("_location"));a.construct=FEaiCityResource_construct;a.unserialize=FEaiCityResource_unserialize;a.dispose=FEaiCityResource_dispose;return a},MO.FEaiCityResource_construct=function(){this.__base.FObject.construct.call(this);
this._location=new SPoint3},MO.FEaiCityResource_unserialize=function(a){this._provinceCode=a.readUint16();this._code=a.readUint16();this._label=a.readString();this._level=a.readUint16();this._location.unserialize(a)},MO.FEaiCityResource_dispose=function(){this._location=RObject.dispose(this._location);this.__base.FObject.dispose.call(this)};
with(MO)MO.FEaiCityResourceConsole=function(a){a=RClass.inherits(this,a,FConsole);a._citys=RClass.register(a,new AGetter("_citys"));a.construct=FEaiCityResourceConsole_construct;a.unserialize=FEaiCityResourceConsole_unserialize;a.dispose=FEaiCityResourceConsole_dispose;return a},MO.FEaiCityResourceConsole_construct=function(){this.__base.FConsole.construct.call(this);this._citys=new TDictionary},MO.FEaiCityResourceConsole_unserialize=function(a){for(var b=this._citys,d=a.readInt32(),c=0;c<d;c++){var e=
RClass.create(FEaiCityResource);e.unserialize(a);b.set(e.code(),e)}},MO.FEaiCityResourceConsole_dispose=function(){this._citys=RObject.dispose(this._citys);this.__base.FConsole.dispose.call(this)};
with(MO)MO.FEaiHistoryCityResource=function(a){a=RClass.inherits(this,a,FObject);a._code=RClass.register(a,new AGetSet("_code"));a._investmentDay=RClass.register(a,new AGetSet("_investmentDay"));a._investmentTotal=RClass.register(a,new AGetSet("_investmentTotal"));a.unserialize=FEaiHistoryCityResource_unserialize;return a},MO.FEaiHistoryCityResource_unserialize=function(a){this._code=a.readUint16();this._investmentDay=a.readFloat();this._investmentTotal=a.readFloat()};
with(MO)MO.FEaiHistoryDateResource=function(a){a=RClass.inherits(this,a,FObject);a._code=RClass.register(a,new AGetter("_code"));a._investmentDay=RClass.register(a,new AGetter("_investmentDay"));a._investmentTotal=RClass.register(a,new AGetter("_investmentTotal"));a._provinces=RClass.register(a,new AGetter("_provinces"));a._citys=RClass.register(a,new AGetter("_citys"));a.construct=FEaiHistoryDateResource_construct;a.unserialize=FEaiHistoryDateResource_unserialize;a.dispose=FEaiHistoryDateResource_dispose;
return a},MO.FEaiHistoryDateResource_construct=function(){this.__base.FObject.construct.call(this);this._provinces=new TDictionary;this._citys=new TDictionary},MO.FEaiHistoryDateResource_unserialize=function(a){this._code=a.readString();this._investmentDay=a.readFloat();this._investmentTotal=a.readFloat();for(var b=this._provinces,d=a.readInt32(),c=0;c<d;c++){var e=RClass.create(FEaiHistoryProvinceResource);e.unserialize(a);b.set(e.code(),e)}b=this._citys;d=a.readInt32();for(c=0;c<d;c++)e=RClass.create(FEaiHistoryCityResource),
e.unserialize(a),b.set(e.code(),e)},MO.FEaiHistoryDateResource_dispose=function(){this._provinces=RObject.dispose(this._provinces);this._citys=RObject.dispose(this._citys);this.__base.FObject.dispose.call(this)};
with(MO)MO.FEaiHistoryMilestoneResource=function(a){a=RClass.inherits(this,a,FObject);a._code=RClass.register(a,new AGetSet("_code"));a._investmentTotal=RClass.register(a,new AGetSet("_investmentTotal"));a._dayCount=RClass.register(a,new AGetSet("_dayCount"));a._companyCount=RClass.register(a,new AGetSet("_companyCount"));a._staffCount=RClass.register(a,new AGetSet("_staffCount"));a.unserialize=FEaiHistoryMilestoneResource_unserialize;return a},MO.FEaiHistoryMilestoneResource_unserialize=function(a){this._code=
a.readString();this._investmentTotal=a.readFloat();this._dayCount=a.readUint16();this._companyCount=a.readUint16();this._staffCount=a.readUint16()};
with(MO)MO.FEaiHistoryProvinceResource=function(a){a=RClass.inherits(this,a,FObject);a._code=RClass.register(a,new AGetSet("_code"));a._investmentDay=RClass.register(a,new AGetSet("_investmentDay"));a._investmentTotal=RClass.register(a,new AGetSet("_investmentTotal"));a.unserialize=FEaiHistoryProvinceResource_unserialize;return a},MO.FEaiHistoryProvinceResource_unserialize=function(a){this._code=a.readUint16();this._investmentDay=a.readFloat();this._investmentTotal=a.readFloat()};
with(MO)MO.FEaiHistoryResourceConsole=function(a){a=RClass.inherits(this,a,FConsole);a._investmentDay=RClass.register(a,new AGetter("_investmentDay"));a._investmentTotal=RClass.register(a,new AGetter("_investmentTotal"));a._investmentProvinceDay=RClass.register(a,new AGetter("_investmentProvinceDay"));a._investmentProvinceTotal=RClass.register(a,new AGetter("_investmentProvinceTotal"));a._investmentCityDay=RClass.register(a,new AGetter("_investmentCityDay"));a._investmentCityTotal=RClass.register(a,
new AGetter("_investmentCityTotal"));a._provinces=RClass.register(a,new AGetter("_provinces"));a._citys=RClass.register(a,new AGetter("_citys"));a._milestones=RClass.register(a,new AGetter("_milestones"));a._dates=RClass.register(a,new AGetter("_dates"));a.construct=FEaiHistoryResourceConsole_construct;a.unserialize=FEaiHistoryResourceConsole_unserialize;a.dispose=FEaiHistoryResourceConsole_dispose;return a},MO.FEaiHistoryResourceConsole_construct=function(){this.__base.FConsole.construct.call(this);
this._provinces=new TDictionary;this._citys=new TDictionary;this._milestones=new TDictionary;this._dates=new TDictionary},MO.FEaiHistoryResourceConsole_unserialize=function(a){this._investmentDay=a.readFloat();this._investmentTotal=a.readFloat();this._investmentProvinceDay=a.readFloat();this._investmentProvinceTotal=a.readFloat();this._investmentCityDay=a.readFloat();this._investmentCityTotal=a.readFloat();for(var b=a.readInt32(),d=0;d<b;d++){var c=RClass.create(FEaiHistoryProvinceResource);c.unserialize(a);
this._provinces.set(c.code(),c)}b=a.readInt32();for(d=0;d<b;d++)c=RClass.create(FEaiHistoryCityResource),c.unserialize(a),this._citys.set(c.code(),c);b=a.readInt32();for(d=0;d<b;d++)c=RClass.create(FEaiHistoryMilestoneResource),c.unserialize(a),this._milestones.set(c.code(),c);b=a.readInt32();for(d=0;d<b;d++)c=RClass.create(FEaiHistoryDateResource),c.unserialize(a),this._dates.set(c.code(),c)},MO.FEaiHistoryResourceConsole_dispose=function(){this._provinces=RObject.dispose(this._provinces);this._citys=
RObject.dispose(this._citys);this._milestones=RObject.dispose(this._milestones);this._dates=RObject.dispose(this._dates);this.__base.FConsole.dispose.call(this)};
with(MO)MO.FEaiProvinceResource=function(a){a=RClass.inherits(this,a,FObject);a._code=RClass.register(a,new AGetSet("_code"));a._name=RClass.register(a,new AGetter("_name"));a._label=RClass.register(a,new AGetSet("_label"));a.unserialize=FEaiProvinceResource_unserialize;return a},MO.FEaiProvinceResource_unserialize=function(a){this._code=a.readUint16();this._name=a.readString();this._label=a.readString()};
with(MO)MO.FEaiProvinceResourceConsole=function(a){a=RClass.inherits(this,a,FConsole);a._provinceCodes=RClass.register(a,new AGetter("_provinceCodes"));a._provinceNames=RClass.register(a,new AGetter("_provinceNames"));a.construct=FEaiProvinceResourceConsole_construct;a.findByCode=FEaiProvinceResourceConsole_findByCode;a.findByName=FEaiProvinceResourceConsole_findByName;a.unserialize=FEaiProvinceResourceConsole_unserialize;a.dispose=FEaiProvinceResourceConsole_dispose;return a},MO.FEaiProvinceResourceConsole_construct=
function(){this.__base.FConsole.construct.call(this);this._provinceCodes=new TDictionary;this._provinceNames=new TDictionary},MO.FEaiProvinceResourceConsole_findByCode=function(a){return this._provinceCodes.get(a)},MO.FEaiProvinceResourceConsole_findByName=function(a){return this._provinceNames.get(a)},MO.FEaiProvinceResourceConsole_unserialize=function(a){for(var b=this._provinceCodes,d=this._provinceNames,c=a.readInt32(),e=0;e<c;e++){var f=RClass.create(FEaiProvinceResource);f.unserialize(a);b.set(f.code(),
f);d.set(f.name(),f)}},MO.FEaiProvinceResourceConsole_dispose=function(){this._provinceCodes=RObject.dispose(this._provinceCodes);this._provinceNames=RObject.dispose(this._provinceNames);this.__base.FConsole.dispose.call(this)};
with(MO)MO.FEaiRateResource=function(a){a=RClass.inherits(this,a,FObject);a._count=RClass.register(a,new AGetter("_count"));a._colors=RClass.register(a,new AGetter("_colors"));a.construct=FEaiRateResource_construct;a.find=FEaiRateResource_find;a.findRate=FEaiRateResource_findRate;a.unserialize=FEaiRateResource_unserialize;a.dispose=FEaiRateResource_dispose;return a},MO.FEaiRateResource_construct=function(){this.__base.FObject.construct.call(this)},MO.FEaiRateResource_find=function(a){a=parseInt(a);
0>a&&(a=0);a>this._count&&(a=this._count-1);return this._colors[a]},MO.FEaiRateResource_findRate=function(a){return this.find(a*this._count)},MO.FEaiRateResource_unserialize=function(a){for(var b=this._count=a.readInt32(),d=this._colors=new Uint32Array(b),c=0;c<b;c++)d[c]=a.readUint32()},MO.FEaiRateResource_dispose=function(){this._colors=null;this.__base.FObject.dispose.call(this)};
with(MO)MO.FEaiRateResourceConsole=function(a){a=RClass.inherits(this,a,FConsole);a._rates=RClass.register(a,new AGetter("_rates"));a.construct=FEaiRateResourceConsole_construct;a.find=FEaiRateResourceConsole_find;a.unserialize=FEaiRateResourceConsole_unserialize;a.dispose=FEaiRateResourceConsole_dispose;return a},MO.FEaiRateResourceConsole_construct=function(){this.__base.FConsole.construct.call(this);this._rates=new TObjects},MO.FEaiRateResourceConsole_find=function(a){return this._rates.get(a)},
MO.FEaiRateResourceConsole_unserialize=function(a){for(var b=this._count=a.readInt32(),d=0;d<b;d++){var c=MO.Class.create(FEaiRateResource);c.unserialize(a);this._rates.push(c)}},MO.FEaiRateResourceConsole_dispose=function(){this._rates=RObject.dispose(this._rates);this.__base.FConsole.dispose.call(this)};
MO.FEaiResourceConsole=function(a){a=MO.RClass.inherits(this,a,MO.FConsole,MO.MListener);a._scopeCd=MO.EScope.Local;a._rateConsole=MO.Class.register(a,new MO.AGetter("_rateConsole"));a._provinceConsole=MO.Class.register(a,new MO.AGetter("_provinceConsole"));a._cityConsole=MO.Class.register(a,new MO.AGetter("_cityConsole"));a._historyConsole=MO.Class.register(a,new MO.AGetter("_historyConsole"));a._loadListeners=MO.Class.register(a,new MO.AListener("_loadListeners",MO.EEvent.Load));a.onLoad=MO.FEaiResourceConsole_onLoad;
a.construct=MO.FEaiResourceConsole_construct;a.unserialize=MO.FEaiResourceConsole_unserialize;a.load=MO.FEaiResourceConsole_load;a.dispose=MO.FEaiResourceConsole_dispose;return a};MO.FEaiResourceConsole_onLoad=function(a){a=a.outputData();var b=MO.Class.create(MO.FDataView);b.setEndianCd(!0);b.link(a);this.unserialize(b);b.dispose();a=new MO.SEvent;this.processLoadListener(a);a.dispose()};
MO.FEaiResourceConsole_construct=function(){this.__base.FConsole.construct.call(this);this._rateConsole=MO.RClass.create(MO.FEaiRateResourceConsole);this._provinceConsole=MO.RClass.create(MO.FEaiProvinceResourceConsole);this._cityConsole=MO.RClass.create(MO.FEaiCityResourceConsole);this._historyConsole=MO.RClass.create(MO.FEaiHistoryResourceConsole)};
MO.FEaiResourceConsole_unserialize=function(a){this._rateConsole.unserialize(a);this._provinceConsole.unserialize(a);this._cityConsole.unserialize(a);this._historyConsole.unserialize(a)};MO.FEaiResourceConsole_load=function(){MO.RConsole.find(MO.FHttpConsole).send("/script/ars/eai/resource.dat").addLoadListener(this,this.onLoad)};
MO.FEaiResourceConsole_dispose=function(a){this._rateConsole=RObject.dispose(this._rateConsole);this._provinceConsole=RObject.dispose(this._provinceConsole);this._cityConsole=RObject.dispose(this._cityConsole);this._historyConsole=RObject.dispose(this._historyConsole);this.__base.FConsole.dispose.call(this)};
with(MO)MO.FEaiCityEffect=function(a){a=RClass.inherits(this,a,FG3dAutomaticEffect);a._code="eai.city";a.drawRenderable=FEaiCityEffect_drawRenderable;return a},MO.FEaiCityEffect_drawRenderable=function(a,b){var d=this._graphicContext,c=this._program,e=b.currentMatrix(),f=a.calculate(EG3dRegionParameter.CameraViewProjectionMatrix),g=b.material(),k=g.info();this.bindMaterial(g);c.setParameter("vc_model_matrix",e);c.setParameter("vc_vp_matrix",f);c.setParameter4("fc_alpha",k.alphaBase,k.alphaRate,k.alphaLevel,
k.alphaMerge);c.setParameter("fc_ambient_color",k.ambientColor);this.bindAttributes(b);this.bindSamplers(b);c=b.indexBuffers().first();d.drawTriangles(c)};
with(MO)MO.FEaiCityRangeEffect=function(a){a=RClass.inherits(this,a,FG3dAutomaticEffect);a._code="eai.city.range";a.drawRenderable=FEaiCityRangeEffect_drawRenderable;return a},MO.FEaiCityRangeEffect_drawRenderable=function(a,b){var d=this._graphicContext,c=this._program,e=b.currentMatrix(),f=a.calculate(EG3dRegionParameter.CameraViewProjectionMatrix),g=b.material();g.info();this.bindMaterial(g);c.setParameter("vc_model_matrix",e);c.setParameter("vc_vp_matrix",f);this.bindAttributes(b);this.bindSamplers(b);
c=b.indexBuffers().first();d.drawTriangles(c)};
with(MO)MO.FEaiLogic=function(a){a=RClass.inherits(this,a,FObject);a._code=null;a.makeUrl=FEaiLogicOrganization_makeUrl;a.send=FEaiLogicOrganization_send;return a},MO.FEaiLogicOrganization_makeUrl=function(a,b){return"http://"+MO.RConsole.find(MO.FEnvironmentConsole).findValue(MO.EEaiConstant.ServiceHost)+"/eai/"+this._code+"/"+a},MO.FEaiLogicOrganization_send=function(a,b,d,c){a=this.makeUrl(a,b);a=RConsole.find(FJsonConsole).sendAsync(a);a.addProcessListener(d,c);return a};
with(MO)MO.FEaiLogicAchievement=function(a){a=RClass.inherits(this,a,FEaiLogic);a._code="achievement";a.doGroup=FEaiLogicAchievement_doGroup;a.doSort=FEaiLogicAchievement_doSort;a.doQuery=FEaiLogicAchievement_doQuery;return a},MO.FEaiLogicAchievement_doGroup=function(a,b){return this.send("group",null,a,b)},MO.FEaiLogicAchievement_doSort=function(a,b){return this.send("sort",null,a,b)},MO.FEaiLogicAchievement_doQuery=function(a,b){return this.send("query",null,a,b)};
MO.FEaiLogicConsole=function(a){a=MO.RClass.inherits(this,a,MO.FConsole);a._organization=null;a._achievement=null;a._schedule=null;a.construct=MO.FEaiLogicConsole_construct;a.organization=MO.FEaiLogicConsole_organization;a.achievement=MO.FEaiLogicConsole_achievement;a.schedule=MO.FEaiLogicConsole_schedule;return a};MO.FEaiLogicConsole_construct=function(a){this._organization=MO.RClass.create(MO.FEaiLogicOrganization);this._achievement=MO.RClass.create(MO.FEaiLogicAchievement);this._schedule=MO.RClass.create(MO.FEaiLogicSchedule)};
MO.FEaiLogicConsole_organization=function(){return this._organization};MO.FEaiLogicConsole_achievement=function(){return this._achievement};MO.FEaiLogicConsole_schedule=function(){return this._schedule};
with(MO)MO.FEaiLogicOrganization=function(a){a=RClass.inherits(this,a,FEaiLogic);a._code="organization";a._pIdMIndexDict=RClass.register(a,new AGetter("_pIdMIndexDict"));a._cityIdNameDict=RClass.register(a,new AGetter("_cityIdNameDict"));a._provinceColors=RClass.register(a,new AGetter("_provinceColors"));a.doFetch=FEaiLogicOrganization_doFetch;a.getMeshIndex=FEaiLogicOrganization_getMeshIndex;a.construct=FEaiLogicOrganization_construct;return a},MO.FEaiLogicOrganization_construct=function(){this.__base.FEaiLogic.construct.call(this);
var a=this._pIdMIndexDict=new TDictionary;a.set(11,6);a.set(12,7);a.set(13,5);a.set(14,8);a.set(15,2);a.set(21,4);a.set(22,3);a.set(23,1);a.set(31,-1);a.set(32,21);a.set(33,22);a.set(34,20);a.set(35,30);a.set(36,23);a.set(37,9);a.set(41,10);a.set(42,19);a.set(43,29);a.set(44,24);a.set(45,25);a.set(46,0);a.set(50,18);a.set(51,17);a.set(52,26);a.set(53,27);a.set(54,16);a.set(61,12);a.set(62,13);a.set(63,15);a.set(64,11);a.set(65,14);a.set(71,28);a.set(81,-1);a.set(82,-1);this._cityIdNameDict=new TDictionary;
a=this._provinceColors=new TObjects;a.push(new SColor4(.25,.5,.6));a.push(new SColor4(.3,.6,.75));a.push(new SColor4(.35,.7,.8));a.push(new SColor4(.4,.75,.85));a.push(new SColor4(.45,.85,1))},MO.FEaiLogicOrganization_doFetch=function(a,b){return this.send("fetch",null,a,b)},MO.FEaiLogicOrganization_getMeshIndex=function(a){return this.pIdMIndexDict().value(a)},MO.FEaiLogicOrganization_getMeshIndex=function(a){return this.cityIdNameDict().value(a)};
with(MO)MO.FEaiLogicSchedule=function(a){a=RClass.inherits(this,a,FEaiLogic);a._code="schedule";a.doFetch=FEaiLogicSchedule_doFetch;return a},MO.FEaiLogicSchedule_doFetch=function(a,b){return this.send("fetch",null,a,b)};
with(MO)MO.MEaiCityRenderable=function(a){a=RClass.inherits(this,a);a._visible=RClass.register(a,new AGetter("_visible"),!0);a._location=RClass.register(a,new AGetter("_location"));a._size=RClass.register(a,new AGetter("_size"));a._color=RClass.register(a,new AGetter("_color"));a.construct=MEaiCityRenderable_construct;a.dispose=MEaiCityRenderable_dispose;return a},MO.MEaiCityRenderable_construct=function(){this._location=new SPoint2;this._size=new SSize2;this._color=new SColor4(1,1,1,1)},MO.MEaiCityRenderable_dispose=
function(){this._location=RObject.dispose(this._location);this._size=RObject.dispose(this._size);this._color=RObject.dispose(this._color)};
with(MO)MO.FEaiBoundaryData=function(a){a=RClass.inherits(this,a,FEaiEntity);a._positionCount=RClass.register(a,new AGetter("_positionCount"));a._positions=RClass.register(a,new AGetter("_positions"));a._indexes=RClass.register(a,new AGetter("_indexes"));a.construct=FEaiBoundaryData_construct;a.unserialize=FEaiBoundaryData_unserialize;a.dispose=FEaiBoundaryData_dispose;return a},MO.FEaiBoundaryData_construct=function(){this.__base.FEaiEntity.construct.call(this)},MO.FEaiBoundaryData_unserialize=function(a){var b=
0,d=this._positionCount=a.readInt32();this._positions=new Float32Array(2*d);for(var c=0;c<d;c++)this._positions[b++]=a.readFloat(),this._positions[b++]=a.readFloat();b=a.readInt32();this._indexes=new Uint16Array(b);for(c=0;c<b;c++)this._indexes[c]=a.readUint16()},MO.FEaiBoundaryData_dispose=function(){this._indexes=this._positions=null;this.__base.FEaiEntity.dispose.call(this)};
with(MO)MO.FEaiCityEntity=function(a){a=RClass.inherits(this,a,FEaiEntity,MEaiCityRenderable);a._data=RClass.register(a,new AGetSet("_data"));a.construct=FEaiCityEntity_construct;a.build=FEaiCityEntity_build;a.update=FEaiCityEntity_update;a.dispose=FEaiCityEntity_dispose;return a},MO.FEaiCityEntity_construct=function(){this.__base.FEaiEntity.construct.call(this);this.__base.MEaiCityRenderable.construct.call(this)},MO.FEaiCityEntity_build=function(a){this._location.assign(this._data.location());this._size.set(2,
2)},MO.FEaiCityEntity_update=function(a){this._data.location();var b=1;if(a){var d=RConsole.find(FEaiResourceConsole).historyConsole().investmentCityTotal(),b=RConsole.find(FEaiResourceConsole).rateConsole().find(EEaiRate.Map);a=5*Math.sqrt(a.investmentTotal()/d);d=b.findRate(a);b=10*a;a=RFloat.toRange(a,0,1);this._color.set((d>>16&255)/255,(d>>8&255)/255,(d>>0&255)/255,6*a)}else this._color.set(0,0,0,0);b=RFloat.toRange(Math.sqrt(b),1,5);this._size.set(b,b)},MO.FEaiCityEntity_dispose=function(){this.__base.MEaiCityRenderable.dispose.call(this);
this.__base.FEaiEntity.dispose.call(this)};
with(MO)MO.FEaiCitysRangeRenderable=function(a){a=RClass.inherits(this,a,FE3dRenderable);a._ready=!1;a._image=null;a._citys=RClass.register(a,new AGetter("_citys"));a._size=RClass.register(a,new AGetter("_size"));a._adjustSize=RClass.register(a,new AGetter("_adjustSize"));a._citySize=RClass.register(a,new AGetter("_citySize"));a._vertexPositionBuffer=null;a._vertexCoordBuffer=null;a._indexBuffer=null;a._texture=null;a.onImageLoad=FEaiCitysRangeRenderable_onImageLoad;a.construct=FEaiCitysRangeRenderable_construct;
a.testReady=FEaiCitysRangeRenderable_testReady;a.setup=FEaiCitysRangeRenderable_setup;a.upload=FEaiCitysRangeRenderable_upload;a.loadUrl=FEaiCitysRangeRenderable_loadUrl;a.dispose=FEaiCitysRangeRenderable_dispose;return a},MO.FEaiCitysRangeRenderable_onImageLoad=function(a){a=a.sender;var b=a.size(),d=b.width,b=b.height;this._size.set(d,b);var c=RInteger.pow2(d),e=RInteger.pow2(b);this._adjustSize.set(c,e);var f=RConsole.find(FE2dCanvasConsole),c=f.allocBySize(c,e);c.context().drawImage(a,0,0,d,b);
this._texture.upload(c);f.free(c);a.dispose();this._ready=!0},MO.FEaiCitysRangeRenderable_construct=function(){this.__base.FE3dRenderable.construct.call(this);this._citys=new TObjects;this._size=new SSize2;this._adjustSize=new SSize2;this._material=RClass.create(FE3dMaterial)},MO.FEaiCitysRangeRenderable_testReady=function(){return this._ready},MO.FEaiCitysRangeRenderable_setup=function(){var a=this._graphicContext,b=this._citys.count(),d=this._vertexCount=4*b,c=[0,0,0,1,0,0,1,-1,0,0,-1,0],e=this._vertexPositionBuffer=
a.createVertexBuffer();e.setCode("position");e.setFormatCd(EG3dAttributeFormat.Float3);e.upload(c,12,4);this.pushVertexBuffer(e);for(var e=0,c=new Float32Array(2*d),f=0;f<b;f++)c[e++]=0,c[e++]=1,c[e++]=1,c[e++]=1,c[e++]=1,c[e++]=0,c[e++]=0,c[e++]=0;e=this._vertexCoordBuffer=a.createVertexBuffer();e.setCode("coord");e.setFormatCd(EG3dAttributeFormat.Float2);e.upload(c,8,d);this.pushVertexBuffer(e);c=[1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1];e=this._vertexColorBuffer=a.createVertexBuffer();e.setCode("color");
e.setFormatCd(EG3dAttributeFormat.Byte4Normal);e.upload(c,4,4);this.pushVertexBuffer(e);d=6*b;e=0;c=new Uint16Array(d);for(f=0;f<b;f++){var g=4*f;c[e++]=g+0;c[e++]=g+1;c[e++]=g+2;c[e++]=g+0;c[e++]=g+2;c[e++]=g+3}e=this._indexBuffer=a.createIndexBuffer();e.upload(c,d);this.pushIndexBuffer(e);a=this._texture=a.createFlatTexture();a.setOptionFlipY(!0);a.setWrapCd(EG3dSamplerFilter.ClampToEdge,EG3dSamplerFilter.ClampToEdge);this.pushTexture(a,"diffuse");a=this._material.info();a.effectCode="eai.citys.range";
a.optionAlpha=!0;this._material._textures=this._textures;this.loadUrl("/script/ars/eai/dot.png")},MO.FEaiCitysRangeRenderable_upload=function(){for(var a=this._citys,b=a.count(),d=0,c=0;c<b;c++){var e=a.at(c);e.visible()&&d++}for(var f=this._vertexCount=4*d,g=0,k=new Float32Array(3*f),m=0,l=new Uint8Array(4*f),c=0;c<b;c++)if(e=a.at(c),e.visible()){var h=e.location(),p=e.size(),q=p.width/2,p=p.height/2;k[g++]=h.x-q;k[g++]=h.y+p;k[g++]=0;k[g++]=h.x+q;k[g++]=h.y+p;k[g++]=0;k[g++]=h.x+q;k[g++]=h.y-p;
k[g++]=0;k[g++]=h.x-q;k[g++]=h.y-p;k[g++]=0;for(var p=e.color(),e=parseInt(255*p.red),h=parseInt(255*p.green),q=parseInt(255*p.blue),p=parseInt(255*p.alpha),r=0;4>r;r++)l[m++]=e,l[m++]=h,l[m++]=q,l[m++]=p}this._vertexPositionBuffer.upload(k,12,f);this._vertexColorBuffer.upload(l,4,f);this._indexBuffer.setCount(6*d)},MO.FEaiCitysRangeRenderable_loadUrl=function(a){var b=RClass.create(FImage);b.addLoadListener(this,this.onImageLoad);b.loadUrl(a);this._ready=!1},MO.FEaiCitysRangeRenderable_dispose=function(){this._size=
RObject.dispose(this._size);this._adjustSize=RObject.dispose(this._adjustSize);this._texture=RObject.dispose(this._texture);this._vertexPositionBuffer=RObject.dispose(this._vertexPositionBuffer);this._vertexCoordBuffer=RObject.dispose(this._vertexCoordBuffer);this._indexBuffer=RObject.dispose(this._indexBuffer);this.__base.FE3dRenderable.dispose.call(this)};
with(MO)MO.FEaiCitysRenderable=function(a){a=RClass.inherits(this,a,FE3dRenderable);a._ready=!1;a._image=null;a._levelScale=null;a._citys=RClass.register(a,new AGetter("_citys"));a._level=RClass.register(a,new AGetSet("_level"));a._size=RClass.register(a,new AGetter("_size"));a._adjustSize=RClass.register(a,new AGetter("_adjustSize"));a._citySize=RClass.register(a,new AGetter("_citySize"));a._vertexPositionBuffer=null;a._vertexCoordBuffer=null;a._indexBuffer=null;a._texture=null;a.onImageLoad=FEaiCitysRenderable_onImageLoad;
a.construct=FEaiCitysRenderable_construct;a.testReady=FEaiCitysRenderable_testReady;a.setup=FEaiCitysRenderable_setup;a.upload=FEaiCitysRenderable_upload;a.loadUrl=FEaiCitysRenderable_loadUrl;a.dispose=FEaiCitysRenderable_dispose;return a},MO.FEaiCitysRenderable_onImageLoad=function(a){a=a.sender;var b=a.size(),d=b.width,b=b.height;this._size.set(d,b);var c=RInteger.pow2(d),e=RInteger.pow2(b);this._adjustSize.set(c,e);var f=RConsole.find(FE2dCanvasConsole),c=f.allocBySize(c,e);c.context().drawImage(a,
0,0,d,b);this._texture.upload(c);f.free(c);a.dispose();this._ready=!0},MO.FEaiCitysRenderable_construct=function(){this.__base.FE3dRenderable.construct.call(this);this._citys=new TObjects;this._size=new SSize2;this._adjustSize=new SSize2;this._material=RClass.create(FE3dMaterial);var a=this._levelScale={};a[1]=.8;a[2]=.5;a[3]=.4;a[4]=.2},MO.FEaiCitysRenderable_testReady=function(){return this._ready},MO.FEaiCitysRenderable_setup=function(){var a=this._graphicContext,b=this._citys.count(),d=this._vertexCount=
4*b,c=this._vertexPositionBuffer=a.createVertexBuffer();c.setCode("position");c.setFormatCd(EG3dAttributeFormat.Float3);this.pushVertexBuffer(c);for(var c=0,e=new Float32Array(2*d),f=0;f<b;f++)e[c++]=0,e[c++]=1,e[c++]=1,e[c++]=1,e[c++]=1,e[c++]=0,e[c++]=0,e[c++]=0;c=this._vertexCoordBuffer=a.createVertexBuffer();c.setCode("coord");c.setFormatCd(EG3dAttributeFormat.Float2);c.upload(e,8,d);this.pushVertexBuffer(c);c=this._vertexColorBuffer=a.createVertexBuffer();c.setCode("color");c.setFormatCd(EG3dAttributeFormat.Byte4Normal);
this.pushVertexBuffer(c);d=6*b;c=0;e=new Uint16Array(d);for(f=0;f<b;f++){var g=4*f;e[c++]=g+0;e[c++]=g+1;e[c++]=g+2;e[c++]=g+0;e[c++]=g+2;e[c++]=g+3}c=this._indexBuffer=a.createIndexBuffer();c.upload(e,d);this.pushIndexBuffer(c);a=this._texture=a.createFlatTexture();a.setOptionFlipY(!0);a.setWrapCd(EG3dSamplerFilter.ClampToEdge,EG3dSamplerFilter.ClampToEdge);this.pushTexture(a,"diffuse");a=this._material.info();a.effectCode="eai.citys";a.optionAlpha=!0;a.ambientColor.setHex("#FFFFFF");this._material._textures=
this._textures;this.loadUrl("/script/ars/eai/city/"+this._level+".png")},MO.FEaiCitysRenderable_upload=function(){for(var a=this._citys,b=a.count(),d=0,c=0;c<b;c++){var e=a.at(c);e.visible()&&d++}for(var f=this._vertexCount=4*d,g=0,k=new Float32Array(3*f),m=0,l=new Uint8Array(4*f),c=0;c<b;c++)if(e=a.at(c),e.visible()){var e=e.location(),h=this._levelScale[this._level];k[g++]=e.x-h;k[g++]=e.y+h;k[g++]=0;k[g++]=e.x+h;k[g++]=e.y+h;k[g++]=0;k[g++]=e.x+h;k[g++]=e.y-h;k[g++]=0;k[g++]=e.x-h;k[g++]=e.y-h;
for(e=k[g++]=0;4>e;e++)l[m++]=255,l[m++]=255,l[m++]=255,l[m++]=255}this._vertexPositionBuffer.upload(k,12,f);this._vertexColorBuffer.upload(l,4,f);this._indexBuffer.setCount(6*d)},MO.FEaiCitysRenderable_loadUrl=function(a){var b=RClass.create(FImage);b.addLoadListener(this,this.onImageLoad);b.loadUrl(a);this._ready=!1},MO.FEaiCitysRenderable_dispose=function(){this._size=RObject.dispose(this._size);this._adjustSize=RObject.dispose(this._adjustSize);this._texture=RObject.dispose(this._texture);this._vertexPositionBuffer=
RObject.dispose(this._vertexPositionBuffer);this._vertexCoordBuffer=RObject.dispose(this._vertexCoordBuffer);this._indexBuffer=RObject.dispose(this._indexBuffer);this.__base.FE3dRenderable.dispose.call(this)};
with(MO)MO.FEaiCountryData=function(a){a=RClass.inherits(this,a,FObject,MListener);a._listenersLoad=RClass.register(a,new AListener("_listenersLoad",EEvent.Load));a._provinces=RClass.register(a,new AGetter("_provinces"));a.onLoaded=FEaiCountryData_onLoaded;a.construct=FEaiCountryData_construct;a.unserialize=FEaiCountryData_unserialize;a.load=FEaiCountryData_load;a.dispose=FEaiCountryData_dispose;return a},MO.FEaiCountryData_construct=function(){this.__base.FObject.construct.call(this);this._provinces=
new TDictionary},MO.FEaiCountryData_onLoaded=function(a){a=a.outputData();var b=RClass.create(FDataView);b.setEndianCd(!0);b.link(a);this.unserialize(b);b.dispose()},MO.FEaiCountryData_unserialize=function(a){for(var b=a.readInt32(),d=0;d<b;d++){var c=RClass.create(FEaiProvinceData);c.unserialize(a);this._provinces.set(c.name(),c)}a=new SEvent(this);this.processLoadListener(a);a.dispose()},MO.FEaiCountryData_load=function(){RConsole.find(FHttpConsole).send("/script/ars/eai/country.dat").addLoadListener(this,
this.onLoaded)},MO.FEaiCountryData_dispose=function(){this._provinces=RObject.dispose(this._provinces);this.__base.FObject.dispose.call(this)};
with(MO)MO.FEaiCountryEntity=function(a){a=RClass.inherits(this,a,FEaiEntity);a._cameraDirection=RClass.register(a,new AGetSet("_cameraDirection"));a._startDelay=RClass.register(a,new AGetSet("_startDelay"),0);a._riseDuration=RClass.register(a,new AGetSet("_riseDuration"),1200);a._riseDistance=RClass.register(a,new AGetSet("_riseDistance"),2050);a._fallDuration=RClass.register(a,new AGetSet("_fallDuration"),400);a._fallDistance=RClass.register(a,new AGetSet("_fallDistance"),50);a._blockInterval=RClass.register(a,
new AGetSet("_blockInterval"),60);a._mouseOverRiseHeight=RClass.register(a,new AGetSet("_mouseOverRiseHeight"),10);a._mouseMoveCheckInterval=RClass.register(a,new AGetSet("_mouseMoveCheckInterval"),100);a._cameraMoveDuration=RClass.register(a,new AGetSet("_cameraMoveDuration"),500);a._template=RClass.register(a,new AGetSet("_template"));a._introAnimeDone=RClass.register(a,new AGetSet("_introAnimeDone"),!1);a._startTime=RClass.register(a,new AGetSet("_startTime"));a._mouseOverRiseRenderable=RClass.register(a,
new AGetSet("_mouseOverRiseRenderable"));a._mouseOverFallArray=RClass.register(a,new AGetSet("_mouseOverFallArray"));a._mouseMoveLastCheck=RClass.register(a,new AGetSet("_mouseMoveLastCheck"));a._cameraMoving=RClass.register(a,new AGetSet("_cameraMoving"),!1);a._cameraFrom=RClass.register(a,new AGetSet("_cameraFrom"));a._cameraTo=RClass.register(a,new AGetSet("_cameraTo"));a.initialize=FEaiCountryEntity_initialize;a.introAnime=FEaiCountryEntity_introAnime;a.onMouseMove=FEaiCountryEntity_onMouseMove;
a.onMouseDown=FEaiCountryEntity_onMouseDown;a.mouseOverFallAnime=FEaiCountryEntity_mouseOverFallAnime;a.onOrganizationFetch=FEaiCountryEntity_onOrganizationFetch;a.cameraMoveAnime=FEaiCountryEntity_cameraMoveAnime;return a},MO.FEaiCountryEntity_initialize=function(a){this.setCameraDirection(new SVector3(.02,-.9,.5));this.setCameraFrom(new SPoint3);this.setCameraTo(new SPoint3);this.setMouseOverFallArray(new TObjects);this.setTemplate(a);this.setMouseMoveLastCheck(new Date);this.template().addEnterFrameListener(this,
FEaiCountryEntity_onEnterFrame);a=this.template().region();a.backgroundColor().set(.2,.2,.2,1);a=a.camera();a.setPosition(3,24,-.5);a.setDirection(this.cameraDirection().x,this.cameraDirection().y,this.cameraDirection().z);a=this.template().sprite();for(var b=0;b<a.renderables().count();b++)a.renderables().at(b).material().info().optionAlpha=!0;this.setStartTime(new Date)},MO.FEaiCountryEntity_onEnterFrame=function(){this.introAnimeDone()?this.cameraMoving()?this.cameraMoveAnime():this.mouseOverFallAnime():
this.introAnime()},MO.FEaiCountryEntity_introAnime=function(){var a=this.template().sprite(),b=(new Date).getTime()-this.startTime().getTime();if(!(b<this.startDelay())){b-=this.startDelay();if(b>this.riseDuration()+this.fallDuration()+this.blockInterval()*a.renderables().count()){this.setIntroAnimeDone(!0);var d=new TListener;d._owner=this;d._callback=this.onMouseMove;RWindow.lsnsMouseMove.push(d);d=new TListener;d._owner=this;d._callback=this.onMouseDown;RWindow.lsnsMouseDown.push(d);RConsole.find(FEnvironmentConsole).registerValue(EEaiConstant.ServiceHost,
"115.28.82.149");MO.RConsole.find(FEaiLogicConsole).organization().doFetch(this,this.onOrganizationFetch)}for(var d=b/this.blockInterval(),c=0;c<a.renderables().count()&&c<d;c++){var e=a.renderables().at(c).matrix(),f=(b-this.blockInterval()*c)/this.riseDuration(),g=0;1<f&&(f=1,g=(b-this.blockInterval()*c-this.riseDuration())/this.fallDuration(),1<g&&(g=1));e.ty=this.riseDistance()*f-this.fallDistance()*g;e.updateForce()}}},MO.FEaiCountryEntity_onMouseMove=function(a){(new Date).getDate()-this.mouseMoveLastCheck()<
this.mouseMoveCheckInterval||(a=RConsole.find(FG3dTechniqueConsole).find(canvas._graphicContext,FG3dSelectTechnique).test(this.template().region(),a.offsetX,a.offsetY),this.mouseOverRiseRenderable()!=a&&(this.mouseOverRiseRenderable()&&this.mouseOverFallArray().push(this.mouseOverRiseRenderable()),this.setMouseOverRiseRenderable(a),this.mouseOverFallArray().contains(this.mouseOverRiseRenderable())&&this.mouseOverFallArray().remove(this.mouseOverRiseRenderable())))},MO.FEaiCountryEntity_mouseOverFallAnime=
function(){for(var a=this.mouseOverFallArray().count()-1;0<=a;a--){var b=this.mouseOverFallArray().at(a).matrix();b.ty>this.riseDistance()-this.fallDistance()?--b.ty:(b.ty=this.riseDistance()-this.fallDistance(),this.mouseOverFallArray().erase(a));b.updateForce()}this.mouseOverRiseRenderable()&&(a=this.mouseOverRiseRenderable().matrix(),a.ty<this.riseDistance()-this.fallDistance()+this.mouseOverRiseHeight()&&(a.ty=this.riseDistance()-this.fallDistance()+this.mouseOverRiseHeight(),a.updateForce()))},
MO.FEaiCountryEntity_onOrganizationFetch=function(a){var b=a.content;a={};for(var d=0;d<b.collection.length;d++)a[b.collection[d].province_id]?(a[b.collection[d].province_id]++,null==b.collection[d].province_id&&b.collection[d].label):a[b.collection[d].province_id]=1;for(var d=MO.RConsole.find(FEaiLogicConsole),b=d.organization().dict(),c=d.organization().provinceColors(),d=0;d<b.count();d++){var e=a[b.name(d)];e||(e=0);var f=b.valueAt(d);if(!(0>f)){var f=this.template().sprite().renderables().at(f),
g=f.material().info().ambientColor;f.material().info();g.assign(c.at(0==e?0:4<Math.floor(e/5+1)?4:Math.floor(e/5+1)));f.material().update()}}},MO.FEaiCountryEntity_onMouseDown=function(a){var b=this.template().region().camera();if(a=RConsole.find(FG3dTechniqueConsole).find(canvas._graphicContext,FG3dSelectTechnique).test(this.template().region(),a.offsetX,a.offsetY)){a=a.calculateOutline();var d=new SOutline3d;d.calculateFrom(a,b.matrix());d=d.radius/Math.sin(b.projection().angle()/2)*Math.sin(90-
b.projection().angle()/2);a=a.center;a=new SPoint3(a.x-d*this.cameraDirection().x,a.y-d*this.cameraDirection().y,a.z-d*this.cameraDirection().z);b=b.position();this.setStartTime(new Date);this.cameraFrom().assign(b);this.cameraTo().assign(a);this.setCameraMoving(!0)}else b.setPosition(3,24,-.5),b.update()},MO.FEaiCountryEntity_cameraMoveAnime=function(){var a=((new Date).getTime()-this.startTime().getTime())/this.cameraMoveDuration();1<=a&&(a=1,this.setCameraMoving(!1));var a=1-(1-a)*(1-a),b=new SPoint3;
b.slerp(this.cameraFrom(),this.cameraTo(),a);var d=this.template().region().camera();d.position().assign(b);d.update();b=this.template().sprite();for(d=0;d<b.renderables().count();d++){var c=b.renderables().at(d);c!=this.mouseOverRiseRenderable()&&(c.material().info().alphaRate=1.5-a,c.material().update())}};
with(MO)MO.FEaiProvinceData=function(a){a=RClass.inherits(this,a,FEaiEntity);a._name=RClass.register(a,new AGetSet("_name"));a._color=RClass.register(a,new AGetSet("_color"));a._boundaries=RClass.register(a,new AGetter("_boundaries"));a.construct=FEaiProvinceData_construct;a.unserialize=FEaiProvinceData_unserialize;a.dispose=FEaiProvinceData_dispose;return a},MO.FEaiProvinceData_construct=function(){this.__base.FEaiEntity.construct.call(this);this._boundaries=new TObjects},MO.FEaiProvinceData_unserialize=
function(a){this._name=a.readString();this._color=a.readUint32();for(var b=a.readInt32(),d=0;d<b;d++){var c=RClass.create(FEaiBoundaryData);c.unserialize(a);this._boundaries.push(c)}},MO.FEaiProvinceData_dispose=function(){this._boundaries=RObject.dispose(this._boundaries);this.__base.FEaiEntity.dispose.call(this)};
with(MO)MO.FEaiProvinceEntity=function(a){a=RClass.inherits(this,a,FEaiEntity);a._data=RClass.register(a,new AGetSet("_data"));a._faceRenderable=RClass.register(a,new AGetter("_faceRenderable"));a._borderRenderable=RClass.register(a,new AGetter("_borderRenderable"));a._layerDepth=3;a.construct=FEaiProvinceEntity_construct;a.buildFace=FEaiProvinceEntity_buildFace;a.buildBorder=FEaiProvinceEntity_buildBorder;a.build=FEaiProvinceEntity_build;a.update=FEaiProvinceEntity_update;a.dispose=FEaiProvinceEntity_dispose;
return a},MO.FEaiProvinceEntity_construct=function(){this.__base.FEaiEntity.construct.call(this)},MO.FEaiProvinceEntity_buildFace=function(a){for(var b=this._data.boundaries(),d=b.count(),c=this._vertexTotal,e=this._indexTotal,f=0,g=0,k=new Float32Array(6*c),m=0,e=new Uint16Array(2*e+6*c),l=0;l<d;l++){for(var h=b.at(l),p=h.positionCount(),q=h.positions(),r=0,n=0;n<p;n++)k[g++]=q[r++],k[g++]=q[r++],k[g++]=0;h=h.indexes();q=h.length;for(n=0;n<q;n++)e[m++]=f+h[n];f+=p}for(var t=f,l=0;l<d;l++){h=b.at(l);
p=h.positionCount();q=h.positions();for(n=r=0;n<p;n++)k[g++]=q[r++],k[g++]=q[r++],k[g++]=this._layerDepth;h=h.indexes();q=h.length;for(n=0;n<q;n++)e[m++]=f+h[n];f+=p}for(l=f=0;l<d;l++){h=b.at(l);p=h.positionCount();for(n=0;n<p;n++)n==p-1?(e[m++]=f+n,e[m++]=f+0,e[m++]=f+n+t,e[m++]=f+0,e[m++]=f+t):(e[m++]=f+n,e[m++]=f+n+1,e[m++]=f+n+t,e[m++]=f+n+1,e[m++]=f+n+t+1),e[m++]=f+n+t;f+=p}d=0;b=this.colorsData=new Uint8Array(8*c);f=2*c;for(n=0;n<f;n++)b[d++]=8,b[d++]=13,b[d++]=25,b[d++]=255;n=this._faceRenderable=
MO.RClass.create(MO.FE3dDataBox);n.linkGraphicContext(a);n.setup();n.vertexPositionBuffer().upload(k,12,2*c);n.vertexColorBuffer().upload(b,4,2*c);n.indexBuffer().upload(e,m);n.material().info().optionDouble=!0},MO.FEaiProvinceEntity_buildBorder=function(a){for(var b=this._data.boundaries(),d=b.count(),c=this._vertexTotal,e=0,f=0,g=new Float32Array(6*c),k=0,m=new Uint16Array(2*c+2*c),l=0;l<d;l++){for(var h=b.at(l),p=h.positionCount(),q=h.positions(),r=0,h=0;h<p;h++)g[f++]=q[r++],g[f++]=q[r++],g[f++]=
0;for(h=0;h<p;h++)m[k++]=e+h,h==p-1?m[k++]=e:m[k++]=e+h+1;e+=p}for(var n=e,l=0;l<d;l++){h=b.at(l);p=h.positionCount();q=h.positions();for(h=r=0;h<p;h++)g[f++]=q[r++],g[f++]=q[r++],g[f++]=this._layerDepth;e+=p}for(l=e=0;l<d;l++){h=b.at(l);p=h.positionCount();for(h=0;h<p;h++)m[k++]=e+h,m[k++]=e+h+n;e+=p}d=0;b=this.colorsData=new Uint8Array(8*c);for(h=0;h<c;h++)b[d++]=0,b[d++]=193,b[d++]=237,b[d++]=255;for(h=0;h<c;h++)b[d++]=11,b[d++]=17,b[d++]=35,b[d++]=255;h=this._borderRenderable=MO.RClass.create(MO.FE3dDataBox);
h.linkGraphicContext(a);h.setup();h.vertexPositionBuffer().upload(g,12,2*c);h.vertexColorBuffer().upload(b,4,2*c);h.indexBuffer().setDrawModeCd(MO.EG3dDrawMode.Lines);h.indexBuffer().setLineWidth(1);h.indexBuffer().upload(m,k)},MO.FEaiProvinceEntity_build=function(a){for(var b=0,d=0,c=this._data.boundaries(),e=c.count(),f=0;f<e;f++)var g=c.at(f),b=b+g.positionCount(),d=d+g.indexes().length;this._vertexTotal=b;this._indexTotal=d;this.buildFace(a);this.buildBorder(a)},MO.FEaiProvinceEntity_update=function(a){a=
a.investmentTotal();Math.sqrt(a)},MO.FEaiProvinceEntity_dispose=function(){this.__base.FEaiEntity.dispose.call(this)};
MO.FEaiChartCustomerScene=function(a){a=MO.RClass.inherits(this,a,MO.FEaiChartScene);a._code=MO.EEaiScene.ChartCustomer;a._playing=!1;a._startDate=null;a._endDate=null;a._currentDate=null;a.onLoadData=MO.FEaiChartCustomerScene_onLoadData;a.onKeyDown=MO.FEaiChartCustomerScene_onKeyDown;a.setup=MO.FEaiChartCustomerScene_setup;a.selectDate=MO.FEaiChartCustomerScene_selectDate;a.active=MO.FEaiChartCustomerScene_active;a.process=MO.FEaiChartCustomerScene_process;a.deactive=MO.FEaiChartCustomerScene_deactive;
return a};MO.FEaiChartCustomerScene_onLoadData=function(a){this.__base.FEaiChartScene.onLoadData.call(this,a);a=this._currentDate.format("YYYYMMDD");this.selectDate(a)};
MO.FEaiChartCustomerScene_onKeyDown=function(a){a=a.keyCode;if(a==MO.EKeyCode.N){this._currentDate.addDay(-1);var b=this._currentDate.format("YYYYMMDD");this.selectDate(b);console.log(b)}a==MO.EKeyCode.M&&(this._currentDate.addDay(1),b=this._currentDate.format("YYYYMMDD"),this.selectDate(b),console.log(b));a==MO.EKeyCode.L&&(MO.RDate.autoParse(this._currentDate,"20140701"),this._playing=!0)};
MO.FEaiChartCustomerScene_selectDate=function(a){this.graphicContext();var b=this._activeStage;b.mapLayer();b.borderLayer();b.dataLayer();if(b=MO.Console.find(MO.FEaiResourceConsole).historyConsole().dates().get(a)){a=b.provinces();for(var d=a.count(),c=0;c<d;c++){var e=a.at(c);this._provinceEntities.get(e.code()).update(e)}for(var e=b.citys(),f=this._cityEntities,d=f.count(),c=0;c<d;c++){var g=f.at(c);a=g.data().code();a=e.get(a);g.update(a)}if(d=document.getElementById("id_total"))d.innerHTML=this._currentDate.format("YYYY-MM-DD")+
" "+b.investmentTotal()}this._citysRangeRenderable.upload()};MO.FEaiChartCustomerScene_setup=function(){this.__base.FEaiChartScene.setup.call(this);MO.RWindow.lsnsKeyDown.register(this,this.onKeyDown);this._currentDate=new MO.TDate;this._startDate=new MO.TDate;this._endDate=new MO.TDate;this._currentDate.parseAuto("20140701");this._startDate.parseAuto("20140701");this._endDate.parseAuto("20150618")};MO.FEaiChartCustomerScene_active=function(){this.__base.FEaiChartScene.active.call(this)};
MO.FEaiChartCustomerScene_process=function(){this.__base.FEaiChartScene.process.call(this);if(this._playing){this._currentDate.addDay(1);var a=this._currentDate.format("YYYYMMDD"),b=this._endDate.format("YYYYMMDD");this.selectDate(a);a==b&&(this._playing=!1)}};MO.FEaiChartCustomerScene_deactive=function(){this.__base.FEaiChartScene.deactive.call(this)};
MO.FEaiChartHistoryScene=function(a){a=MO.RClass.inherits(this,a,MO.FEaiChartScene);a._code=MO.EEaiScene.ChartHistory;a._playing=!0;a._lastTick=0;a._interval=10;a._startDate=null;a._endDate=null;a._currentDate=null;a._playButton=null;a._pauseButton=null;a._buttonTransform=null;a._timeline=null;a._buttonAudio=null;a.onLoadData=MO.FEaiChartHistoryScene_onLoadData;a.onDateSelect=MO.FEaiChartHistoryScene_onDateSelect;a.onOperationPlay=MO.FEaiChartHistoryScene_onOperationPlay;a.onOperationPause=MO.FEaiChartHistoryScene_onOperationPause;
a.setup=MO.FEaiChartHistoryScene_setup;a.selectDate=MO.FEaiChartHistoryScene_selectDate;a.switchPlay=MO.FEaiChartHistoryScene_switchPlay;a.active=MO.FEaiChartHistoryScene_active;a.process=MO.FEaiChartHistoryScene_process;a.deactive=MO.FEaiChartHistoryScene_deactive;return a};MO.FEaiChartHistoryScene_onLoadData=function(a){this.__base.FEaiChartScene.onLoadData.call(this,a);a=this._currentDate.format("YYYYMMDD");this.selectDate(a)};
MO.FEaiChartHistoryScene_onDateSelect=function(a){this._currentDate.date.setTime(a.date.date.getTime());this._currentDate.refresh();this.selectDate(this._currentDate.format("YYYYMMDD"))};MO.FEaiChartHistoryScene_onOperationPlay=function(a){a=this._currentDate.format("YYYYMMDD");var b=this._endDate.format("YYYYMMDD");a==b&&MO.RDate.autoParse(this._currentDate,"20140701");this.switchPlay(!0)};MO.FEaiChartHistoryScene_onOperationPause=function(a){this.switchPlay(!1)};
MO.FEaiChartHistoryScene_setup=function(){this.__base.FEaiChartScene.setup.call(this);var a=this._activeStage.faceLayer();this._currentDate=new MO.TDate;this._startDate=new MO.TDate;this._endDate=new MO.TDate;this._currentDate.parseAuto("20140701");this._startDate.parseAuto("20140701");this._endDate.parseAuto("20150618");var b=this._playButton=MO.Class.create(MO.FGuiPicture);b.linkGraphicContext(this);b.setLocation(40,730);b.setSize(196,196);b.setBackResource("url:/script/ars/eai/player.png");b.psInitialize();
b.build();b.setVisible(!0);b.addOperationDownListener(this,this.onOperationPlay);this._desktop.register(b);a.push(b);b=this._pauseButton=MO.Class.create(MO.FGuiPicture);b.linkGraphicContext(this);b.setLocation(40,730);b.setSize(196,196);b.setBackResource("url:/script/ars/eai/pause.png");b.psInitialize();b.build();b.setVisible(!1);b.addOperationDownListener(this,this.onOperationPause);this._desktop.register(b);a.push(b);(this._buttonAudio=MO.Class.create(MO.FAudio)).loadUrl("/script/ars/eai/button.mp3");
b=this._buttonTransform=MO.Class.create(MO.FGuiChangeTransform);b.setInterval(10);b.setScale(.1);for(var b=MO.Console.find(MO.FEaiResourceConsole).historyConsole().milestones(),d=this._milestoneBars=new MO.TObjects,c=b.count(),e=0;e<c;e++){var f=b.at(e),g=MO.Console.find(MO.FGuiFrameConsole).create(this,"eai.chart.MilestoneBar");g.setLocation(0,25+90*e);var k=new MO.TDate;k.parse(f.code());g.findComponent("date").setLabel(k.format("YYYY/MM/DD"));g.findComponent("total").setLabel(parseInt(f.investmentTotal()/
1E8)+"\u4ebf");a.push(g);this._desktop.register(g);d.push(g)}this.activeStage();b=this._timeline=MO.Class.create(MO.FGuiChartTimeline);b.setName("Timeline");b.setLeft(50);b.setTop(MO.Eai.Canvas.logicSize().height-400);b.setWidth(MO.Eai.Canvas.logicSize().width-300);b.setHeight(350);b.setTimeUnit(MO.EGuiTimeUnit.Month);b.setStartTime(this._startDate);b.setEndTime(this._endDate);b.setDegreeTime(this._currentDate);b.addDataChangedListener(this,this.onDateSelect);b.linkGraphicContext(this);b.build();
this._desktop.register(b);a.push(b)};
MO.FEaiChartHistoryScene_selectDate=function(a){this.graphicContext();var b=this._activeStage;b.mapLayer();b.borderLayer();b=MO.Console.find(MO.FEaiResourceConsole).historyConsole();MO.Console.find(MO.FEaiResourceConsole).provinceConsole();if(b=b.dates().get(a)){this._timeline.setDegreeTime(this._currentDate);this._timeline.repaint();for(var d=b.citys(),c=this._cityEntities,e=c.count(),f=0;f<e;f++){var g=c.at(f);a=g.data().code();a=d.get(a);g.update(a)}this._totalBar.findComponent("total").setLabel(MO.RFloat.unitFormat(b.investmentTotal(),0,
0,2,0,1E4,"\u4e07"));this._totalBar.repaint()}this._citysRangeRenderable.upload()};MO.FEaiChartHistoryScene_switchPlay=function(a){this._playing=a;this._buttonAudio.play(0);a?(this._playButton.setVisible(!1),this._pauseButton.setVisible(!0)):(this._playButton.setVisible(!0),this._pauseButton.setVisible(!1))};MO.FEaiChartHistoryScene_active=function(){this.__base.FEaiChartScene.active.call(this)};
MO.FEaiChartHistoryScene_process=function(){this.__base.FEaiChartScene.process.call(this);if(this._playing){var a=MO.Timer.current();if(a-this._lastTick>this._interval){this._currentDate.addDay(1);var b=this._currentDate.format("YYYYMMDD"),d=this._endDate.format("YYYYMMDD");this.selectDate(b);b==d&&this.switchPlay(!1);this._lastTick=a}a=this._citysRenderables;b=a.count();for(d=0;d<b;d++)a.at(d).upload();this._citysRangeRenderable.upload()}};MO.FEaiChartHistoryScene_deactive=function(){this.__base.FEaiChartScene.deactive.call(this)};
MO.FEaiChartIndustryScene=function(a){a=MO.RClass.inherits(this,a,MO.FEaiChartScene);a._code=MO.EEaiScene.ChartIndustry;a._playing=!1;a._startDate=null;a._endDate=null;a._currentDate=null;a.onLoadData=MO.FEaiChartIndustryScene_onLoadData;a.onKeyDown=MO.FEaiChartIndustryScene_onKeyDown;a.setup=MO.FEaiChartIndustryScene_setup;a.selectDate=MO.FEaiChartIndustryScene_selectDate;a.active=MO.FEaiChartIndustryScene_active;a.process=MO.FEaiChartIndustryScene_process;a.deactive=MO.FEaiChartIndustryScene_deactive;
return a};MO.FEaiChartIndustryScene_onLoadData=function(a){this.__base.FEaiChartScene.onLoadData.call(this,a);a=this._currentDate.format("YYYYMMDD");this.selectDate(a)};
MO.FEaiChartIndustryScene_onKeyDown=function(a){a=a.keyCode;if(a==MO.EKeyCode.N){this._currentDate.addDay(-1);var b=this._currentDate.format("YYYYMMDD");this.selectDate(b);console.log(b)}a==MO.EKeyCode.M&&(this._currentDate.addDay(1),b=this._currentDate.format("YYYYMMDD"),this.selectDate(b),console.log(b));a==MO.EKeyCode.L&&(MO.RDate.autoParse(this._currentDate,"20140701"),this._playing=!0)};
MO.FEaiChartIndustryScene_selectDate=function(a){this.graphicContext();var b=this._activeStage;b.mapLayer();b.borderLayer();b.dataLayer();if(b=MO.Console.find(MO.FEaiResourceConsole).historyConsole().dates().get(a)){a=b.provinces();for(var d=a.count(),c=0;c<d;c++){var e=a.at(c);this._provinceEntities.get(e.code()).update(e)}for(var e=b.citys(),f=this._cityEntities,d=f.count(),c=0;c<d;c++){var g=f.at(c);a=g.data().code();a=e.get(a);g.update(a)}if(d=document.getElementById("id_total"))d.innerHTML=this._currentDate.format("YYYY-MM-DD")+
" "+b.investmentTotal()}this._citysRangeRenderable.upload()};MO.FEaiChartIndustryScene_setup=function(){this.__base.FEaiChartScene.setup.call(this);MO.RWindow.lsnsKeyDown.register(this,this.onKeyDown);this._currentDate=new MO.TDate;this._startDate=new MO.TDate;this._endDate=new MO.TDate;this._currentDate.parseAuto("20140701");this._startDate.parseAuto("20140701");this._endDate.parseAuto("20150618")};MO.FEaiChartIndustryScene_active=function(){this.__base.FEaiChartScene.active.call(this)};
MO.FEaiChartIndustryScene_process=function(){this.__base.FEaiChartScene.process.call(this);if(this._playing){this._currentDate.addDay(1);var a=this._currentDate.format("YYYYMMDD"),b=this._endDate.format("YYYYMMDD");this.selectDate(a);a==b&&(this._playing=!1)}};MO.FEaiChartIndustryScene_deactive=function(){this.__base.FEaiChartScene.deactive.call(this)};
MO.FEaiChartInvestmentScene=function(a){a=MO.RClass.inherits(this,a,MO.FEaiChartScene);a._code=MO.EEaiScene.ChartInvestment;a._playing=!1;a._startDate=null;a._endDate=null;a._currentDate=null;a._timeline=null;a.onLoadData=MO.FEaiChartInvestmentScene_onLoadData;a.onKeyDown=MO.FEaiChartInvestmentScene_onKeyDown;a.setup=MO.FEaiChartInvestmentScene_setup;a.selectDate=MO.FEaiChartInvestmentScene_selectDate;a.active=MO.FEaiChartInvestmentScene_active;a.process=MO.FEaiChartInvestmentScene_process;a.deactive=
MO.FEaiChartInvestmentScene_deactive;a.onDateSelect=MO.FEaiChartInvestmentScene_onDateSelect;return a};MO.FEaiChartInvestmentScene_onLoadData=function(a){this.__base.FEaiChartScene.onLoadData.call(this,a);a=this._currentDate.format("YYYYMMDD");this.selectDate(a)};
MO.FEaiChartInvestmentScene_onKeyDown=function(a){a=a.keyCode;if(a==MO.EKeyCode.N){this._currentDate.addDay(-1);var b=this._currentDate.format("YYYYMMDD");this.selectDate(b);console.log(b)}a==MO.EKeyCode.M&&(this._currentDate.addDay(1),b=this._currentDate.format("YYYYMMDD"),this.selectDate(b),console.log(b));if(a==MO.EKeyCode.L){MO.RDate.autoParse(this._currentDate,"20140701");a=document.getElementById("id_investment_table");for(b=1;b<a.rows.length;b++)a.rows[b].style.display="none";this._playing=
!0}};
MO.FEaiChartInvestmentScene_selectDate=function(a){this.graphicContext();var b=this._activeStage;b.mapLayer();b.borderLayer();var b=MO.Console.find(MO.FEaiResourceConsole).historyConsole(),d=MO.Console.find(MO.FEaiResourceConsole).provinceConsole();if(b=b.dates().get(a)){a=b.provinces();for(var c=a.count(),e=document.getElementById("id_investment_table");e.rows.length<c+1;){var f=e.insertRow(e.rows.length);f.insertCell(0);f.insertCell(1);f.insertCell(2)}for(var g=0;g<c;g++){var k=a.at(g);this._provinceEntities.get(k.code()).update(k);var m=
d.findByCode(k.code()),f=e.rows[g+1];f.style.display="";f.className="DataGrid_Row";var l=f.cells[0],h=f.cells[1],f=f.cells[2];2<g&&(l.innerText=g+1);h.innerText=m.label();1E3<k.investmentTotal()?f.innerText=MO.RFloat.unitFormat(k.investmentTotal(),0,0,2,0,1E4,"\u4e07"):f.innerText=k.investmentTotal();f.align="right"}this._timeline.setDegreeTime(this._currentDate);this._timeline.repaint();d=b.citys();e=this._cityEntities;c=e.count();for(g=0;g<c;g++)k=e.at(g),a=k.data().code(),a=d.get(a),k.update(a);
this._totalBar.findComponent("total").setLabel(MO.RFloat.unitFormat(b.investmentTotal(),0,0,2,0,1E4,"\u4e07"));this._totalBar.repaint()}};
MO.FEaiChartInvestmentScene_setup=function(){this.__base.FEaiChartScene.setup.call(this);MO.RWindow.lsnsKeyDown.register(this,this.onKeyDown);this._currentDate=new MO.TDate;this._startDate=new MO.TDate;this._endDate=new MO.TDate;this._currentDate.parseAuto("20140701");this._startDate.parseAuto("20140701");this._endDate.parseAuto("20150618");for(var a=document.getElementById("id_investment_table"),b=0;3>b;b++){var d=a.insertRow(a.rows.length),c=d.insertCell(0);d.insertCell(1);d.insertCell(2);switch(b){case 0:d.style.color=
"#FFEA01";c.innerHTML="1 <IMG src='/script/ars/eai/medals/gold.png'/>";break;case 1:d.style.color="#C5D3D6";c.innerHTML="2 <IMG src='/script/ars/eai/medals/silver.png'/>";break;case 2:d.style.color="#E16A00",c.innerHTML="3 <IMG src='/script/ars/eai/medals/copper.png'/>"}}a=this.activeStage().faceLayer();b=this._timeline=MO.RClass.create(MO.FGuiChartTimeline);b.setName("Timeline");b.setLeft(50);b.setTop(MO.Eai.Canvas._size.height-400);b.setWidth(MO.Eai.Canvas._size.width-500);b.setHeight(350);b.setTimeUnit(MO.EGuiTimeUnit.Month);
b.setStartTime(this._startDate);b.setEndTime(this._endDate);b.setDegreeTime(this._currentDate);b.addDataChangedListener(this,this.onDateSelect);b.linkGraphicContext(this);b.build();this._desktop.register(b);a.push(b)};MO.FEaiChartInvestmentScene_onDateSelect=function(a){this._currentDate.date.setTime(a.date.date.getTime());this._currentDate.refresh();this.selectDate(this._currentDate.format("YYYYMMDD"))};MO.FEaiChartInvestmentScene_active=function(){this.__base.FEaiChartScene.active.call(this)};
MO.FEaiChartInvestmentScene_process=function(){this.__base.FEaiChartScene.process.call(this);if(this._playing){this._currentDate.addDay(1);var a=this._currentDate.format("YYYYMMDD"),b=this._endDate.format("YYYYMMDD");this.selectDate(a);a==b&&(this._playing=!1)}for(var a=this._citysRenderables,b=a.count(),d=0;d<b;d++)a.at(d).upload();this._citysRangeRenderable.upload()};MO.FEaiChartInvestmentScene_deactive=function(){this.__base.FEaiChartScene.deactive.call(this)};
MO.FEaiChartScene=function(a){a=MO.RClass.inherits(this,a,MO.FEaiScene);a._countryData=null;a._provinceEntities=MO.Class.register(a,new MO.AGetter("_provinceEntities"));a._cityEntities=MO.Class.register(a,new MO.AGetter("_cityEntities"));a._countryBorderDisplay=null;a._countryDisplay=null;a._citysRenderables=null;a._logoBar=null;a._titleBar=null;a._groundAutio=null;a.onLoadData=MO.FEaiChartScene_onLoadData;a.construct=MO.FEaiChartScene_construct;a.fixMatrix=MO.FEaiChartScene_fixMatrix;a.setup=MO.FEaiChartScene_setup;
a.active=MO.FEaiChartScene_active;a.process=MO.FEaiChartScene_process;a.deactive=MO.FEaiChartScene_deactive;a.dispose=MO.FEaiChartScene_dispose;return a};
MO.FEaiChartScene_onLoadData=function(a){var b=a.sender;a=this.graphicContext();for(var d=this._countryDisplay,c=this._countryBorderDisplay,e=MO.Console.find(MO.FEaiResourceConsole).provinceConsole(),b=b.provinces(),f=b.count(),g=0;g<f;g++){provinceData=b.at(g);var k=provinceData.name(),k=e.findByName(k),m=MO.Class.create(MO.FEaiProvinceEntity);m.setData(provinceData);m.build(a);this._provinceEntities.set(k.code(),m);d.pushRenderable(m.faceRenderable());c.pushRenderable(m.borderRenderable())}};
MO.FEaiChartScene_construct=function(){this.__base.FEaiScene.construct.call(this);this._provinceEntities=new MO.TDictionary;this._cityEntities=new MO.TDictionary;this._citysRenderables=new MO.TDictionary};MO.FEaiChartScene_fixMatrix=function(a){a.tx=-35;a.ty=-12.3;a.tz=0;a.setScale(.32,.36,.32);a.update()};
MO.FEaiChartScene_setup=function(){this.__base.FEaiScene.setup.call(this);var a=this.graphicContext();a.size();var b=this._activeStage=MO.Class.create(MO.FEaiChartStage);b.linkGraphicContext(this);b.region().linkGraphicContext(this);b.region().backgroundColor().set(0,0,0,0);var d=this._countryDisplay=MO.Class.create(MO.FE3dDisplay);this.fixMatrix(d.matrix());b.mapLayer().pushDisplay(d);d=this._countryBorderDisplay=MO.Class.create(MO.FE3dDisplay);this.fixMatrix(d.matrix());b.borderLayer().pushDisplay(d);
d=this._background=MO.Class.create(MO.FGuiPicture);d.linkGraphicContext(this);d.size().assign(MO.Eai.Canvas.screenSize());d.size().set(1920,1080);d.setBackResource("url:/script/ars/eai/background.png");d.psInitialize();d.build();d.renderable().setOptionFull(!0);this._desktop.register(d);b.groundLayer().push(d);d=this._citysRangeRenderable=MO.Class.create(MO.FEaiCitysRangeRenderable);d.linkGraphicContext(this);this.fixMatrix(d.matrix());b.cityRangeLayer().push(d);for(var c=this._citysRenderables,e=
4;1<=e;e--){var f=MO.Class.create(MO.FEaiCitysRenderable);f.setLevel(e);f.linkGraphicContext(this);this.fixMatrix(f.matrix());b.cityLayer().push(f);c.set(e,f)}for(var f=MO.Console.find(MO.FEaiResourceConsole).cityConsole().citys(),g=f.count(),e=0;e<g;e++){var k=f.at(e),m=k.level();k.location();var l=MO.Class.create(MO.FEaiCityEntity);l.setData(k);l.build(a);this._cityEntities.set(k.code(),l);k=c.get(m);k.citys().push(l);d.citys().push(l)}a=c.count();for(e=0;e<a;e++)k=c.at(e),k.setup(),k.upload();
d.setup();d.upload();a=this._logoBar=MO.RConsole.find(MO.FGuiFrameConsole).get(this,"eai.chart.LogoBar");a.setLocation(10,10);b.faceLayer().push(a);this._desktop.register(a);d=new MO.TDate;a.findComponent("date").setLabel(d.format("YYYY/MM/DD"));a.findComponent("time").setLabel(d.format("HH24:MI"));a=this._totalBar=MO.RConsole.find(MO.FGuiFrameConsole).get(this,"eai.chart.TotalBar");a.setLocation(650,20);b.faceLayer().push(a);this._desktop.register(a);b=this._groundAutio=MO.Class.create(MO.FAudio);
b.loadUrl("/script/ars/eai/ground.mp3");b.setVolume(.5);b.play();b=this._countryData=MO.Class.create(MO.FEaiCountryData);b.addLoadListener(this,this.onLoadData);b.load()};MO.FEaiChartScene_active=function(){this.__base.FEaiScene.active.call(this)};MO.FEaiChartScene_active=function(){this.__base.FEaiScene.active.call(this)};MO.FEaiChartScene_process=function(){this.__base.FEaiScene.process.call(this)};
MO.FEaiChartScene_dispose=function(){this._provinceEntities=RObject.dispose(this._provinceEntities);this._cityEntities=RObject.dispose(this._cityEntities);this.__base.FEaiScene.dispose.call(this)};
MO.FEaiChartStage=function(a){a=MO.RClass.inherits(this,a,MO.FE3dStage);a._groundLayer=MO.RClass.register(a,new MO.AGetter("_groundLayer"));a._mapLayer=MO.RClass.register(a,new MO.AGetter("_mapLayer"));a._borderLayer=MO.RClass.register(a,new MO.AGetter("_borderLayer"));a._cityRangeLayer=MO.RClass.register(a,new MO.AGetter("_cityRangeLayer"));a._cityLayer=MO.RClass.register(a,new MO.AGetter("_cityLayer"));a._faceLayer=MO.RClass.register(a,new MO.AGetter("_faceLayer"));a.construct=MO.FEaiChartStage_construct;
return a};
MO.FEaiChartStage_construct=function(){this.__base.FE3dStage.construct.call(this);var a=this._groundLayer=MO.RClass.create(MO.FDisplayLayer);this.registerLayer("GroundLayer",a);a=this._mapLayer=MO.RClass.create(MO.FDisplayLayer);a.setOptionClearDepth(!0);this.registerLayer("MapLayer",a);a=this._borderLayer=MO.RClass.create(MO.FDisplayLayer);this.registerLayer("BorderLayer",a);a=this._cityRangeLayer=MO.RClass.create(MO.FDisplayLayer);a.setOptionClearDepth(!0);this.registerLayer("CityRangeLayer",a);
a=this._cityLayer=MO.RClass.create(MO.FDisplayLayer);a.setOptionClearDepth(!0);this.registerLayer("CityLayer",a);a=this._faceLayer=MO.RClass.create(MO.FDisplayLayer);a.setOptionClearDepth(!0);this.registerLayer("FaceLayer",a)};MO.FEaiCompanyScene=function(a){a=MO.RClass.inherits(this,a,MO.FEaiScene);a._code=MO.EEaiScene.Company;return a};
MO.FEaiCountryScene=function(a){a=MO.RClass.inherits(this,a,MO.FEaiScene);a._code=MO.EEaiScene.Country;a._countryTemplate=null;a._countryLogoBar=null;a.onTemplateLoad=MO.FEaiCountryScene_onTemplateLoad;a.setup=MO.FEaiCountryScene_setup;a.active=MO.FEaiCountryScene_active;a.deactive=MO.FEaiCountryScene_deactive;return a};MO.FEaiCountryScene_onTemplateLoad=function(a){a=this._countryTemplate.sprite().matrix();a.tx=-4;a.ty=-3;a.rx=-Math.PI/2;a.updateForce();MO.Eai.Canvas.activeStage()};
MO.FEaiCountryScene_setup=function(){this.__base.FEaiScene.setup.call(this);var a=this._countryLogoBar=MO.RConsole.find(MO.FGuiFrameConsole).get(MO.Eai.Canvas,"eai.country.LogoBar");this.registerFrame(a)};MO.FEaiCountryScene_active=function(){this.__base.FEaiScene.active.call(this)};MO.FEaiCountryScene_deactive=function(){this.__base.FEaiScene.deactive.call(this);MO.Eai.Canvas.activeStage().faceLayer().removeRenderable(this._countryLogoBar.renderable())};
MO.FEaiGroupReportScene=function(a){a=MO.RClass.inherits(this,a,MO.FEaiScene);a._code=MO.EEaiScene.GroupReport;return a};MO.FEaiGroupScene=function(a){a=MO.RClass.inherits(this,a,MO.FEaiScene);a._code=MO.EEaiScene.Group;return a};
with(MO)MO.FEaiScene=function(a){a=RClass.inherits(this,a,FScene);a._desktop=RClass.register(a,new AGetter("_desktop"));a._engineInfo=null;a.onProcess=MO.FEaiScene_onProcess;a.construct=MO.FEaiScene_construct;a.setup=MO.FEaiScene_setup;a.active=MO.FEaiScene_active;a.deactive=MO.FEaiScene_deactive;a.processEvent=FEaiScene_processEvent;a.dispose=MO.FEaiScene_dispose;return a},MO.FEaiScene_onProcess=function(){this._desktop.process();this.__base.FScene.onProcess.call(this)},MO.FEaiScene_construct=function(){this.__base.FScene.construct.call(this)},
MO.FEaiScene_setup=function(){this.__base.FScene.setup.call(this);var a=this._engineInfo=MO.Class.create(MO.FGuiEngineInfo);a.linkGraphicContext(this);a.setContext(this.graphicContext());a.location().set(10,300);a.build();var b=this._desktop=RClass.create(FGuiDesktop);b.linkGraphicContext(this);b.setup();b.register(a)},MO.FEaiScene_active=function(){this.__base.FScene.active.call(this);var a=this._activeStage;MO.Eai.Canvas.selectStage(a);a=this._activeStage;a.faceLayer();this._engineInfo.setStage(a)},
MO.FEaiScene_deactive=function(){this.__base.FScene.deactive.call(this);this._activeStage.faceLayer().remove(this._engineInfo.renderable());MO.Eai.Canvas.selectStage(null)},MO.FEaiScene_processEvent=function(a){this.__base.FScene.processEvent();this._desktop.processEvent(a)},MO.FEaiScene_dispose=function(){this._desktop=RObject.dispose(this._desktop);this.__base.FScene.dispose.call(this)};with(MO)MO.FEaiChapter=function(a){return a=RClass.inherits(this,a,FChapter)};
MO.FEaiChartChapter=function(a){a=MO.RClass.inherits(this,a,MO.FEaiChapter);a._code=MO.EEaiChapter.Chart;a._sceneHistory=MO.Class.register(a,new MO.AGetter("_sceneHistory"));a._sceneIndustry=MO.Class.register(a,new MO.AGetter("_sceneIndustry"));a._sceneInvestment=MO.Class.register(a,new MO.AGetter("_sceneInvestment"));a._sceneCustomer=MO.Class.register(a,new MO.AGetter("_sceneCustomer"));a.construct=MO.FEaiChartChapter_construct;a.setup=MO.FEaiChartChapter_setup;a.process=MO.FEaiChartChapter_process;
a.dispose=MO.FEaiChartChapter_dispose;return a};MO.FEaiChartChapter_construct=function(){this.__base.FEaiChapter.construct.call(this)};
MO.FEaiChartChapter_setup=function(){var a=this._sceneHistory=MO.RClass.create(MO.FEaiChartHistoryScene);a.linkGraphicContext(this);this.registerScene(a);a=this._sceneIndustry=MO.RClass.create(MO.FEaiChartIndustryScene);a.linkGraphicContext(this);this.registerScene(a);a=this._sceneInvestment=MO.RClass.create(MO.FEaiChartInvestmentScene);a.linkGraphicContext(this);this.registerScene(a);a=this._sceneCustomer=MO.RClass.create(MO.FEaiChartCustomerScene);a.linkGraphicContext(this);this.registerScene(a)};
MO.FEaiChartChapter_process=function(){this.__base.FEaiChapter.process.call(this)};MO.FEaiChartChapter_dispose=function(){this.__base.FEaiChapter.dispose.call(this)};MO.FEaiLoadingChapter=function(a){a=MO.RClass.inherits(this,a,MO.FEaiChapter);a._code=MO.EEaiChapter.Loading;return a};MO.FEaiLoginChapter=function(a){a=MO.RClass.inherits(this,a,MO.FEaiChapter);a._code=MO.EEaiChapter.Login;return a};
MO.FEaiSceneChapter=function(a){a=MO.RClass.inherits(this,a,MO.FEaiChapter);a._code=MO.EEaiChapter.Scene;a._sceneCountry=null;a._sceneGroup=null;a._sceneGroupReport=null;a._sceneCompany=null;a.construct=MO.FEaiSceneChapter_construct;a.setup=MO.FEaiSceneChapter_setup;a.process=MO.FEaiSceneChapter_process;a.dispose=MO.FEaiSceneChapter_dispose;return a};MO.FEaiSceneChapter_construct=function(){this.__base.FEaiChapter.construct.call(this)};
MO.FEaiSceneChapter_setup=function(){var a=this._sceneCountry=MO.RClass.create(MO.FEaiCountryScene);a.linkGraphicContext(this);this.registerScene(a);a=this._sceneGroup=MO.RClass.create(MO.FEaiGroupScene);a.linkGraphicContext(this);this.registerScene(a);a=this._sceneGroupReport=MO.RClass.create(MO.FEaiGroupReportScene);a.linkGraphicContext(this);this.registerScene(a);a=this._sceneCompany=MO.RClass.create(MO.FEaiCompanyScene);a.linkGraphicContext(this);this.registerScene(a)};
MO.FEaiSceneChapter_process=function(){this.__base.FEaiChapter.process.call(this)};MO.FEaiSceneChapter_dispose=function(){this.__base.FEaiChapter.dispose.call(this)};
with(MO)MO.FEaiApplication=function(a){a=RClass.inherits(this,a,FApplication);a._thread=null;a._interval=10;a.construct=FEaiApplication_construct;a.createCanvas=FEaiApplication_createCanvas;a.setup=FEaiApplication_setup;a.dispose=FEaiApplication_dispose;return a},MO.FEaiApplication_construct=function(){this.__base.FApplication.construct.call(this);var a=this._thread=RClass.create(FThread);a.setInterval(this._interval);a.addProcessListener(this,this.process);RConsole.find(FThreadConsole).start(a)},
MO.FEaiApplication_createCanvas=function(){return RClass.create(FEaiCanvas)},MO.FEaiApplication_setup=function(a){a=RConsole.find(FG3dEffectConsole);a.register("general.color.eai.citys",FEaiCityEffect);a.register("general.color.eai.citys.range",FEaiCityRangeEffect)},MO.FEaiApplication_dispose=function(){this.__base.FApplication.dispose.call(this)};
with(MO)MO.FEaiCanvas=function(a){a=RClass.inherits(this,a,FE3dCanvas);a._scaleRate=1;a._optionAlpha=!0;a._activeStage=RClass.register(a,new AGetter("_activeStage"));a._capturePosition=null;a._captureRotation=null;a.onResize=FEaiCanvas_onResize;a.construct=FEaiCanvas_construct;a.selectStage=FEaiCanvas_selectStage;a.dispose=FEaiCanvas_dispose;return a},MO.FEaiCanvas_onResize=function(a){this.__base.FE3dCanvas.onResize.call(this,a);a=this._graphicContext.size();var b=this._activeStage;b&&(b=b.camera().projection(),
b.size().set(a.width,a.height),b.update())},MO.FEaiCanvas_construct=function(){this.__base.FE3dCanvas.construct.call(this);this._rotation=new SVector3;this._capturePosition=new SPoint2;this._captureRotation=new SVector3},MO.FEaiCanvas_selectStage=function(a){a.linkGraphicContext(this);a.region().linkGraphicContext(this);a.selectTechnique(this,FE3dGeneralTechnique);var b=a.region().camera(),d=b.projection();d.setAngle(80);d.size().set(this._hCanvas.offsetWidth,this._hCanvas.offsetHeight);d.update();
b.position().set(0,0,-10);b.lookAt(0,0,0);b.update();this._activeStage=a},MO.FEaiCanvas_dispose=function(){this._rotation=RObject.dispose(this._rotation);this.__base.FE3dCanvas.dispose.call(this)};
with(MO)MO.FEaiChartApplication=function(a){a=RClass.inherits(this,a,FEaiApplication);a._sceneCode=RClass.register(a,new AGetSet("_sceneCode"),MO.EEaiScene.ChartHistory);a._chapterLoading=RClass.register(a,new AGetter("_chapterLoading"));a._chapterChart=RClass.register(a,new AGetter("_chapterChart"));a._thread=null;a._interval=10;a.onLoadResource=FEaiChartApplication_onLoadResource;a.construct=FEaiChartApplication_construct;a.createCanvas=FEaiChartApplication_createCanvas;a.setup=FEaiChartApplication_setup;
a.dispose=FEaiChartApplication_dispose;return a},MO.FEaiChartApplication_onLoadResource=function(){this.selectChapterByCode(MO.EEaiChapter.Chart).selectSceneByCode(this._sceneCode)},MO.FEaiChartApplication_construct=function(){this.__base.FEaiApplication.construct.call(this)},MO.FEaiChartApplication_createCanvas=function(){return RClass.create(FEaiChartCanvas)},MO.FEaiChartApplication_setup=function(a){this.__base.FEaiApplication.setup.call(this,a);this._hPanel=a;var b=MO.Eai.Canvas=this._canvas=
this.createCanvas();b.build(a);b.setPanel(a);this.linkGraphicContext(b);a=this._chapterLoading=MO.RClass.create(MO.FEaiLoadingChapter);a.linkGraphicContext(this);this.registerChapter(a);a=this._chapterChart=MO.RClass.create(MO.FEaiChartChapter);a.linkGraphicContext(this);this.registerChapter(a);a=MO.RConsole.find(MO.FEaiResourceConsole);a.addLoadListener(this,this.onLoadResource);a.load()},MO.FEaiChartApplication_dispose=function(){this._chapterLoading=RObject.dispose(this._chapterLoading);this._chapterChart=
RObject.dispose(this._chapterChart);this.__base.FEaiApplication.dispose.call(this)};
with(MO)MO.FEaiChartCanvas=function(a){a=RClass.inherits(this,a,FEaiCanvas);a._capturePosition=null;a._cameraPosition=null;a.onEnterFrame=FEaiChartCanvas_onEnterFrame;a.onMouseCaptureStart=FEaiChartCanvas_onMouseCaptureStart;a.onMouseCapture=FEaiChartCanvas_onMouseCapture;a.onMouseCaptureStop=FEaiChartCanvas_onMouseCaptureStop;a.construct=FEaiChartCanvas_construct;a.setPanel=FEaiChartCanvas_setPanel;a.dispose=FEaiChartCanvas_dispose;return a},MO.FEaiChartCanvas_onEnterFrame=function(){var a=this._activeStage;
if(a){var a=a.camera(),b=RKeyboard.isPress(EKeyCode.W),d=RKeyboard.isPress(EKeyCode.S);b&&!d&&a.doMoveY(.5);!b&&d&&a.doMoveY(-.5);b=RKeyboard.isPress(EKeyCode.A);d=RKeyboard.isPress(EKeyCode.D);b&&!d&&a.doMoveX(-.5);!b&&d&&a.doMoveX(.5);a.update()}},MO.FEaiChartCanvas_onMouseCaptureStart=function(a){var b=this._activeStage;b&&(this._capturePosition.set(a.clientX,a.clientY),this._cameraPosition.assign(b.camera().position()))},MO.FEaiChartCanvas_onMouseCapture=function(a){var b=this._activeStage;if(b){var d=
a.clientX-this._capturePosition.x;a=a.clientY-this._capturePosition.y;b=b.camera().position();b.x=this._cameraPosition.x-.03*d;b.y=this._cameraPosition.y+.03*a}},MO.FEaiChartCanvas_onMouseCaptureStop=function(a){},MO.FEaiChartCanvas_construct=function(){this.__base.FEaiCanvas.construct.call(this);this._logicSize=new SSize2(1920,1080);this._cameraPosition=new SPoint3},MO.FEaiChartCanvas_setPanel=function(a){this.__base.FEaiCanvas.setPanel.call(this,a)},MO.FEaiChartCanvas_dispose=function(){this._cameraPosition=
RObject.dispose(this._cameraPosition);this.__base.FEaiCanvas.dispose.call(this)};
with(MO)MO.FEaiPlatformApplication=function(a){a=RClass.inherits(this,a,FEaiApplication);a._chapterLoading=RClass.register(a,new AGetter("_chapterLoading"));a._chapterLogin=RClass.register(a,new AGetter("_chapterLogin"));a._chapterScene=RClass.register(a,new AGetter("_chapterScene"));a._chapterChart=RClass.register(a,new AGetter("_chapterChart"));a._thread=null;a._interval=10;a.onLoadResource=FEaiPlatformApplication_onLoadResource;a.construct=FEaiPlatformApplication_construct;a.createCanvas=FEaiPlatformApplication_createCanvas;
a.setup=FEaiPlatformApplication_setup;a.dispose=FEaiPlatformApplication_dispose;return a},MO.FEaiPlatformApplication_onLoadResource=function(){this.selectChapterByCode(MO.EEaiChapter.Scene).selectSceneByCode(MO.EEaiScene.Country)},MO.FEaiPlatformApplication_construct=function(){this.__base.FEaiApplication.construct.call(this)},MO.FEaiPlatformApplication_createCanvas=function(){return RClass.create(FEaiPlatformCanvas)},MO.FEaiPlatformApplication_setup=function(){var a=this._chapterLoading=MO.RClass.create(MO.FEaiLoadingChapter);
a.linkGraphicContext(this);this.registerChapter(a);a=this._chapterLogin=MO.RClass.create(MO.FEaiLoginChapter);a.linkGraphicContext(this);this.registerChapter(a);a=this._chapterScene=MO.RClass.create(MO.FEaiSceneChapter);a.linkGraphicContext(this);this.registerChapter(a);a=this._chapterChart=MO.RClass.create(MO.FEaiChartChapter);a.linkGraphicContext(this);this.registerChapter(a);a=MO.RConsole.find(MO.FEaiResourceConsole);a.addLoadListener(this,this.onLoadResource);a.load()},MO.FEaiPlatformApplication_dispose=
function(){this.__base.FEaiApplication.dispose.call(this)};
with(MO)MO.FEaiPlatformCanvas=function(a){a=RClass.inherits(this,a,FEaiCanvas);a._capturePosition=null;a._captureRotation=null;a.onEnterFrame=FEaiPlatformCanvas_onEnterFrame;a.onMouseCaptureStart=FEaiPlatformCanvas_onMouseCaptureStart;a.onMouseCapture=FEaiPlatformCanvas_onMouseCapture;a.onMouseCaptureStop=FEaiPlatformCanvas_onMouseCaptureStop;a.construct=FEaiPlatformCanvas_construct;a.dispose=FEaiPlatformCanvas_dispose;return a},MO.FEaiPlatformCanvas_onEnterFrame=function(){var a=this._activeStage;
if(a){var b=a.camera(),d=.05,c=RKeyboard.isPress(EKeyCode.W),e=RKeyboard.isPress(EKeyCode.S);c&&!e&&b.doWalk(.5);!c&&e&&b.doWalk(-.5);c=RKeyboard.isPress(EKeyCode.A);e=RKeyboard.isPress(EKeyCode.D);c&&!e&&b.doYaw(d);!c&&e&&b.doYaw(-d);c=RKeyboard.isPress(EKeyCode.Q);e=RKeyboard.isPress(EKeyCode.E);c&&!e&&b.doFly(.5);!c&&e&&b.doFly(-.5);e=RKeyboard.isPress(EKeyCode.Z);c=RKeyboard.isPress(EKeyCode.X);e&&!c&&b.doPitch(d);!e&&c&&b.doPitch(-d);b.update();if(this._optionRotation){d=this._rotation;a=a.layers();
b=a.count();for(c=0;c<b;c++)e=a.value(c).matrix(),e.setRotation(0,d.y,0),e.update();d.y+=.01}}},MO.FEaiPlatformCanvas_onMouseCaptureStart=function(a){var b=this._activeStage;if(b){var d=this._activeStage.region();RConsole.find(FG3dTechniqueConsole).find(this._graphicContext,FG3dSelectTechnique).test(d,a.offsetX,a.offsetY);this._capturePosition.set(a.clientX,a.clientY);this._captureRotation.assign(b.camera()._rotation)}},MO.FEaiPlatformCanvas_onMouseCapture=function(a){if(this._activeStage){var b=
a.clientX-this._capturePosition.x;a=a.clientY-this._capturePosition.y;var d=this._activeStage.camera().rotation(),c=this._captureRotation;d.x=c.x+.003*a;d.y=c.y+.003*b}},MO.FEaiPlatformCanvas_onMouseCaptureStop=function(a){},MO.FEaiPlatformCanvas_construct=function(){this.__base.FEaiCanvas.construct.call(this)},MO.FEaiPlatformCanvas_dispose=function(){this.__base.FEaiCanvas.dispose.call(this)};MO.Eai.setup=function(a,b){};
