var LZMA=function(){function q(a,c){function b(){}f=b.prototype=c||new bc;f.getClass$=La;f.typeId$=a;return b}function qa(a,c){postMessage({action:3,callback_num:c,result:a})}function n(a,c,b,e,d){var g=Array(e);if(0<d&&(d=[null,0,!1,[0,0]][d],"number"!==typeof d))for(var m=0;m<e;++m)g[m]=d;aa();gb(g,Ba,ra);g.arrayClass$=a;g.typeId$=c;g.queryId$=b;return g}function cc(a,c,b,e){aa();gb(e,Ba,ra);e.arrayClass$=a;e.typeId$=c;e.queryId$=b;return e}function hb(a,c,b){if(null!=b){var e;if(e=0<a.queryId$)e=
b.typeId$,e=!(e&&ib[e][a.queryId$]);if(e)throw new U;if(0>a.queryId$&&(b.typeMarker$==E||2==b.typeId$))throw new U;}return a[c]=b}function aa(){aa=E;Ba=[];ra=[];var a=new dc,c=Ba,b=ra,e=0,d,g;for(g in a)if(d=a[g])c[e]=g,b[e]=d,++e}function gb(a,c,b){aa();for(var e=0,d=c.length;e<d;++e)a[c[e]]=b[e]}function jb(a,c){var b;if(b=null!=a)b=a.typeId$,b=!(b&&ib[b][c]);if(b)throw new ec;return a}function da(a,c){return Ca(a[0]+c[0],a[1]+c[1])}function kb(a,c){var b=~~Math.max(Math.min(a[1]/4294967296,2147483647),
-2147483648)&~~Math.max(Math.min(c[1]/4294967296,2147483647),-2147483648),e=R(a)&R(c),d;d=e;0>e&&(d+=4294967296);return[d,4294967296*b]}function Da(a,c){var b,e;if(a[0]==c[0]&&a[1]==c[1])return 0;b=0>a[1];e=0>c[1];return b&&!e?-1:!b&&e?1:0>Ca(a[0]-c[0],a[1]-c[1])[1]?-1:1}function Ca(a,c){var b,e;c%=1.8446744073709552E19;a%=1.8446744073709552E19;b=c%4294967296;e=4294967296*Math.floor(a/4294967296);c=c-b+e;for(a=a-e+b;0>a;)a+=4294967296,c-=4294967296;for(;4294967295<a;)a-=4294967296,c+=4294967296;for(c%=
1.8446744073709552E19;0x7fffffff00000000<c;)c-=1.8446744073709552E19;for(;-9223372036854775808>c;)c+=1.8446744073709552E19;return[a,c]}function Va(a,c){return a[0]==c[0]&&a[1]==c[1]}function ea(a){var c,b;return-129<a&&128>a?(c=a+128,b=(lb(),Wa)[c],null==b&&(b=Wa[c]=0<=a?[a,0]:[a+4294967296,-4294967296]),b):0<=a?[a,0]:[a+4294967296,-4294967296]}function R(a){return 2147483648<=a[0]?~~Math.max(Math.min(a[0]-4294967296,2147483647),-2147483648):~~Math.max(Math.min(a[0],2147483647),-2147483648)}function mb(a){var c;
if(Va(a,(ba(),S)))return S;c=-a[1];a=-a[0];4294967295<a&&(a-=4294967296,c+=4294967296);0>a&&(a+=4294967296,c-=4294967296);return[a,c]}function sa(a){return 30>=a?1<<a:sa(30)*sa(a-30)}function Xa(a,c){var b,e,d;c&=63;if(Va(a,(ba(),S)))return 0==c?a:Ya;if(0>a[1])return mb(Xa(mb(a),c));b=sa(c);e=a[1]*b%1.8446744073709552E19;d=a[0]*b;b=d-d%4294967296;e+=b;0x7fffffffffffffff<=e&&(e-=1.8446744073709552E19);return[d-b,e]}function nb(a,c){var b;b=sa(c&63);return Ca(Math.floor(a[0]/b),a[1]/b)}function lb(){lb=
E;Wa=n(fc,0,9,256,0)}function ba(){ba=E;Math.log(2);ob=gc;S=hc;ea(-1);ea(1);pb=ea(2);Ya=ea(0)}function qb(a,c){var b=c.length;a.buf=c;a.pos=0;a.count=0+b;a.count>c.length&&(a.count=c.length);return a}function Ea(a){return a.pos>=a.count?-1:a.buf[a.pos++]&255}function rb(a){a.buf=n(fa,0,-1,32,1);return a}function Fa(a,c){var b;c<=a.buf.length||(c=Za(c,2*a.buf.length),b=n(fa,0,-1,c,1),va(a.buf,0,b,0,a.buf.length),a.buf=b)}function sb(a){var c;c=n(fa,0,-1,a.count,1);va(a.buf,0,c,0,a.count);return c}
function Pa(a,c){a.detailMessage=c;return a}function I(a,c){var b;b=new ic;b.typeName=a+c;return b}function Za(a,c){return a>c?a:c}function wa(a,c){return a<c?a:c}function va(a,c,b,e,d){var g,m,k,l;if(null==a||null==b)throw new jc;k=(a.typeMarker$==E||2==a.typeId$?a.getClass$():La()).typeName;g=(b.typeMarker$==E||2==b.typeId$?b.getClass$():La()).typeName;if(91!=k.charCodeAt(0)||91!=g.charCodeAt(0))throw c=new U,c.detailMessage="Must be array types",c;if(k.charCodeAt(1)!=g.charCodeAt(1))throw c=new U,
c.detailMessage="Array types must match",c;l=a.length;m=b.length;if(0>c||0>e||0>d||c+d>l||e+d>m)throw new kc;if(m=76==k.charCodeAt(1)||91==k.charCodeAt(1))g=null==g?!1:String(k)==g,m=!g;if(m)if(k=jb(a,3),g=jb(b,3),(null==a?null:a)===(null==b?null:b)&&c<e)for(c+=d,a=e+d;a-- >e;)hb(g,a,k[--c]);else for(a=e+d;e<a;)hb(g,e++,k[c++]);else for(g=0;g<d;++g)b[e+g]=a[c+g]}function tb(a){try{var c;a:{var b=a.chunker,e;if(!b.alive)throw new lc;e=!0;try{if(b.encoder){b:{var d=b.encoder,g=b.encoder.processedInSize,
m=b.encoder.processedOutSize,k=b.encoder.finished,l,h,z,f,n,r,w,u,q,t,v,C,y,B,J;g[0]=V;m[0]=V;k[0]=!0;if(d._inStream){d._matchFinder._stream=d._inStream;var W=d._matchFinder;W._bufferOffset=0;W._pos=0;W._streamPos=0;W._streamEndWasReached=!1;ub(W);W._cyclicBufferPos=0;vb(W,-1);d._needReleaseMFStream=!0;d._inStream=null}if(!d._finished){d._finished=!0;B=d.nowPos64;if(Va(d.nowPos64,V)){if(0==Ma(d._matchFinder)){$a(d,R(d.nowPos64));break b}ab(d);y=R(d.nowPos64)&d._posStateMask;x(d._rangeEncoder,d._isMatch,
(d._state<<4)+y,0);d._state=ta(d._state);z=K(d._matchFinder,-d._additionalOffset);wb(Ga(d._literalEncoder,R(d.nowPos64),d._previousByte),d._rangeEncoder,z);d._previousByte=z;--d._additionalOffset;d.nowPos64=da(d.nowPos64,xb)}if(0==Ma(d._matchFinder))$a(d,R(d.nowPos64));else for(;;){w=mc(d,R(d.nowPos64));t=d.backRes;y=R(d.nowPos64)&d._posStateMask;h=(d._state<<4)+y;if(1==w&&-1==t){x(d._rangeEncoder,d._isMatch,h,0);z=K(d._matchFinder,-d._additionalOffset);J=Ga(d._literalEncoder,R(d.nowPos64),d._previousByte);
if(7>d._state)wb(J,d._rangeEncoder,z);else{q=K(d._matchFinder,-d._repDistances[0]-1-d._additionalOffset);for(var L=J,I=d._rangeEncoder,p=q,F=z,H=void 0,D=void 0,M=void 0,E=void 0,N=W=void 0,D=1,W=!0,M=7;0<=M;--M)H=F>>M&1,N=D,W&&(E=p>>M&1,N+=1+E<<8,W=E==H),x(I,L.m_Encoders,N,H),D=D<<1|H}d._previousByte=z;d._state=ta(d._state)}else{x(d._rangeEncoder,d._isMatch,h,1);if(4>t){if(x(d._rangeEncoder,d._isRep,d._state,1),0==t?(x(d._rangeEncoder,d._isRepG0,d._state,0),1==w?x(d._rangeEncoder,d._isRep0Long,h,
0):x(d._rangeEncoder,d._isRep0Long,h,1)):(x(d._rangeEncoder,d._isRepG0,d._state,1),1==t?x(d._rangeEncoder,d._isRepG1,d._state,0):(x(d._rangeEncoder,d._isRepG1,d._state,1),x(d._rangeEncoder,d._isRepG2,d._state,t-2))),1==w?d._state=7>d._state?9:11:(bb(d._repMatchLenEncoder,d._rangeEncoder,w-2,y),d._state=7>d._state?8:11),f=d._repDistances[t],0!=t){for(r=t;1<=r;--r)d._repDistances[r]=d._repDistances[r-1];d._repDistances[0]=f}}else{x(d._rangeEncoder,d._isRep,d._state,0);d._state=7>d._state?7:10;bb(d._lenEncoder,
d._rangeEncoder,w-2,y);t-=4;C=cb(t);u=Qa(w);Na(d._posSlotEncoder[u],d._rangeEncoder,C);if(4<=C)if(n=(C>>1)-1,l=(2|C&1)<<n,v=t-l,14>C)for(var fa=d._posEncoders,L=l-C-1,ha=d._rangeEncoder,p=n,F=v,M=D=H=void 0,M=1,D=0;D<p;++D)H=F&1,x(ha,fa,L+M,H),M=M<<1|H,F>>=1;else yb(d._rangeEncoder,v>>4,n-4),zb(d._posAlignEncoder,d._rangeEncoder,v&15),++d._alignPriceCount;f=t;for(r=3;1<=r;--r)d._repDistances[r]=d._repDistances[r-1];d._repDistances[0]=f;++d._matchPriceCount}d._previousByte=K(d._matchFinder,w-1-d._additionalOffset)}d._additionalOffset-=
w;d.nowPos64=da(d.nowPos64,ea(w));if(0==d._additionalOffset){128<=d._matchPriceCount&&Ab(d);16<=d._alignPriceCount&&Bb(d);g[0]=d.nowPos64;var L=m,Q,G=d._rangeEncoder;Q=da(da(ea(G._cacheSize),G._position),nc);L[0]=Q;if(0==Ma(d._matchFinder)){$a(d,R(d.nowPos64));break b}var ia,ba=d.nowPos64;ia=Ca(ba[0]-B[0],ba[1]-B[1]);if(0<=Da(ia,oc)){d._finished=!1;k[0]=!1;break b}}}}}b.inBytesProcessed=b.encoder.processedInSize[0];if(b.encoder.finished[0]){var oa=b.encoder;Cb(oa);oa._rangeEncoder.Stream=null;b.alive=
!1}}else{b:{var p=b.decoder,A,Ra,ga,la;la=R(p.nowPos64)&p.m_PosStateMask;if(0==O(p.m_RangeDecoder,p.m_IsMatchDecoders,(p.state<<4)+la)){var ma=p.m_LiteralDecoder,ka=R(p.nowPos64),N=ma.m_Coders[((ka&ma.m_PosMask)<<ma.m_NumPrevBits)+((p.prevByte&255)>>>8-ma.m_NumPrevBits)];if(7>p.state){var qa=p.m_RangeDecoder,Ha;Ha=1;do Ha=Ha<<1|O(qa,N.m_Decoders,Ha);while(256>Ha);p.prevByte=Ha<<24>>24}else{var Db=p.m_RangeDecoder,P=Eb(p.m_OutWindow,p.rep0),T,Y,na;na=1;do if(Y=P>>7&1,P<<=1,T=O(Db,N.m_Decoders,(1+Y<<
8)+na),na=na<<1|T,Y!=T){for(;256>na;)na=na<<1|O(Db,N.m_Decoders,na);break}while(256>na);p.prevByte=na<<24>>24}var S=p.m_OutWindow,va=p.prevByte;S._buffer[S._pos++]=va;S._pos>=S._windowSize&&Oa(S);p.state=ta(p.state);p.nowPos64=da(p.nowPos64,xb)}else{if(1==O(p.m_RangeDecoder,p.m_IsRepDecoders,p.state))F=0,0==O(p.m_RangeDecoder,p.m_IsRepG0Decoders,p.state)?0==O(p.m_RangeDecoder,p.m_IsRep0LongDecoders,(p.state<<4)+la)&&(p.state=7>p.state?9:11,F=1):(0==O(p.m_RangeDecoder,p.m_IsRepG1Decoders,p.state)?
A=p.rep1:(0==O(p.m_RangeDecoder,p.m_IsRepG2Decoders,p.state)?A=p.rep2:(A=p.rep3,p.rep3=p.rep2),p.rep2=p.rep1),p.rep1=p.rep0,p.rep0=A),0==F&&(F=Fb(p.m_RepLenDecoder,p.m_RangeDecoder,la)+2,p.state=7>p.state?8:11);else if(p.rep3=p.rep2,p.rep2=p.rep1,p.rep1=p.rep0,F=2+Fb(p.m_LenDecoder,p.m_RangeDecoder,la),p.state=7>p.state?7:10,ga=Sa(p.m_PosSlotDecoder[Qa(F)],p.m_RangeDecoder),4<=ga)if(Ra=(ga>>1)-1,p.rep0=(2|ga&1)<<Ra,14>ga){var xa=p.rep0,ya=p.m_PosDecoders,za=p.rep0-ga-1,Aa=p.m_RangeDecoder,ja,Z,Ia,
aa;Ia=1;for(Z=aa=0;Z<Ra;++Z)ja=O(Aa,ya,za+Ia),Ia<<=1,Ia+=ja,aa|=ja<<Z;p.rep0=xa+aa}else{var Ba=p.rep0,ca=p.m_RangeDecoder,ra,U,sa;U=0;for(ra=Ra-4;0!=ra;--ra)ca.Range>>>=1,sa=ca.Code-ca.Range>>>31,ca.Code-=ca.Range&sa-1,U=U<<1|1-sa,0==(ca.Range&-16777216)&&(ca.Code=ca.Code<<8|Ea(ca.Stream),ca.Range<<=8);p.rep0=Ba+(U<<4);var Fa=p.rep0,wa=p.m_PosAlignDecoder,Ka=p.m_RangeDecoder,ua,X,Ja,pa;Ja=1;for(X=pa=0;X<wa.NumBitLevels;++X)ua=O(Ka,wa.Models,Ja),Ja<<=1,Ja+=ua,pa|=ua<<X;p.rep0=Fa+pa;if(0>p.rep0){L=
-1==p.rep0?1:-1;break b}}else p.rep0=ga;if(0<=Da(ea(p.rep0),p.nowPos64)||p.rep0>=p.m_DictionarySizeCheck){L=-1;break b}H=p.m_OutWindow;d=F;D=H._pos-p.rep0-1;for(0>D&&(D+=H._windowSize);0!=d;--d)D>=H._windowSize&&(D=0),H._buffer[H._pos++]=H._buffer[D++],H._pos>=H._windowSize&&Oa(H);p.nowPos64=da(p.nowPos64,ea(F));p.prevByte=Eb(p.m_OutWindow,0)}L=0}if(-1==L)throw Pa(new Ta,"corrupted input");b.inBytesProcessed=Ua;b.outBytesProcessed=b.decoder.nowPos64;if(1==L||0<=Da(b.decoder.outSize,V)&&0<=Da(b.decoder.nowPos64,
b.decoder.outSize))M=b.decoder,Oa(M.m_OutWindow),E=M.m_OutWindow,Oa(E),E._stream=null,M.m_RangeDecoder.Stream=null,b.alive=!1}e=!1;c=b.alive;break a}finally{e&&(b.alive=!1)}c=void 0}return c}catch(La){return a.exception=La,!1}}function pc(a,c,b){a.output=rb(new Gb);try{var e=qb(new Hb,c),d=a.output,g=ea(c.length),m;if(!b){var k=new Ib;k.detailMessage="null mode";throw k;}if(0>Da(g,Ua)){var l=new Ib;l.detailMessage="invalid length "+g;throw l;}a.length_0=g;var h=new qc,z;Jb();h._repDistances=n(J,0,
-1,4,1);h._optimum=n(rc,0,6,4096,0);h._rangeEncoder=(ha(),new sc);h._isMatch=n(y,0,-1,192,1);h._isRep=n(y,0,-1,12,1);h._isRepG0=n(y,0,-1,12,1);h._isRepG1=n(y,0,-1,12,1);h._isRepG2=n(y,0,-1,12,1);h._isRep0Long=n(y,0,-1,192,1);h._posSlotEncoder=n(db,0,8,4,0);h._posEncoders=n(y,0,-1,114,1);h._posAlignEncoder=xa(new ya,4);h._lenEncoder=Kb(new Lb);h._repMatchLenEncoder=Kb(new Lb);h._literalEncoder=new tc;h._matchDistances=n(J,0,-1,548,1);h._posSlotPrices=n(J,0,-1,256,1);h._distancesPrices=n(J,0,-1,512,
1);h._alignPrices=n(J,0,-1,16,1);h.reps=n(J,0,-1,4,1);h.repLens=n(J,0,-1,4,1);h.processedInSize=n(Mb,0,-1,1,3);h.processedOutSize=n(Mb,0,-1,1,3);h.finished=n(uc,0,-1,1,2);h.properties=n(fa,0,-1,5,1);h.tempPrices=n(J,0,-1,128,1);for(z=0;4096>z;++z)h._optimum[z]=new vc;for(z=0;4>z;++z)h._posSlotEncoder[z]=xa(new ya,6);var f;var q=1<<b.dicSize,r;if(1>q||536870912<q)f=!1;else{h._dictionarySize=q;for(r=0;q>1<<r;++r);h._distTableSize=2*r;f=!0}var w,u,v;if(v=f){var t=b.fb;5>t||273<t?v=!1:(h._numFastBytes=
t,v=!0)}if(u=v){var x=b.matchFinder,C;0>x||2<x?u=!1:(C=h._matchFinderType,h._matchFinderType=x,h._matchFinder&&C!=h._matchFinderType&&(h._dictionarySizePrev=-1,h._matchFinder=null),u=!0)}if(w=u){var E=b.lc,K=b.lp,I=b.pb;0>K||4<K||0>E||8<E||0>I||4<I?w=!1:(h._numLiteralPosStateBits=K,h._numLiteralContextBits=E,h._posStateBits=I,h._posStateMask=(1<<h._posStateBits)-1,w=!0)}if(!w){var W=new oa;W.detailMessage="unexpected failure";throw W;}h._writeEndMark=!0;var L;h.properties[0]=9*(5*h._posStateBits+
h._numLiteralPosStateBits)+h._numLiteralContextBits<<24>>24;for(L=0;4>L;++L)h.properties[1+L]=h._dictionarySize>>8*L<<24>>24;var O=h.properties;Fa(d,d.count+5);va(O,0,d.buf,d.count,5);d.count+=5;for(m=0;64>m;m+=8){c=d;var p=R(nb(g,m))&255;Fa(c,c.count+1);c.buf[c.count++]=p<<24>>24}h._needReleaseMFStream=!1;h._inStream=e;h._finished=!1;var F,H;h._matchFinder||(F=(Nb(),new wc),H=4,0==h._matchFinderType&&(H=2),F.HASH_ARRAY=2<H,F.HASH_ARRAY?(F.kNumHashDirectBytes=0,F.kMinMatchCheck=4,F.kFixHashSize=66560):
(F.kNumHashDirectBytes=2,F.kMinMatchCheck=3,F.kFixHashSize=0),h._matchFinder=F);var D=h._literalEncoder,M=h._numLiteralPosStateBits,Q=h._numLiteralContextBits,N,S;if(null==D.m_Coders||D.m_NumPrevBits!=Q||D.m_NumPosBits!=M)for(D.m_NumPosBits=M,D.m_PosMask=(1<<M)-1,D.m_NumPrevBits=Q,S=1<<D.m_NumPrevBits+D.m_NumPosBits,D.m_Coders=n(xc,0,5,S,0),N=0;N<S;++N){var da=D.m_Coders,e=N,ba=new yc;ba.m_Encoders=n(y,0,-1,768,1);da[e]=ba}if(h._dictionarySize!=h._dictionarySizePrev||h._numFastBytesPrev!=h._numFastBytes){var G=
h._matchFinder,P=h._dictionarySize,T=h._numFastBytes,Y,A;if(!(1073741567<P)){G._cutValue=16+(T>>1);D=P+4096;N=T+274;var Z;G._keepSizeBefore=D;G._keepSizeAfter=N;Z=D+N+(~~((P+4096+T+274)/2)+256);if(null==G._bufferBase||G._blockSize!=Z)G._bufferBase=null,G._blockSize=Z,G._bufferBase=n(fa,0,-1,G._blockSize,1);G._pointerToLastSafePosition=G._blockSize-N;G._matchMaxLen=T;Y=P+1;G._cyclicBufferSize!=Y&&(G._son=n(J,0,-1,2*(G._cyclicBufferSize=Y),1));A=65536;G.HASH_ARRAY&&(A=P-1,A|=A>>1,A|=A>>2,A|=A>>4,A|=
A>>8,A>>=1,A|=65535,16777216<A&&(A>>=1),G._hashMask=A,++A,A+=G.kFixHashSize);A!=G._hashSizeSum&&(G._hash=n(J,0,-1,G._hashSizeSum=A,1))}h._dictionarySizePrev=h._dictionarySize;h._numFastBytesPrev=h._numFastBytes}h._rangeEncoder.Stream=d;var ga,la;h._state=0;for(la=h._previousByte=0;4>la;++la)h._repDistances[la]=0;var ma=h._rangeEncoder;ma._position=V;ma.Low=V;ma.Range=-1;ma._cacheSize=1;ma._cache=0;ia(h._isMatch);ia(h._isRep0Long);ia(h._isRep);ia(h._isRepG0);ia(h._isRepG1);ia(h._isRepG2);ia(h._posEncoders);
var aa=h._literalEncoder,U,ja;ja=1<<aa.m_NumPrevBits+aa.m_NumPosBits;for(U=0;U<ja;++U)ia(aa.m_Coders[U].m_Encoders);for(ga=0;4>ga;++ga)B(h._posSlotEncoder[ga].Models);Ob(h._lenEncoder,1<<h._posStateBits);Ob(h._repMatchLenEncoder,1<<h._posStateBits);B(h._posAlignEncoder.Models);h._longestMatchWasFound=!1;h._optimumEndIndex=0;h._optimumCurrentIndex=0;h._additionalOffset=0;Ab(h);Bb(h);h._lenEncoder._tableSize=h._numFastBytes+1-2;Pb(h._lenEncoder,1<<h._posStateBits);h._repMatchLenEncoder._tableSize=h._numFastBytes+
1-2;Pb(h._repMatchLenEncoder,1<<h._posStateBits);h.nowPos64=V;void 0;var X=new Qb;X.encoder=h;X.decoder=null;X.alive=!0;a.chunker=X}catch(ka){throw ka;}return a}function zc(a,c){a.output=rb(new Gb);var b=qb(new Hb,c),e=a.output,d="",g,m,k;m=n(fa,0,-1,5,1);for(g=0;g<m.length;++g){k=Ea(b);if(-1==k)throw Pa(new Ta,"truncated input");m[g]=k<<24>>24}var l=new Ac;l.m_OutWindow=new Bc;l.m_RangeDecoder=new Cc;l.m_IsMatchDecoders=n(y,0,-1,192,1);l.m_IsRepDecoders=n(y,0,-1,12,1);l.m_IsRepG0Decoders=n(y,0,-1,
12,1);l.m_IsRepG1Decoders=n(y,0,-1,12,1);l.m_IsRepG2Decoders=n(y,0,-1,12,1);l.m_IsRep0LongDecoders=n(y,0,-1,192,1);l.m_PosSlotDecoder=n(eb,0,7,4,0);l.m_PosDecoders=n(y,0,-1,114,1);l.m_PosAlignDecoder=za(new Aa,4);l.m_LenDecoder=Rb(new Sb);l.m_RepLenDecoder=Rb(new Sb);l.m_LiteralDecoder=new Dc;for(g=0;4>g;++g)l.m_PosSlotDecoder[g]=za(new Aa,6);var h,z,f;if(5>m.length)g=!1;else{g=m[0]&255;z=g%9;g=~~(g/9);f=g%5;k=~~(g/5);for(h=g=0;4>h;++h)g+=(m[1+h]&255)<<8*h;if(!(m=99999999<g)){if(8<z||4<f||4<k)k=!1;
else{m=l.m_LiteralDecoder;if(null==m.m_Coders||m.m_NumPrevBits!=z||m.m_NumPosBits!=f)for(m.m_NumPosBits=f,m.m_PosMask=(1<<f)-1,m.m_NumPrevBits=z,f=1<<m.m_NumPrevBits+m.m_NumPosBits,m.m_Coders=n(Ec,0,4,f,0),z=0;z<f;++z){h=m.m_Coders;var q=z,r=new Fc;r.m_Decoders=n(y,0,-1,768,1);h[q]=r}k=1<<k;Tb(l.m_LenDecoder,k);Tb(l.m_RepLenDecoder,k);l.m_PosStateMask=k-1;k=!0}m=!k}if(m)g=!1;else if(0>g)g=!1;else{if(l.m_DictionarySize!=g){l.m_DictionarySize=g;l.m_DictionarySizeCheck=Za(l.m_DictionarySize,1);g=l.m_OutWindow;
k=Za(l.m_DictionarySizeCheck,4096);if(null==g._buffer||g._windowSize!=k)g._buffer=n(fa,0,-1,k,1);g._windowSize=k;g._pos=0;g._streamPos=0}g=!0}}if(!g)throw Pa(new Ta,"corrupted input");for(g=0;64>g;g+=8){k=Ea(b);if(-1==k)throw Pa(new Ta,"truncated input");k=k.toString(16);1==k.length&&(k="0"+k);d=k+""+d}/^0+$|^f+$/i.test(d)?a.length_0=Ua:(d=parseInt(d,16),d=4294967295<d?Ua:isNaN(d)?(ba(),Ya):-9223372036854775808>d?(ba(),S):0x7fffffffffffffff<=d?(ba(),ob):0<d?Ca(Math.floor(d),0):Ca(Math.ceil(d),0),
a.length_0=d);d=a.length_0;l.m_RangeDecoder.Stream=b;b=l.m_OutWindow;Oa(b);b._stream=null;b._stream=e;e=l.m_OutWindow;e._streamPos=0;e._pos=0;B(l.m_IsMatchDecoders);B(l.m_IsRep0LongDecoders);B(l.m_IsRepDecoders);B(l.m_IsRepG0Decoders);B(l.m_IsRepG1Decoders);B(l.m_IsRepG2Decoders);B(l.m_PosDecoders);e=l.m_LiteralDecoder;g=1<<e.m_NumPrevBits+e.m_NumPosBits;for(b=0;b<g;++b)B(e.m_Coders[b].m_Decoders);for(e=0;4>e;++e)B(l.m_PosSlotDecoder[e].Models);Ub(l.m_LenDecoder);Ub(l.m_RepLenDecoder);B(l.m_PosAlignDecoder.Models);
e=l.m_RangeDecoder;e.Code=0;e.Range=-1;for(b=0;5>b;++b)e.Code=e.Code<<8|Ea(e.Stream);l.state=0;l.rep0=0;l.rep1=0;l.rep2=0;l.rep3=0;l.outSize=d;l.nowPos64=V;l.prevByte=0;e=new Qb;e.decoder=l;e.encoder=null;e.alive=!0;a.chunker=e;return a}function K(a,c){return a._bufferBase[a._bufferOffset+a._pos+c]}function P(a,c,b,e){var d;a._streamEndWasReached&&a._pos+c+e>a._streamPos&&(e=a._streamPos-(a._pos+c));++b;d=a._bufferOffset+a._pos+c;for(c=0;c<e&&a._bufferBase[d+c]==a._bufferBase[d+c-b];++c);return c}
function Ma(a){return a._streamPos-a._pos}function ub(a){var c,b;if(!a._streamEndWasReached)for(;;){b=-a._bufferOffset+a._blockSize-a._streamPos;if(0==b)break;c=a._stream;var e=a._bufferBase,d=a._bufferOffset+a._streamPos;c.pos>=c.count?c=-1:(b=wa(b,c.count-c.pos),va(c.buf,c.pos,e,d,b),c.pos+=b,c=b);if(-1==c){a._posLimit=a._streamPos;c=a._bufferOffset+a._posLimit;c>a._pointerToLastSafePosition&&(a._posLimit=a._pointerToLastSafePosition-a._bufferOffset);a._streamEndWasReached=!0;break}a._streamPos+=
c;a._streamPos>=a._pos+a._keepSizeAfter&&(a._posLimit=a._streamPos-a._keepSizeAfter)}}function vb(a,c){a._bufferOffset+=c;a._posLimit-=c;a._pos-=c;a._streamPos-=c}function Nb(){Nb=E;var a,c,b;T=n(J,0,-1,256,1);for(a=0;256>a;++a){b=a;for(c=0;8>c;++c)b=0!=(b&1)?b>>>1^-306674912:b>>>1;T[a]=b}}function Ka(a){var c;++a._cyclicBufferPos>=a._cyclicBufferSize&&(a._cyclicBufferPos=0);++a._pos;if(a._pos>a._posLimit){c=a._bufferOffset+a._pos;if(c>a._pointerToLastSafePosition){var b,e;e=a._bufferOffset+a._pos-
a._keepSizeBefore;0<e&&--e;b=a._bufferOffset+a._streamPos-e;for(c=0;c<b;++c)a._bufferBase[c]=a._bufferBase[e+c];a._bufferOffset-=e}ub(a)}1073741823==a._pos&&(c=a._pos-a._cyclicBufferSize,Vb(a._son,2*a._cyclicBufferSize,c),Vb(a._hash,a._hashSizeSum,c),vb(a,c))}function Vb(a,c,b){var e,d;for(e=0;e<c;++e)d=a[e],d=d<=b?0:d-b,a[e]=d}function Wb(a,c){var b,e,d,g,m,k,l,h,z,f,n,r;do{if(a._pos+a._matchMaxLen<=a._streamPos)h=a._matchMaxLen;else if(h=a._streamPos-a._pos,h<a.kMinMatchCheck){Ka(a);continue}z=
a._pos>a._cyclicBufferSize?a._pos-a._cyclicBufferSize:0;e=a._bufferOffset+a._pos;a.HASH_ARRAY?(d=T[a._bufferBase[e]&255]^a._bufferBase[e+1]&255,b=d&1023,a._hash[b]=a._pos,d^=(a._bufferBase[e+2]&255)<<8,b=d&65535,a._hash[1024+b]=a._pos,b=(d^T[a._bufferBase[e+3]&255]<<5)&a._hashMask):b=a._bufferBase[e]&255^(a._bufferBase[e+1]&255)<<8;d=a._hash[a.kFixHashSize+b];a._hash[a.kFixHashSize+b]=a._pos;n=(a._cyclicBufferPos<<1)+1;r=a._cyclicBufferPos<<1;k=l=a.kNumHashDirectBytes;for(b=a._cutValue;;){if(d<=z||
0==b--){a._son[n]=a._son[r]=0;break}g=a._pos-d;g=(g<=a._cyclicBufferPos?a._cyclicBufferPos-g:a._cyclicBufferPos-g+a._cyclicBufferSize)<<1;f=a._bufferOffset+d;m=k<l?k:l;if(a._bufferBase[f+m]==a._bufferBase[e+m]){for(;++m!=h&&a._bufferBase[f+m]==a._bufferBase[e+m];);if(m==h){a._son[r]=a._son[g];a._son[n]=a._son[g+1];break}}(a._bufferBase[f+m]&255)<(a._bufferBase[e+m]&255)?(a._son[r]=d,r=g+1,d=a._son[r],l=m):(a._son[n]=d,n=g,d=a._son[n],k=m)}Ka(a)}while(0!=--c)}function Oa(a){var c;c=a._pos-a._streamPos;
if(0!=c){var b=a._stream,e=a._buffer,d=a._streamPos;Fa(b,b.count+c);va(e,d,b.buf,b.count,c);b.count+=c;a._pos>=a._windowSize&&(a._pos=0);a._streamPos=a._pos}}function Eb(a,c){var b;b=a._pos-c-1;0>b&&(b+=a._windowSize);return a._buffer[b]}function Qa(a){a-=2;return 4>a?a:3}function ta(a){return 4>a?0:10>a?a-3:a-6}function Tb(a,c){for(;a.m_NumPosStates<c;++a.m_NumPosStates)a.m_LowCoder[a.m_NumPosStates]=za(new Aa,3),a.m_MidCoder[a.m_NumPosStates]=za(new Aa,3)}function Fb(a,c,b){var e;if(0==O(c,a.m_Choice,
0))return Sa(a.m_LowCoder[b],c);e=8;return e=0==O(c,a.m_Choice,1)?e+Sa(a.m_MidCoder[b],c):e+(8+Sa(a.m_HighCoder,c))}function Rb(a){a.m_Choice=n(y,0,-1,2,1);a.m_LowCoder=n(eb,0,7,16,0);a.m_MidCoder=n(eb,0,7,16,0);a.m_HighCoder=za(new Aa,8);return a}function Ub(a){var c;B(a.m_Choice);for(c=0;c<a.m_NumPosStates;++c)B(a.m_LowCoder[c].Models),B(a.m_MidCoder[c].Models);B(a.m_HighCoder.Models)}function Jb(){Jb=E;var a,c,b,e;Q=n(fa,0,-1,2048,1);a=2;Q[0]=0;Q[1]=1;for(e=2;22>e;++e)for(b=1<<(e>>1)-1,c=0;c<b;++c,
++a)Q[a]=e<<24>>24}function Xb(a,c){var b,e,d,g;a._optimumEndIndex=c;d=a._optimum[c].PosPrev;e=a._optimum[c].BackPrev;do a._optimum[c].Prev1IsChar&&(b=a._optimum[d],b.BackPrev=-1,b.Prev1IsChar=0,a._optimum[d].PosPrev=d-1,a._optimum[c].Prev2&&(a._optimum[d-1].Prev1IsChar=0,a._optimum[d-1].PosPrev=a._optimum[c].PosPrev2,a._optimum[d-1].BackPrev=a._optimum[c].BackPrev2)),g=d,b=e,e=a._optimum[g].BackPrev,d=a._optimum[g].PosPrev,a._optimum[g].BackPrev=b,a._optimum[g].PosPrev=c,c=g;while(0<c);a.backRes=
a._optimum[0].BackPrev;a._optimumCurrentIndex=a._optimum[0].PosPrev;return a._optimumCurrentIndex}function Bb(a){var c;for(c=0;16>c;++c){for(var b=a._alignPrices,e=c,d=a._posAlignEncoder,g=c,m=void 0,k=void 0,l=void 0,h=void 0,h=0,l=1,k=d.NumBitLevels;0!=k;--k)m=g&1,g>>>=1,h+=ja(d.Models[l],m),l=l<<1|m;b[e]=h}a._alignPriceCount=0}function Ab(a){var c,b,e,d,g,m;for(b=4;128>b;++b){d=cb(b);e=(d>>1)-1;c=(2|d&1)<<e;g=a.tempPrices;m=b;var k=a._posEncoders;d=c-d-1;c=b-c;for(var l=void 0,h=void 0,z=void 0,
f=void 0,f=0,z=1,h=e;0!=h;--h)l=c&1,c>>>=1,f+=(ha(),v[((k[d+z]-l^-l)&2047)>>>2]),z=z<<1|l;g[m]=f}for(e=0;4>e;++e){b=a._posSlotEncoder[e];g=e<<6;for(d=0;d<a._distTableSize;++d)a._posSlotPrices[g+d]=ua(b,d);for(d=14;d<a._distTableSize;++d)a._posSlotPrices[g+d]+=(d>>1)-1-4<<6;m=128*e;for(b=0;4>b;++b)a._distancesPrices[m+b]=a._posSlotPrices[g+b];for(;128>b;++b)a._distancesPrices[m+b]=a._posSlotPrices[g+cb(b)]+a.tempPrices[b]}a._matchPriceCount=0}function $a(a,c){Cb(a);var b=c&a._posStateMask;a._writeEndMark&&
(x(a._rangeEncoder,a._isMatch,(a._state<<4)+b,1),x(a._rangeEncoder,a._isRep,a._state,0),a._state=7>a._state?7:10,bb(a._lenEncoder,a._rangeEncoder,0,b),b=Qa(2),Na(a._posSlotEncoder[b],a._rangeEncoder,63),yb(a._rangeEncoder,67108863,26),zb(a._posAlignEncoder,a._rangeEncoder,15));var b=a._rangeEncoder,e;for(e=0;5>e;++e)fb(b)}function mc(a,c){var b,e,d,g,m,k,l,h,f,n,q,r,w,u,x,t,y,C,B,E,I,J,L;if(a._optimumEndIndex!=a._optimumCurrentIndex)return h=a._optimum[a._optimumCurrentIndex].PosPrev-a._optimumCurrentIndex,
a.backRes=a._optimum[a._optimumCurrentIndex].BackPrev,a._optimumCurrentIndex=a._optimum[a._optimumCurrentIndex].PosPrev,h;a._optimumCurrentIndex=a._optimumEndIndex=0;a._longestMatchWasFound?(b=a._longestMatchLength,a._longestMatchWasFound=!1):b=ab(a);h=a._numDistancePairs;r=Ma(a._matchFinder)+1;if(2>r)return a.backRes=-1,1;for(k=l=0;4>k;++k)a.reps[k]=a._repDistances[k],a.repLens[k]=P(a._matchFinder,-1,a.reps[k],273),a.repLens[k]>a.repLens[l]&&(l=k);if(a.repLens[l]>=a._numFastBytes)return a.backRes=
l,h=a.repLens[l],B=h-1,0<B&&(Wb(a._matchFinder,B),a._additionalOffset+=B),h;if(b>=a._numFastBytes)return a.backRes=a._matchDistances[h-1]+4,h=b-1,0<h&&(Wb(a._matchFinder,h),a._additionalOffset+=h),b;m=K(a._matchFinder,-1);q=K(a._matchFinder,-a._repDistances[0]-1-1);if(2>b&&m!=q&&2>a.repLens[l])return a.backRes=-1,1;a._optimum[0].State=a._state;t=c&a._posStateMask;a._optimum[1].Price=(ha(),v[a._isMatch[(a._state<<4)+t]>>>2])+X(Ga(a._literalEncoder,c,a._previousByte),7<=a._state,q,m);g=a._optimum[1];
g.BackPrev=-1;g.Prev1IsChar=0;g=v[2048-a._isMatch[(a._state<<4)+t]>>>2];u=g+v[2048-a._isRep[a._state]>>>2];q==m&&(k=u,d=a._state,w=t,d=(ha(),v[a._isRepG0[d]>>>2])+v[a._isRep0Long[(d<<4)+w]>>>2],w=k+d,w<a._optimum[1].Price&&(a._optimum[1].Price=w,k=a._optimum[1],k.BackPrev=0,k.Prev1IsChar=0));l=b>=a.repLens[l]?b:a.repLens[l];if(2>l)return a.backRes=a._optimum[1].BackPrev,1;a._optimum[1].PosPrev=0;a._optimum[0].Backs0=a.reps[0];a._optimum[0].Backs1=a.reps[1];a._optimum[0].Backs2=a.reps[2];a._optimum[0].Backs3=
a.reps[3];k=l;do a._optimum[k--].Price=268435455;while(2<=k);for(k=0;4>k;++k)if(w=a.repLens[k],!(2>w)){d=u+Y(a,k,a._state,t);do e=d+a._repMatchLenEncoder._prices[272*t+(w-2)],f=a._optimum[w],e<f.Price&&(f.Price=e,f.PosPrev=0,f.BackPrev=k,f.Prev1IsChar=0);while(2<=--w)}g+=v[a._isRep[a._state]>>>2];k=2<=a.repLens[0]?a.repLens[0]+1:2;if(k<=b){for(u=0;k>a._matchDistances[u];)u+=2;for(;b=a._matchDistances[u+1],e=g+Yb(a,b,k,t),f=a._optimum[k],e<f.Price&&(f.Price=e,f.PosPrev=0,f.BackPrev=b+4,f.Prev1IsChar=
0),k!=a._matchDistances[u]||(u+=2,u!=h);++k);}for(b=0;;){++b;if(b==l)return Xb(a,b);d=ab(a);h=a._numDistancePairs;if(d>=a._numFastBytes)return a._longestMatchLength=d,a._longestMatchWasFound=!0,Xb(a,b);++c;g=a._optimum[b].PosPrev;a._optimum[b].Prev1IsChar?(--g,a._optimum[b].Prev2?(k=a._optimum[a._optimum[b].PosPrev2].State,k=4>a._optimum[b].BackPrev2?7>k?8:11:7>k?7:10):k=a._optimum[g].State,k=ta(k)):k=a._optimum[g].State;g==b-1?k=0==a._optimum[b].BackPrev?7>k?9:11:ta(k):(a._optimum[b].Prev1IsChar&&
a._optimum[b].Prev2?(g=a._optimum[b].PosPrev2,t=a._optimum[b].BackPrev2,k=7>k?8:11):(t=a._optimum[b].BackPrev,k=4>t?7>k?8:11:7>k?7:10),g=a._optimum[g],4>t?0==t?(a.reps[0]=g.Backs0,a.reps[1]=g.Backs1,a.reps[2]=g.Backs2,a.reps[3]=g.Backs3):1==t?(a.reps[0]=g.Backs1,a.reps[1]=g.Backs0,a.reps[2]=g.Backs2,a.reps[3]=g.Backs3):2==t?(a.reps[0]=g.Backs2,a.reps[1]=g.Backs0,a.reps[2]=g.Backs1,a.reps[3]=g.Backs3):(a.reps[0]=g.Backs3,a.reps[1]=g.Backs0,a.reps[2]=g.Backs1,a.reps[3]=g.Backs2):(a.reps[0]=t-4,a.reps[1]=
g.Backs0,a.reps[2]=g.Backs1,a.reps[3]=g.Backs2));a._optimum[b].State=k;a._optimum[b].Backs0=a.reps[0];a._optimum[b].Backs1=a.reps[1];a._optimum[b].Backs2=a.reps[2];a._optimum[b].Backs3=a.reps[3];g=a._optimum[b].Price;m=K(a._matchFinder,-1);q=K(a._matchFinder,-a.reps[0]-1-1);t=c&a._posStateMask;e=g+v[a._isMatch[(k<<4)+t]>>>2]+X(Ga(a._literalEncoder,c,K(a._matchFinder,-2)),7<=k,q,m);r=a._optimum[b+1];f=!1;e<r.Price&&(r.Price=e,r.PosPrev=b,r.BackPrev=-1,r.Prev1IsChar=0,f=!0);g+=v[2048-a._isMatch[(k<<
4)+t]>>>2];u=g+v[2048-a._isRep[k]>>>2];q!=m||r.PosPrev<b&&0==r.BackPrev||(w=u+(v[a._isRepG0[k]>>>2]+v[a._isRep0Long[(k<<4)+t]>>>2]),w<=r.Price&&(r.Price=w,r.PosPrev=b,r.BackPrev=0,r.Prev1IsChar=0,f=!0));w=Ma(a._matchFinder)+1;r=w=4095-b<w?4095-b:w;if(!(2>r)){r>a._numFastBytes&&(r=a._numFastBytes);if(!f&&q!=m&&(f=wa(w-1,a._numFastBytes),f=P(a._matchFinder,0,a.reps[0],f),2<=f)){C=ta(k);n=c+1&a._posStateMask;e=e+v[2048-a._isMatch[(C<<4)+n]>>>2]+v[2048-a._isRep[C]>>>2];for(x=b+1+f;l<x;)a._optimum[++l].Price=
268435455;e+=(B=a._repMatchLenEncoder._prices[272*n+(f-2)],B+Y(a,0,C,n));f=a._optimum[x];e<f.Price&&(f.Price=e,f.PosPrev=b+1,f.BackPrev=0,f.Prev1IsChar=1,f.Prev2=0)}q=2;for(y=0;4>y;++y)if(m=P(a._matchFinder,-1,a.reps[y],r),!(2>m)){n=m;do{for(;l<b+m;)a._optimum[++l].Price=268435455;e=u+(E=a._repMatchLenEncoder._prices[272*t+(m-2)],E+Y(a,y,k,t));f=a._optimum[b+m];e<f.Price&&(f.Price=e,f.PosPrev=b,f.BackPrev=y,f.Prev1IsChar=0)}while(2<=--m);m=n;0==y&&(q=m+1);if(m<w&&(f=wa(w-1-m,a._numFastBytes),f=P(a._matchFinder,
m,a.reps[y],f),2<=f)){C=7>k?8:11;n=c+m&a._posStateMask;e=u+(I=a._repMatchLenEncoder._prices[272*t+(m-2)],I+Y(a,y,k,t))+v[a._isMatch[(C<<4)+n]>>>2]+X(Ga(a._literalEncoder,c+m,K(a._matchFinder,m-1-1)),!0,K(a._matchFinder,m-1-(a.reps[y]+1)),K(a._matchFinder,m-1));C=ta(C);n=c+m+1&a._posStateMask;e+=v[2048-a._isMatch[(C<<4)+n]>>>2];e+=v[2048-a._isRep[C]>>>2];for(x=m+1+f;l<b+x;)a._optimum[++l].Price=268435455;e+=(J=a._repMatchLenEncoder._prices[272*n+(f-2)],J+Y(a,0,C,n));f=a._optimum[b+x];e<f.Price&&(f.Price=
e,f.PosPrev=b+m+1,f.BackPrev=0,f.Prev1IsChar=1,f.Prev2=1,f.PosPrev2=b,f.BackPrev2=y)}}if(d>r){d=r;for(h=0;d>a._matchDistances[h];h+=2);a._matchDistances[h]=d;h+=2}if(d>=q){for(g+=v[a._isRep[k]>>>2];l<b+d;)a._optimum[++l].Price=268435455;for(u=0;q>a._matchDistances[u];)u+=2;for(m=q;;++m)if(d=a._matchDistances[u+1],e=g+Yb(a,d,m,t),f=a._optimum[b+m],e<f.Price&&(f.Price=e,f.PosPrev=b,f.BackPrev=d+4,f.Prev1IsChar=0),m==a._matchDistances[u]){if(m<w&&(f=wa(w-1-m,a._numFastBytes),f=P(a._matchFinder,m,d,f),
2<=f)){C=7>k?7:10;n=c+m&a._posStateMask;e=e+v[a._isMatch[(C<<4)+n]>>>2]+X(Ga(a._literalEncoder,c+m,K(a._matchFinder,m-1-1)),!0,K(a._matchFinder,m-(d+1)-1),K(a._matchFinder,m-1));C=ta(C);n=c+m+1&a._posStateMask;e+=v[2048-a._isMatch[(C<<4)+n]>>>2];e+=v[2048-a._isRep[C]>>>2];for(x=m+1+f;l<b+x;)a._optimum[++l].Price=268435455;e+=(L=a._repMatchLenEncoder._prices[272*n+(f-2)],L+Y(a,0,C,n));f=a._optimum[b+x];e<f.Price&&(f.Price=e,f.PosPrev=b+m+1,f.BackPrev=0,f.Prev1IsChar=1,f.Prev2=1,f.PosPrev2=b,f.BackPrev2=
d+4)}u+=2;if(u==h)break}}}}}function Yb(a,c,b,e){var d;d=Qa(b);if(128>c)c=a._distancesPrices[128*d+c];else{var g=a._posSlotPrices,f;f=131072>c?Q[c>>6]+12:134217728>c?Q[c>>16]+32:Q[c>>26]+52;c=g[(d<<6)+f]+a._alignPrices[c&15]}return c+a._lenEncoder._prices[272*e+(b-2)]}function Y(a,c,b,e){var d;0==c?(d=(ha(),v[a._isRepG0[b]>>>2]),d+=v[2048-a._isRep0Long[(b<<4)+e]>>>2]):(d=(ha(),v[2048-a._isRepG0[b]>>>2]),1==c?d+=v[a._isRepG1[b]>>>2]:(d+=v[2048-a._isRepG1[b]>>>2],d+=ja(a._isRepG2[b],c-2)));return d}
function ab(a){var c;c=0;var b;a:{b=a._matchFinder;var e=a._matchDistances,d,g,f,k,l,h,n,q,v,r,w,u,y,t,x;if(b._pos+b._matchMaxLen<=b._streamPos)v=b._matchMaxLen;else if(v=b._streamPos-b._pos,v<b.kMinMatchCheck){Ka(b);b=0;break a}u=0;r=b._pos>b._cyclicBufferSize?b._pos-b._cyclicBufferSize:0;g=b._bufferOffset+b._pos;w=1;h=d=0;b.HASH_ARRAY?(f=T[b._bufferBase[g]&255]^b._bufferBase[g+1]&255,d=f&1023,f^=(b._bufferBase[g+2]&255)<<8,h=f&65535,n=(f^T[b._bufferBase[g+3]&255]<<5)&b._hashMask):n=b._bufferBase[g]&
255^(b._bufferBase[g+1]&255)<<8;f=b._hash[b.kFixHashSize+n];b.HASH_ARRAY&&(k=b._hash[d],l=b._hash[1024+h],b._hash[d]=b._pos,b._hash[1024+h]=b._pos,k>r&&b._bufferBase[b._bufferOffset+k]==b._bufferBase[g]&&(e[u++]=w=2,e[u++]=b._pos-k-1),l>r&&b._bufferBase[b._bufferOffset+l]==b._bufferBase[g]&&(l==k&&(u-=2),e[u++]=w=3,e[u++]=b._pos-l-1,k=l),0!=u&&k==f&&(u-=2,w=1));b._hash[b.kFixHashSize+n]=b._pos;t=(b._cyclicBufferPos<<1)+1;x=b._cyclicBufferPos<<1;n=q=b.kNumHashDirectBytes;0!=b.kNumHashDirectBytes&&
f>r&&b._bufferBase[b._bufferOffset+f+b.kNumHashDirectBytes]!=b._bufferBase[g+b.kNumHashDirectBytes]&&(e[u++]=w=b.kNumHashDirectBytes,e[u++]=b._pos-f-1);for(d=b._cutValue;;){if(f<=r||0==d--){b._son[t]=b._son[x]=0;break}k=b._pos-f;h=(k<=b._cyclicBufferPos?b._cyclicBufferPos-k:b._cyclicBufferPos-k+b._cyclicBufferSize)<<1;y=b._bufferOffset+f;l=n<q?n:q;if(b._bufferBase[y+l]==b._bufferBase[g+l]){for(;++l!=v&&b._bufferBase[y+l]==b._bufferBase[g+l];);if(w<l&&(e[u++]=w=l,e[u++]=k-1,l==v)){b._son[x]=b._son[h];
b._son[t]=b._son[h+1];break}}(b._bufferBase[y+l]&255)<(b._bufferBase[g+l]&255)?(b._son[x]=f,x=h+1,f=b._son[x],q=l):(b._son[t]=f,t=h,f=b._son[t],n=l)}Ka(b);b=u}a._numDistancePairs=b;0<a._numDistancePairs&&(c=a._matchDistances[a._numDistancePairs-2],c==a._numFastBytes&&(c+=P(a._matchFinder,c-1,a._matchDistances[a._numDistancePairs-1],273-c)));++a._additionalOffset;return c}function Cb(a){a._matchFinder&&a._needReleaseMFStream&&(a._matchFinder._stream=null,a._needReleaseMFStream=!1)}function cb(a){return 2048>
a?Q[a]:2097152>a?Q[a>>10]+20:Q[a>>20]+40}function Ob(a,c){var b;ia(a._choice);for(b=0;b<c;++b)B(a._lowCoder[b].Models),B(a._midCoder[b].Models);B(a._highCoder.Models)}function Zb(a,c,b,e,d){var g,f,k,l;g=(ha(),v[a._choice[0]>>>2]);f=v[2048-a._choice[0]>>>2];k=f+v[a._choice[1]>>>2];f+=v[2048-a._choice[1]>>>2];for(l=0;8>l;++l){if(l>=b)return;e[d+l]=g+ua(a._lowCoder[c],l)}for(;16>l;++l){if(l>=b)return;e[d+l]=k+ua(a._midCoder[c],l-8)}for(;l<b;++l)e[d+l]=f+ua(a._highCoder,l-8-8)}function bb(a,c,b,e){8>
b?(x(c,a._choice,0,0),Na(a._lowCoder[e],c,b)):(b-=8,x(c,a._choice,0,1),8>b?(x(c,a._choice,1,0),Na(a._midCoder[e],c,b)):(x(c,a._choice,1,1),Na(a._highCoder,c,b-8)));0==--a._counters[e]&&(Zb(a,e,a._tableSize,a._prices,272*e),a._counters[e]=a._tableSize)}function Kb(a){var c;a._choice=n(y,0,-1,2,1);a._lowCoder=n(db,0,8,16,0);a._midCoder=n(db,0,8,16,0);a._highCoder=xa(new ya,8);for(c=0;16>c;++c)a._lowCoder[c]=xa(new ya,3),a._midCoder[c]=xa(new ya,3);a._prices=n(J,0,-1,4352,1);a._counters=n(J,0,-1,16,
1);return a}function Pb(a,c){var b;for(b=0;b<c;++b)Zb(a,b,a._tableSize,a._prices,272*b),a._counters[b]=a._tableSize}function Ga(a,c,b){return a.m_Coders[((c&a.m_PosMask)<<a.m_NumPrevBits)+((b&255)>>>8-a.m_NumPrevBits)]}function wb(a,c,b){var e,d,g;d=1;for(g=7;0<=g;--g)e=b>>g&1,x(c,a.m_Encoders,d,e),d=d<<1|e}function X(a,c,b,e){var d,g,f,k;k=0;d=1;g=7;if(c)for(;0<=g;--g)if(f=b>>g&1,c=e>>g&1,k+=ja(a.m_Encoders[(1+f<<8)+d],c),d=d<<1|c,f!=c){--g;break}for(;0<=g;--g)c=e>>g&1,k+=ja(a.m_Encoders[d],c),d=
d<<1|c;return k}function za(a,c){a.NumBitLevels=c;a.Models=n(y,0,-1,1<<c,1);return a}function Sa(a,c){var b,e;e=1;for(b=a.NumBitLevels;0!=b;--b)e=(e<<1)+O(c,a.Models,e);return e-(1<<a.NumBitLevels)}function xa(a,c){a.NumBitLevels=c;a.Models=n(y,0,-1,1<<c,1);return a}function Na(a,c,b){var e,d,g;g=1;for(d=a.NumBitLevels;0!=d;)--d,e=b>>>d&1,x(c,a.Models,g,e),g=g<<1|e}function ua(a,c){var b,e,d,g;g=0;d=1;for(e=a.NumBitLevels;0!=e;)--e,b=c>>>e&1,g+=ja(a.Models[d],b),d=(d<<1)+b;return g}function zb(a,
c,b){var e,d,g;g=1;for(d=0;d<a.NumBitLevels;++d)e=b&1,x(c,a.Models,g,e),g=g<<1|e,b>>=1}function O(a,c,b){var e,d;d=c[b];e=(a.Range>>>11)*d;if((a.Code^-2147483648)<(e^-2147483648))return a.Range=e,c[b]=d+(2048-d>>>5)<<16>>16,0==(a.Range&-16777216)&&(a.Code=a.Code<<8|Ea(a.Stream),a.Range<<=8),0;a.Range-=e;a.Code-=e;c[b]=d-(d>>>5)<<16>>16;0==(a.Range&-16777216)&&(a.Code=a.Code<<8|Ea(a.Stream),a.Range<<=8);return 1}function B(a){var c;for(c=0;c<a.length;++c)a[c]=1024}function ha(){ha=E;var a,c,b;v=n(J,
0,-1,512,1);for(c=8;0<=c;--c)for(b=1<<9-c-1,a=1<<9-c;b<a;++b)v[b]=(c<<6)+(a-b<<6>>>9-c-1)}function x(a,c,b,e){var d,g;g=c[b];d=(a.Range>>>11)*g;0==e?(a.Range=d,c[b]=g+(2048-g>>>5)<<16>>16):(a.Low=da(a.Low,kb(ea(d),Gc)),a.Range-=d,c[b]=g-(g>>>5)<<16>>16);0==(a.Range&-16777216)&&(a.Range<<=8,fb(a))}function yb(a,c,b){for(--b;0<=b;--b)a.Range>>>=1,1==(c>>>b&1)&&(a.Low=da(a.Low,ea(a.Range))),0==(a.Range&-16777216)&&(a.Range<<=8,fb(a))}function fb(a){var c,b;c=a.Low;var e;e=32;b=nb(c,e);0>c[1]&&(b=da(b,
Xa((ba(),pb),63-e)));c=R(b);if(0!=c||0>Da(a.Low,Hc)){a._position=da(a._position,ea(a._cacheSize));b=a._cache;do e=a.Stream,b+=c,Fa(e,e.count+1),e.buf[e.count++]=b<<24>>24,b=255;while(0!=--a._cacheSize);a._cache=R(a.Low)>>>24}++a._cacheSize;a.Low=Xa(kb(a.Low,Ic),8)}function ja(a,c){ha();return v[((a-c^-c)&2047)>>>2]}function ia(a){ha();var c;for(c=0;c<a.length;++c)a[c]=1024}function ka(a){var c;for(c=a.length-1;0<=c;--c)0>a[c]&&(a[c]=256+a[c]);return a}function Jc(a){var c=new Kc,b;c.data=(b=[],b.explicitLength=
0,b);var e,d,g;for(b=0;b<a.length;++b)if(e=a[b]&255,0==(e&128)){if(0==e)return ka(a);d=c.data;e=String.fromCharCode(e&65535);d[d.explicitLength++]=e}else if(192==(e&224)){if(b+1>=a.length)return ka(a);d=a[++b]&255;if(128!=(d&192))return ka(a);var f=c.data;e=String.fromCharCode((e&31)<<6&65535|d&63);f[f.explicitLength++]=e}else if(224==(e&240)){if(b+2>=a.length)return ka(a);d=a[++b]&255;if(128!=(d&192))return ka(a);g=a[++b]&255;if(128!=(g&192))return ka(a);f=c.data;e=String.fromCharCode(((e&15)<<12|
(d&63)<<6|g&63)&65535);f[f.explicitLength++]=e}else return ka(a);a=c.data;var k,c=(k=a.join(""),a.length=a.explicitLength=0,k);return a[a.explicitLength++]=c}function Lc(a){var c,b,e,d,f;c=a.length;f=n(Mc,0,-1,c,1);for(e=b=0;e<c;++e)f[b++]=a.charCodeAt(e);for(d=e=0;d<a.length;++d)c=f[d],1<=c&&127>=c?++e:e=0==c||128<=c&&2047>=c?e+2:e+3;b=n(fa,0,-1,e,1);for(d=e=0;d<a.length;++d)c=f[d],1<=c&&127>=c?b[e++]=c<<24>>24:(0==c||128<=c&&2047>=c?b[e++]=(192|c>>6&31)<<24>>24:(b[e++]=(224|c>>12&15)<<24>>24,b[e++]=
(128|c>>6&63)<<24>>24),b[e++]=(128|c&63)<<24>>24);return b}function $b(a){return a}function Z(a){return a[1]+a[0]}function E(){}var pa="function"==typeof setImmediate?setImmediate:setTimeout,La=function(){return{typeName:this.typeId$+""}},f,hc=[0,-9223372036854775808],Ua=[4294967295,-4294967296],V=[0,0],xb=[1,0],nc=[4,0],oc=[4096,0],Ic=[16777215,0],Hc=[4278190080,0],Gc=[4294967295,0],gc=[4294967295,0x7fffffff00000000],bc=q(1,{});f.typeMarker$=E;var Nc=q(3),Oc=q(4,new Nc),oa=q(5,new Oc),dc=q(0);f.getClass$=
function(){return this.arrayClass$};f.length=0;f.queryId$=0;var Ba,ra,ib=[{},{},{1:1},{2:1},{2:1},{2:1},{2:1},{2:1,10:1},{2:1},{2:1},{2:1},{2:1},{2:1},{2:1,11:1},{2:1},{2:1},{2:1},{4:1},{5:1},{6:1},{7:1},{8:1},{9:1}],Wa,ob,S,pb,Ya,Pc=q(0),Hb=q(0,new Pc);f.count=0;f.pos=0;var Qc=q(0),Gb=q(0,new Qc);f.count=0;var Ta=q(7),U=q(9,new oa),ic=q(0),ec=q(12,new oa),Ib=q(13,new oa),lc=q(14,new oa),kc=q(15,new oa),jc=q(16,new oa),Kc=q(0),Rc=q(0),Sc=q(0,new Rc),Tc=q(0);f.length_0=V;var Uc=q(0,new Tc),Vc=q(0);
f._blockSize=0;f._bufferOffset=0;f._keepSizeAfter=0;f._keepSizeBefore=0;f._pointerToLastSafePosition=0;f._pos=0;f._posLimit=0;f._streamPos=0;var wc=q(0,new Vc);f.HASH_ARRAY=!0;f._cutValue=255;f._cyclicBufferPos=0;f._cyclicBufferSize=0;f._hashSizeSum=0;f.kFixHashSize=66560;f.kMinMatchCheck=4;f.kNumHashDirectBytes=0;var T,Bc=q(0);f._pos=0;f._streamPos=0;f._windowSize=0;var Qb=q(0),Ac=q(0);f.m_DictionarySize=-1;f.m_DictionarySizeCheck=-1;f.m_PosStateMask=0;f.nowPos64=V;f.outSize=V;f.prevByte=0;f.rep0=
0;f.rep1=0;f.rep2=0;f.rep3=0;f.state=0;var Sb=q(0);f.m_NumPosStates=0;var Dc=q(0);f.m_NumPosBits=0;f.m_NumPrevBits=0;f.m_PosMask=0;var Fc=q(17),qc=q(0);f._additionalOffset=0;f._alignPriceCount=0;f._dictionarySize=4194304;f._dictionarySizePrev=-1;f._distTableSize=44;f._longestMatchLength=0;f._matchFinderType=1;f._matchPriceCount=0;f._numDistancePairs=0;f._numFastBytes=32;f._numFastBytesPrev=-1;f._numLiteralContextBits=3;f._numLiteralPosStateBits=0;f._optimumCurrentIndex=0;f._optimumEndIndex=0;f._posStateBits=
2;f._posStateMask=3;f._previousByte=0;f._state=0;f.backRes=0;f.nowPos64=V;var Q,Wc=q(0),Lb=q(0,new Wc);f._tableSize=0;var tc=q(0);f.m_NumPosBits=0;f.m_NumPrevBits=0;f.m_PosMask=0;var yc=q(18),vc=q(19);f.BackPrev=0;f.BackPrev2=0;f.Backs0=0;f.Backs1=0;f.Backs2=0;f.Backs3=0;f.PosPrev=0;f.PosPrev2=0;f.Price=0;f.State=0;var Aa=q(20);f.NumBitLevels=0;var ya=q(21);f.NumBitLevels=0;var Cc=q(0);f.Code=0;f.Range=0;var sc=q(0);f.Low=V;f.Range=0;f._cache=0;f._cacheSize=0;f._position=V;var v,ac=q(0),fa=I("","[B"),
y=I("","[S"),Mc=I("","[C"),J=I("","[I"),rc=I("[Ll.","o"),db=I("[Ll","be"),Mb=I("","[J"),uc=I("","[Z"),xc=I("[Ll.","e"),eb=I("[Ll","bd"),Ec=I("[Ll.","d"),fc=I("","[[D"),Xc=function(){var a=[{dicSize:16,fb:64,matchFinder:0,lc:3,lp:0,pb:2},{dicSize:20,fb:64,matchFinder:0,lc:3,lp:0,pb:2},{dicSize:19,fb:64,matchFinder:1,lc:3,lp:0,pb:2},{dicSize:20,fb:64,matchFinder:1,lc:3,lp:0,pb:2},{dicSize:21,fb:128,matchFinder:1,lc:3,lp:0,pb:2},{dicSize:22,fb:128,matchFinder:1,lc:3,lp:0,pb:2},{dicSize:23,fb:128,matchFinder:1,
lc:3,lp:0,pb:2},{dicSize:24,fb:255,matchFinder:1,lc:3,lp:0,pb:2},{dicSize:25,fb:255,matchFinder:1,lc:3,lp:0,pb:2}];return function(c){return a[c-1]||a[0]}}();"undefined"===typeof onmessage||"undefined"!=typeof window&&"undefined"!=typeof window.document||function(){onmessage=function(a){a&&a.data&&(2==a.data.action?LZMA.decompress(a.data.data,a.data.callback_num):1==a.data.action&&LZMA.compress(a.data.data,a.data.mode,a.data.callback_num))}}();return{compress:function(a,c,b,e){function d(){var a;
for(a=(new Date).getTime();tb(f.c);)if(m=Z(f.c.chunker.inBytesProcessed)/Z(f.c.length_0),200<(new Date).getTime()-a)return e?e(m):"undefined"!==typeof k&&qa(m,k),pa(d,0),!1;e?e(1):"undefined"!==typeof k&&qa(1,k);a=sb(f.c.output);b?b(a):"undefined"!==typeof k&&postMessage({action:1,callback_num:k,result:a.slice(0)})}var f=$b(new ac),m,k;"function"!==typeof b&&(k=b,b=e=0);f.mode=Xc(c);f.c=pc(new Sc,Lc(a),f.mode);e?e(0):"undefined"!==typeof k&&qa(0,k);pa(d,0)},decompress:function(a,c,b){function e(){var a;
a=0;for(var h=(new Date).getTime();tb(d.d);)if(0==++a%1E3&&200<(new Date).getTime()-h)return k&&(f=Z(d.d.chunker.decoder.nowPos64)/Z(d.d.length_0),b?b(f):"undefined"!==typeof m&&qa(f,m)),pa(e,0),!1;k&&(b?b(1):"undefined"!==typeof m&&qa(1,m));a=Jc(sb(d.d.output));c?c(a):"undefined"!==typeof m&&postMessage({action:2,callback_num:m,result:new Uint8Array(a)})}var d=$b(new ac),f,m,k;"function"!==typeof c&&(m=c,c=b=0);a=cc(fa,0,-1,a);d.d=zc(new Uc,a);k=-1<Z(d.d.length_0);b?b(k?0:-1):"undefined"!==typeof m&&
qa(k?0:-1,m);pa(e,0)}}}();this.LZMA=this.LZMA_WORKER=LZMA;
