var LZMA=function(){function G(a,b){postMessage({action:3,cbn:b,result:a})}function n(a){var b=[];b[a-1]=void 0;return b}function D(a,b){return T(a[0]+b[0],a[1]+b[1])}function ka(a,b){var c=~~Math.max(Math.min(a[1]/4294967296,2147483647),-2147483648)&~~Math.max(Math.min(b[1]/4294967296,2147483647),-2147483648),d=x(a)&x(b),e;e=d;0>d&&(e+=4294967296);return[e,4294967296*c]}function H(a,b){var c,d;if(a[0]==b[0]&&a[1]==b[1])return 0;c=0>a[1];d=0>b[1];return c&&!d?-1:!c&&d?1:0>T(a[0]-b[0],a[1]-b[1])[1]?
-1:1}function T(a,b){var c,d;b%=1.8446744073709552E19;a%=1.8446744073709552E19;c=b%4294967296;d=4294967296*Math.floor(a/4294967296);b=b-c+d;for(a=a-d+c;0>a;)a+=4294967296,b-=4294967296;for(;4294967295<a;)a-=4294967296,b+=4294967296;for(b%=1.8446744073709552E19;0x7fffffff00000000<b;)b-=1.8446744073709552E19;for(;-9223372036854775808>b;)b+=1.8446744073709552E19;return[a,b]}function E(a){return 0<=a?[a,0]:[a+4294967296,-4294967296]}function x(a){return 2147483648<=a[0]?~~Math.max(Math.min(a[0]-4294967296,
2147483647),-2147483648):~~Math.max(Math.min(a[0],2147483647),-2147483648)}function U(a){return 30>=a?1<<a:U(30)*U(a-30)}function la(a,b){var c,d,e;b&=63;if(a[0]==ma[0]&&a[1]==ma[1])return b?B:a;if(0>a[1])throw Error("Neg");c=U(b);d=a[1]*c%1.8446744073709552E19;e=a[0]*c;c=e-e%4294967296;d+=c;0x7fffffffffffffff<=d&&(d-=1.8446744073709552E19);return[e-c,d]}function na(a,b){var c;c=U(b&63);return T(Math.floor(a[0]/c),a[1]/c)}function oa(a,b){a.buf=b;a.pos=0;a.count=b.length;return a}function I(a){return a.pos>=
a.count?-1:a.buf[a.pos++]&255}function pa(a){a.buf=n(32);a.count=0;return a}function qa(a){var b=a.buf;b.length=a.count;return b}function ea(a,b,c,d,e){for(var f=0;f<e;++f)c[d+f]=a[b+f]}function Oa(a,b,c){a.output=pa({});var d=oa({},b),e=a.output,f=E(b.length);if(0>H(f,V))throw Error("invalid length "+f);a.length_0=f;b={};var h;b._repDistances=n(4);b._optimum=[];b._rangeEncoder={};b._isMatch=n(192);b._isRep=n(12);b._isRepG0=n(12);b._isRepG1=n(12);b._isRepG2=n(12);b._isRep0Long=n(192);b._posSlotEncoder=
[];b._posEncoders=n(114);b._posAlignEncoder=N({},4);b._lenEncoder=ra({});b._repMatchLenEncoder=ra({});b._literalEncoder={};b._matchDistances=[];b._posSlotPrices=[];b._distancesPrices=[];b._alignPrices=n(16);b.reps=n(4);b.repLens=n(4);b.processedInSize=[B];b.processedOutSize=[B];b.finished=[0];b.properties=n(5);b.tempPrices=n(128);b._longestMatchLength=0;b._matchFinderType=1;b._numDistancePairs=0;b._numFastBytesPrev=-1;for(h=b.backRes=0;4096>h;++h)b._optimum[h]={};for(h=0;4>h;++h)b._posSlotEncoder[h]=
N({},6);h=1<<c.s;b._dictionarySize=h;for(var g=0;h>1<<g;++g);b._distTableSize=2*g;b._numFastBytes=c.f;h=b._matchFinderType;b._matchFinderType=c.m;b._matchFinder&&h!=b._matchFinderType&&(b._dictionarySizePrev=-1,b._matchFinder=null);b._numLiteralPosStateBits=0;b._numLiteralContextBits=3;b._posStateBits=2;b._posStateMask=3;b._writeEndMark=1;b.properties[0]=9*(5*b._posStateBits+b._numLiteralPosStateBits)+b._numLiteralContextBits<<24>>24;for(c=0;4>c;++c)b.properties[1+c]=b._dictionarySize>>8*c<<24>>24;
ea(b.properties,0,e.buf,e.count,5);e.count+=5;for(c=0;64>c;c+=8)h=x(na(f,c))&255,e.buf[e.count++]=h<<24>>24;b._needReleaseMFStream=0;b._inStream=d;b._finished=0;b._matchFinder||(d={},f=4,b._matchFinderType||(f=2),d.HASH_ARRAY=2<f,d.HASH_ARRAY?(d.kNumHashDirectBytes=0,d.kMinMatchCheck=4,d.kFixHashSize=66560):(d.kNumHashDirectBytes=2,d.kMinMatchCheck=3,d.kFixHashSize=0),b._matchFinder=d);d=b._literalEncoder;f=b._numLiteralPosStateBits;c=b._numLiteralContextBits;if(null==d.m_Coders||d.m_NumPrevBits!=
c||d.m_NumPosBits!=f)for(d.m_NumPosBits=f,d.m_PosMask=(1<<f)-1,d.m_NumPrevBits=c,c=1<<d.m_NumPrevBits+d.m_NumPosBits,d.m_Coders=n(c),f=0;f<c;++f){h=d.m_Coders;var g=f,k={};k.m_Encoders=n(768);h[g]=k}if(b._dictionarySize!=b._dictionarySizePrev||b._numFastBytesPrev!=b._numFastBytes){d=b._matchFinder;f=b._dictionarySize;c=b._numFastBytes;if(1073741567>f){d._cutValue=16+(c>>1);g=f+4096;h=c+274;d._keepSizeBefore=g;d._keepSizeAfter=h;g=g+h+(~~((f+4096+c+274)/2)+256);if(null==d._bufferBase||d._blockSize!=
g)d._bufferBase=null,d._blockSize=g,d._bufferBase=n(d._blockSize);d._pointerToLastSafePosition=d._blockSize-h;d._matchMaxLen=c;c=f+1;d._cyclicBufferSize!=c&&(d._son=n(2*(d._cyclicBufferSize=c)));c=65536;d.HASH_ARRAY&&(c=f-1,c|=c>>1,c|=c>>2,c|=c>>4,c=(c|c>>8)>>1,c|=65535,16777216<c&&(c>>=1),d._hashMask=c,++c,c+=d.kFixHashSize);c!=d._hashSizeSum&&(d._hash=n(d._hashSizeSum=c))}b._dictionarySizePrev=b._dictionarySize;b._numFastBytesPrev=b._numFastBytes}b._rangeEncoder.Stream=e;b._state=0;for(e=b._previousByte=
0;4>e;++e)b._repDistances[e]=0;e=b._rangeEncoder;e._position=B;e.Low=B;e.Range=-1;e._cacheSize=1;e._cache=0;u(b._isMatch);u(b._isRep0Long);u(b._isRep);u(b._isRepG0);u(b._isRepG1);u(b._isRepG2);u(b._posEncoders);e=b._literalEncoder;f=1<<e.m_NumPrevBits+e.m_NumPosBits;for(d=0;d<f;++d)u(e.m_Coders[d].m_Encoders);for(e=0;4>e;++e)u(b._posSlotEncoder[e].Models);sa(b._lenEncoder,1<<b._posStateBits);sa(b._repMatchLenEncoder,1<<b._posStateBits);u(b._posAlignEncoder.Models);b._longestMatchWasFound=0;b._optimumEndIndex=
0;b._optimumCurrentIndex=0;b._additionalOffset=0;ta(b);ua(b);b._lenEncoder._tableSize=b._numFastBytes+1-2;va(b._lenEncoder,1<<b._posStateBits);b._repMatchLenEncoder._tableSize=b._numFastBytes+1-2;va(b._repMatchLenEncoder,1<<b._posStateBits);b.nowPos64=B;void 0;e={};e.encoder=b;e.decoder=null;e.alive=1;a.chunker=e;return a}function Pa(a,b){a.output=pa({});var c=oa({},b),d=a.output,e="",f,h=[],g;for(f=0;5>f;++f){g=I(c);if(-1==g)throw Error("truncated input");h[f]=g<<24>>24}var k={m_OutWindow:{},m_RangeDecoder:{}};
k.m_IsMatchDecoders=n(192);k.m_IsRepDecoders=n(12);k.m_IsRepG0Decoders=n(12);k.m_IsRepG1Decoders=n(12);k.m_IsRepG2Decoders=n(12);k.m_IsRep0LongDecoders=n(192);k.m_PosSlotDecoder=n(4);k.m_PosDecoders=n(114);k.m_PosAlignDecoder=O({},4);k.m_LenDecoder=wa({});k.m_RepLenDecoder=wa({});k.m_LiteralDecoder={};for(f=0;4>f;++f)k.m_PosSlotDecoder[f]=O({},6);var m,l,q;if(5>h.length)f=0;else{f=h[0]&255;l=f%9;f=~~(f/9);q=f%5;g=~~(f/5);for(m=f=0;4>m;++m)f+=(h[1+m]&255)<<8*m;if(!(h=99999999<f)){if(8<l||4<q||4<g)g=
0;else{h=k.m_LiteralDecoder;if(null==h.m_Coders||h.m_NumPrevBits!=l||h.m_NumPosBits!=q)for(h.m_NumPosBits=q,h.m_PosMask=(1<<q)-1,h.m_NumPrevBits=l,q=1<<h.m_NumPrevBits+h.m_NumPosBits,h.m_Coders=n(q),l=0;l<q;++l){m=h.m_Coders;var p=l,v={};v.m_Decoders=n(768);m[p]=v}g=1<<g;xa(k.m_LenDecoder,g);xa(k.m_RepLenDecoder,g);k.m_PosStateMask=g-1;g=1}h=!g}if(h)f=0;else if(0>f)f=0;else{if(k.m_DictionarySize!=f){k.m_DictionarySize=f;k.m_DictionarySizeCheck=Math.max(k.m_DictionarySize,1);f=k.m_OutWindow;g=Math.max(k.m_DictionarySizeCheck,
4096);if(null==f._buffer||f._windowSize!=g)f._buffer=n(g);f._windowSize=g;f._pos=0;f._streamPos=0}f=1}}if(!f)throw Error("corrupted input");for(f=0;64>f;f+=8){g=I(c);if(-1==g)throw Error("truncated input");g=g.toString(16);1==g.length&&(g="0"+g);e=g+""+e}/^0+$|^f+$/i.test(e)?a.length_0=V:(e=parseInt(e,16),a.length_0=4294967295<e?V:E(e));e=a.length_0;k.m_RangeDecoder.Stream=c;c=k.m_OutWindow;P(c);c._stream=null;k.m_OutWindow._stream=d;k.m_OutWindow._streamPos=0;k.m_OutWindow._pos=0;u(k.m_IsMatchDecoders);
u(k.m_IsRep0LongDecoders);u(k.m_IsRepDecoders);u(k.m_IsRepG0Decoders);u(k.m_IsRepG1Decoders);u(k.m_IsRepG2Decoders);u(k.m_PosDecoders);d=k.m_LiteralDecoder;f=1<<d.m_NumPrevBits+d.m_NumPosBits;for(c=0;c<f;++c)u(d.m_Coders[c].m_Decoders);for(d=0;4>d;++d)u(k.m_PosSlotDecoder[d].Models);ya(k.m_LenDecoder);ya(k.m_RepLenDecoder);u(k.m_PosAlignDecoder.Models);d=k.m_RangeDecoder;d.Code=0;d.Range=-1;for(c=0;5>c;++c)d.Code=d.Code<<8|I(d.Stream);k.state=0;k.rep0=0;k.rep1=0;k.rep2=0;k.rep3=0;k.outSize=e;k.nowPos64=
B;k.prevByte=0;d={};d.decoder=k;d.encoder=null;d.alive=1;a.chunker=d;return a}function C(a,b){return a._bufferBase[a._bufferOffset+a._pos+b]}function J(a,b,c,d){var e;a._streamEndWasReached&&a._pos+b+d>a._streamPos&&(d=a._streamPos-(a._pos+b));++c;e=a._bufferOffset+a._pos+b;for(b=0;b<d&&a._bufferBase[e+b]==a._bufferBase[e+b-c];++b);return b}function Q(a){return a._streamPos-a._pos}function za(a){var b,c;if(!a._streamEndWasReached)for(;;){c=-a._bufferOffset+a._blockSize-a._streamPos;if(!c)break;b=
a._stream;var d=a._bufferBase,e=a._bufferOffset+a._streamPos;b.pos>=b.count?b=-1:(c=Math.min(c,b.count-b.pos),ea(b.buf,b.pos,d,e,c),b.pos+=c,b=c);if(-1==b){a._posLimit=a._streamPos;b=a._bufferOffset+a._posLimit;b>a._pointerToLastSafePosition&&(a._posLimit=a._pointerToLastSafePosition-a._bufferOffset);a._streamEndWasReached=1;break}a._streamPos+=b;a._streamPos>=a._pos+a._keepSizeAfter&&(a._posLimit=a._streamPos-a._keepSizeAfter)}}function Aa(a,b){a._bufferOffset+=b;a._posLimit-=b;a._pos-=b;a._streamPos-=
b}function W(a){var b;++a._cyclicBufferPos>=a._cyclicBufferSize&&(a._cyclicBufferPos=0);++a._pos;if(a._pos>a._posLimit){b=a._bufferOffset+a._pos;if(b>a._pointerToLastSafePosition){var c,d;d=a._bufferOffset+a._pos-a._keepSizeBefore;0<d&&--d;c=a._bufferOffset+a._streamPos-d;for(b=0;b<c;++b)a._bufferBase[b]=a._bufferBase[d+b];a._bufferOffset-=d}za(a)}1073741823==a._pos&&(b=a._pos-a._cyclicBufferSize,Ba(a._son,2*a._cyclicBufferSize,b),Ba(a._hash,a._hashSizeSum,b),Aa(a,b))}function Ba(a,b,c){var d,e;for(d=
0;d<b;++d)e=a[d]||0,e=e<=c?0:e-c,a[d]=e}function Ca(a,b){var c,d,e,f,h,g,k,m,l,q,p,v;do{if(a._pos+a._matchMaxLen<=a._streamPos)m=a._matchMaxLen;else if(m=a._streamPos-a._pos,m<a.kMinMatchCheck){W(a);continue}l=a._pos>a._cyclicBufferSize?a._pos-a._cyclicBufferSize:0;d=a._bufferOffset+a._pos;a.HASH_ARRAY?(e=X[a._bufferBase[d]&255]^a._bufferBase[d+1]&255,c=e&1023,a._hash[c]=a._pos,e^=(a._bufferBase[d+2]&255)<<8,c=e&65535,a._hash[1024+c]=a._pos,c=(e^X[a._bufferBase[d+3]&255]<<5)&a._hashMask):c=a._bufferBase[d]&
255^(a._bufferBase[d+1]&255)<<8;e=a._hash[a.kFixHashSize+c];a._hash[a.kFixHashSize+c]=a._pos;p=(a._cyclicBufferPos<<1)+1;v=a._cyclicBufferPos<<1;g=k=a.kNumHashDirectBytes;for(c=a._cutValue;;){if(e<=l||0==c--){a._son[p]=a._son[v]=0;break}f=a._pos-e;f=(f<=a._cyclicBufferPos?a._cyclicBufferPos-f:a._cyclicBufferPos-f+a._cyclicBufferSize)<<1;q=a._bufferOffset+e;h=g<k?g:k;if(a._bufferBase[q+h]==a._bufferBase[d+h]){for(;++h!=m&&a._bufferBase[q+h]==a._bufferBase[d+h];);if(h==m){a._son[v]=a._son[f];a._son[p]=
a._son[f+1];break}}(a._bufferBase[q+h]&255)<(a._bufferBase[d+h]&255)?(a._son[v]=e,v=f+1,e=a._son[v],k=h):(a._son[p]=e,p=f,e=a._son[p],g=h)}W(a)}while(0!=--b)}function P(a){var b=a._pos-a._streamPos;if(b){var c=a._stream;ea(a._buffer,a._streamPos,c.buf,c.count,b);c.count+=b;a._pos>=a._windowSize&&(a._pos=0);a._streamPos=a._pos}}function Da(a,b){var c=a._pos-b-1;0>c&&(c+=a._windowSize);return a._buffer[c]}function Y(a){a-=2;return 4>a?a:3}function F(a){return 4>a?0:10>a?a-3:a-6}function Ea(a){if(!a.alive)throw Error("bad state");
if(a.encoder){a:{var b=a.encoder,c=a.encoder.processedInSize,d=a.encoder.processedOutSize,e=a.encoder.finished,f,h,g,k,m,l,q,p;c[0]=B;d[0]=B;e[0]=1;b._inStream&&(b._matchFinder._stream=b._inStream,p=b._matchFinder,p._bufferOffset=0,p._pos=0,p._streamPos=0,p._streamEndWasReached=0,za(p),p._cyclicBufferPos=0,Aa(p,-1),b._needReleaseMFStream=1,b._inStream=null);if(!b._finished){b._finished=1;m=p=b.nowPos64;if(m[0]==B[0]&&m[1]==B[1]){if(!Q(b._matchFinder)){fa(b,x(b.nowPos64));break a}ga(b);q=x(b.nowPos64)&
b._posStateMask;w(b._rangeEncoder,b._isMatch,(b._state<<4)+q,0);b._state=F(b._state);g=C(b._matchFinder,-b._additionalOffset);Fa(K(b._literalEncoder,x(b.nowPos64),b._previousByte),b._rangeEncoder,g);b._previousByte=g;--b._additionalOffset;b.nowPos64=D(b.nowPos64,Ga)}if(Q(b._matchFinder))for(;;){m=Qa(b,x(b.nowPos64));g=b.backRes;q=x(b.nowPos64)&b._posStateMask;h=(b._state<<4)+q;if(1==m&&-1==g){w(b._rangeEncoder,b._isMatch,h,0);g=C(b._matchFinder,-b._additionalOffset);h=K(b._literalEncoder,x(b.nowPos64),
b._previousByte);if(7>b._state)Fa(h,b._rangeEncoder,g);else{f=C(b._matchFinder,-b._repDistances[0]-1-b._additionalOffset);q=b._rangeEncoder;k=g;for(var v=l=void 0,n=void 0,r=void 0,t=n=1,v=7;0<=v;--v)l=k>>v&1,r=t,n&&(n=f>>v&1,r+=1+n<<8,n=n==l),w(q,h.m_Encoders,r,l),t=t<<1|l}b._previousByte=g;b._state=F(b._state)}else{w(b._rangeEncoder,b._isMatch,h,1);if(4>g){if(w(b._rangeEncoder,b._isRep,b._state,1),g?(w(b._rangeEncoder,b._isRepG0,b._state,1),1==g?w(b._rangeEncoder,b._isRepG1,b._state,0):(w(b._rangeEncoder,
b._isRepG1,b._state,1),w(b._rangeEncoder,b._isRepG2,b._state,g-2))):(w(b._rangeEncoder,b._isRepG0,b._state,0),1==m?w(b._rangeEncoder,b._isRep0Long,h,0):w(b._rangeEncoder,b._isRep0Long,h,1)),1==m?b._state=7>b._state?9:11:(ha(b._repMatchLenEncoder,b._rangeEncoder,m-2,q),b._state=7>b._state?8:11),h=b._repDistances[g],0!=g){for(;1<=g;--g)b._repDistances[g]=b._repDistances[g-1];b._repDistances[0]=h}}else{w(b._rangeEncoder,b._isRep,b._state,0);b._state=7>b._state?7:10;ha(b._lenEncoder,b._rangeEncoder,m-
2,q);g-=4;q=ia(g);h=Y(m);R(b._posSlotEncoder[h],b._rangeEncoder,q);if(4<=q)if(k=(q>>1)-1,f=(2|q&1)<<k,l=g-f,14>q)for(h=b._posEncoders,q=f-q-1,f=b._rangeEncoder,r=v=void 0,t=1,r=0;r<k;++r)v=l&1,w(f,h,q+t,v),t=t<<1|v,l>>=1;else Ha(b._rangeEncoder,l>>4,k-4),Ia(b._posAlignEncoder,b._rangeEncoder,l&15),++b._alignPriceCount;h=g;for(g=3;1<=g;--g)b._repDistances[g]=b._repDistances[g-1];b._repDistances[0]=h;++b._matchPriceCount}b._previousByte=C(b._matchFinder,m-1-b._additionalOffset)}b._additionalOffset-=
m;b.nowPos64=D(b.nowPos64,E(m));if(!b._additionalOffset){128<=b._matchPriceCount&&ta(b);16<=b._alignPriceCount&&ua(b);c[0]=b.nowPos64;m=b._rangeEncoder;m=D(D(E(m._cacheSize),m._position),[4,0]);d[0]=m;if(!Q(b._matchFinder)){fa(b,x(b.nowPos64));break}m=b.nowPos64;m=T(m[0]-p[0],m[1]-p[1]);if(0<=H(m,[4096,0])){b._finished=0;e[0]=0;break}}}else fa(b,x(b.nowPos64))}}a.inBytesProcessed=a.encoder.processedInSize[0];a.encoder.finished[0]&&(b=a.encoder,Ja(b),b._rangeEncoder.Stream=null,a.alive=0)}else{a:{b=
a.decoder;e=x(b.nowPos64)&b.m_PosStateMask;if(A(b.m_RangeDecoder,b.m_IsMatchDecoders,(b.state<<4)+e)){if(A(b.m_RangeDecoder,b.m_IsRepDecoders,b.state))c=0,A(b.m_RangeDecoder,b.m_IsRepG0Decoders,b.state)?(A(b.m_RangeDecoder,b.m_IsRepG1Decoders,b.state)?(A(b.m_RangeDecoder,b.m_IsRepG2Decoders,b.state)?(d=b.rep3,b.rep3=b.rep2):d=b.rep2,b.rep2=b.rep1):d=b.rep1,b.rep1=b.rep0,b.rep0=d):A(b.m_RangeDecoder,b.m_IsRep0LongDecoders,(b.state<<4)+e)||(b.state=7>b.state?9:11,c=1),c||(c=Ka(b.m_RepLenDecoder,b.m_RangeDecoder,
e)+2,b.state=7>b.state?8:11);else if(b.rep3=b.rep2,b.rep2=b.rep1,b.rep1=b.rep0,c=2+Ka(b.m_LenDecoder,b.m_RangeDecoder,e),b.state=7>b.state?7:10,m=Z(b.m_PosSlotDecoder[Y(c)],b.m_RangeDecoder),4<=m)if(d=(m>>1)-1,b.rep0=(2|m&1)<<d,14>m){e=b.rep0;p=b.m_PosDecoders;m=b.rep0-m-1;g=b.m_RangeDecoder;f=1;for(q=k=0;q<d;++q)h=A(g,p,m+f),f<<=1,f+=h,k|=h<<q;b.rep0=e+k}else{e=b.rep0;p=b.m_RangeDecoder;m=0;for(d-=4;0!=d;--d)p.Range>>>=1,g=p.Code-p.Range>>>31,p.Code-=p.Range&g-1,m=m<<1|1-g,p.Range&-16777216||(p.Code=
p.Code<<8|I(p.Stream),p.Range<<=8);b.rep0=e+(m<<4);d=b.rep0;e=b.m_PosAlignDecoder;p=b.m_RangeDecoder;h=1;for(g=q=0;g<e.NumBitLevels;++g)m=A(p,e.Models,h),h<<=1,h+=m,q|=m<<g;b.rep0=d+q;if(0>b.rep0){b=-1==b.rep0?1:-1;break a}}else b.rep0=m;if(0<=H(E(b.rep0),b.nowPos64)||b.rep0>=b.m_DictionarySizeCheck){b=-1;break a}d=b.m_OutWindow;e=c;p=d._pos-b.rep0-1;for(0>p&&(p+=d._windowSize);0!=e;--e)p>=d._windowSize&&(p=0),d._buffer[d._pos++]=d._buffer[p++],d._pos>=d._windowSize&&P(d);b.nowPos64=D(b.nowPos64,
E(c));b.prevByte=Da(b.m_OutWindow,0)}else{c=b.m_LiteralDecoder;d=x(b.nowPos64);c=c.m_Coders[((d&c.m_PosMask)<<c.m_NumPrevBits)+((b.prevByte&255)>>>8-c.m_NumPrevBits)];if(7>b.state){d=b.m_RangeDecoder;e=1;do e=e<<1|A(d,c.m_Decoders,e);while(256>e);b.prevByte=e<<24>>24}else{d=b.m_RangeDecoder;e=Da(b.m_OutWindow,b.rep0);g=1;do if(m=e>>7&1,e<<=1,p=A(d,c.m_Decoders,(1+m<<8)+g),g=g<<1|p,m!=p){for(;256>g;)g=g<<1|A(d,c.m_Decoders,g);break}while(256>g);b.prevByte=g<<24>>24}c=b.m_OutWindow;d=b.prevByte;c._buffer[c._pos++]=
d;c._pos>=c._windowSize&&P(c);b.state=F(b.state);b.nowPos64=D(b.nowPos64,Ga)}b=0}if(-1==b)throw Error("corrupted input");a.inBytesProcessed=V;a.outBytesProcessed=a.decoder.nowPos64;if(b||0<=H(a.decoder.outSize,B)&&0<=H(a.decoder.nowPos64,a.decoder.outSize))P(a.decoder.m_OutWindow),b=a.decoder.m_OutWindow,P(b),b._stream=null,a.decoder.m_RangeDecoder.Stream=null,a.alive=0}return a.alive}function xa(a,b){for(;a.m_NumPosStates<b;++a.m_NumPosStates)a.m_LowCoder[a.m_NumPosStates]=O({},3),a.m_MidCoder[a.m_NumPosStates]=
O({},3)}function Ka(a,b,c){if(!A(b,a.m_Choice,0))return Z(a.m_LowCoder[c],b);var d=8;return d=A(b,a.m_Choice,1)?d+(8+Z(a.m_HighCoder,b)):d+Z(a.m_MidCoder[c],b)}function wa(a){a.m_Choice=n(2);a.m_LowCoder=n(16);a.m_MidCoder=n(16);a.m_HighCoder=O({},8);a.m_NumPosStates=0;return a}function ya(a){u(a.m_Choice);for(var b=0;b<a.m_NumPosStates;++b)u(a.m_LowCoder[b].Models),u(a.m_MidCoder[b].Models);u(a.m_HighCoder.Models)}function La(a,b){var c,d,e,f;a._optimumEndIndex=b;e=a._optimum[b].PosPrev;d=a._optimum[b].BackPrev;
do a._optimum[b].Prev1IsChar&&(c=a._optimum[e],c.BackPrev=-1,c.Prev1IsChar=0,a._optimum[e].PosPrev=e-1,a._optimum[b].Prev2&&(a._optimum[e-1].Prev1IsChar=0,a._optimum[e-1].PosPrev=a._optimum[b].PosPrev2,a._optimum[e-1].BackPrev=a._optimum[b].BackPrev2)),f=e,c=d,d=a._optimum[f].BackPrev,e=a._optimum[f].PosPrev,a._optimum[f].BackPrev=c,a._optimum[f].PosPrev=b,b=f;while(0<b);a.backRes=a._optimum[0].BackPrev;a._optimumCurrentIndex=a._optimum[0].PosPrev;return a._optimumCurrentIndex}function ua(a){for(var b=
0;16>b;++b){for(var c=a._alignPrices,d=b,e=a._posAlignEncoder,f=b,h=void 0,g=void 0,k=1,m=0,g=e.NumBitLevels;0!=g;--g)h=f&1,f>>>=1,m+=S(e.Models[k],h),k=k<<1|h;c[d]=m}a._alignPriceCount=0}function ta(a){var b,c,d,e;for(c=4;128>c;++c){e=ia(c);d=(e>>1)-1;b=(2|e&1)<<d;for(var f=a.tempPrices,h=c,g=c-b,k=void 0,m=void 0,l=1,q=0,m=d;0!=m;--m)k=g&1,g>>>=1,q+=t[((a._posEncoders[b-e-1+l]-k^-k)&2047)>>>2],l=l<<1|k;f[h]=q}for(b=0;4>b;++b){c=a._posSlotEncoder[b];d=b<<6;for(e=0;e<a._distTableSize;++e)a._posSlotPrices[d+
e]=aa(c,e);for(e=14;e<a._distTableSize;++e)a._posSlotPrices[d+e]+=(e>>1)-1-4<<6;e=128*b;for(c=0;4>c;++c)a._distancesPrices[e+c]=a._posSlotPrices[d+c];for(;128>c;++c)a._distancesPrices[e+c]=a._posSlotPrices[d+ia(c)]+a.tempPrices[c]}a._matchPriceCount=0}function fa(a,b){Ja(a);var c=b&a._posStateMask;a._writeEndMark&&(w(a._rangeEncoder,a._isMatch,(a._state<<4)+c,1),w(a._rangeEncoder,a._isRep,a._state,0),a._state=7>a._state?7:10,ha(a._lenEncoder,a._rangeEncoder,0,c),c=Y(2),R(a._posSlotEncoder[c],a._rangeEncoder,
63),Ha(a._rangeEncoder,67108863,26),Ia(a._posAlignEncoder,a._rangeEncoder,15));for(c=0;5>c;++c)ja(a._rangeEncoder)}function Qa(a,b){var c,d,e,f,h,g,k,m,l,q,p,v,n,r,u,y,w,z,x,A,B,D,E;if(a._optimumEndIndex!=a._optimumCurrentIndex)return m=a._optimum[a._optimumCurrentIndex].PosPrev-a._optimumCurrentIndex,a.backRes=a._optimum[a._optimumCurrentIndex].BackPrev,a._optimumCurrentIndex=a._optimum[a._optimumCurrentIndex].PosPrev,m;a._optimumCurrentIndex=a._optimumEndIndex=0;a._longestMatchWasFound?(c=a._longestMatchLength,
a._longestMatchWasFound=0):c=ga(a);m=a._numDistancePairs;v=Q(a._matchFinder)+1;if(2>v)return a.backRes=-1,1;for(g=k=0;4>g;++g)a.reps[g]=a._repDistances[g],a.repLens[g]=J(a._matchFinder,-1,a.reps[g],273),a.repLens[g]>a.repLens[k]&&(k=g);if(a.repLens[k]>=a._numFastBytes)return a.backRes=k,m=a.repLens[k],x=m-1,0<x&&(Ca(a._matchFinder,x),a._additionalOffset+=x),m;if(c>=a._numFastBytes)return a.backRes=a._matchDistances[m-1]+4,m=c-1,0<m&&(Ca(a._matchFinder,m),a._additionalOffset+=m),c;h=C(a._matchFinder,
-1);p=C(a._matchFinder,-a._repDistances[0]-1-1);if(2>c&&h!=p&&2>a.repLens[k])return a.backRes=-1,1;a._optimum[0].State=a._state;y=b&a._posStateMask;a._optimum[1].Price=t[a._isMatch[(a._state<<4)+y]>>>2]+ba(K(a._literalEncoder,b,a._previousByte),7<=a._state,p,h);f=a._optimum[1];f.BackPrev=-1;f.Prev1IsChar=0;f=t[2048-a._isMatch[(a._state<<4)+y]>>>2];r=f+t[2048-a._isRep[a._state]>>>2];p==h&&(g=a._state,n=r+(t[a._isRepG0[g]>>>2]+t[a._isRep0Long[(g<<4)+y]>>>2]),n<a._optimum[1].Price&&(a._optimum[1].Price=
n,g=a._optimum[1],g.BackPrev=0,g.Prev1IsChar=0));k=c>=a.repLens[k]?c:a.repLens[k];if(2>k)return a.backRes=a._optimum[1].BackPrev,1;a._optimum[1].PosPrev=0;a._optimum[0].Backs0=a.reps[0];a._optimum[0].Backs1=a.reps[1];a._optimum[0].Backs2=a.reps[2];a._optimum[0].Backs3=a.reps[3];g=k;do a._optimum[g--].Price=268435455;while(2<=g);for(g=0;4>g;++g)if(n=a.repLens[g],!(2>n)){e=r+L(a,g,a._state,y);do d=e+a._repMatchLenEncoder._prices[272*y+(n-2)],l=a._optimum[n],d<l.Price&&(l.Price=d,l.PosPrev=0,l.BackPrev=
g,l.Prev1IsChar=0);while(2<=--n)}f+=t[a._isRep[a._state]>>>2];g=2<=a.repLens[0]?a.repLens[0]+1:2;if(g<=c){for(r=0;g>a._matchDistances[r];)r+=2;for(;c=a._matchDistances[r+1],d=f+Ma(a,c,g,y),l=a._optimum[g],d<l.Price&&(l.Price=d,l.PosPrev=0,l.BackPrev=c+4,l.Prev1IsChar=0),g!=a._matchDistances[r]||(r+=2,r!=m);++g);}for(c=0;;){++c;if(c==k)return La(a,c);e=ga(a);m=a._numDistancePairs;if(e>=a._numFastBytes)return a._longestMatchLength=e,a._longestMatchWasFound=1,La(a,c);++b;f=a._optimum[c].PosPrev;a._optimum[c].Prev1IsChar?
(--f,a._optimum[c].Prev2?(g=a._optimum[a._optimum[c].PosPrev2].State,g=4>a._optimum[c].BackPrev2?7>g?8:11:7>g?7:10):g=a._optimum[f].State,g=F(g)):g=a._optimum[f].State;f==c-1?g=a._optimum[c].BackPrev?F(g):7>g?9:11:(a._optimum[c].Prev1IsChar&&a._optimum[c].Prev2?(f=a._optimum[c].PosPrev2,y=a._optimum[c].BackPrev2,g=7>g?8:11):(y=a._optimum[c].BackPrev,g=4>y?7>g?8:11:7>g?7:10),f=a._optimum[f],4>y?y?1==y?(a.reps[0]=f.Backs1,a.reps[1]=f.Backs0,a.reps[2]=f.Backs2,a.reps[3]=f.Backs3):2==y?(a.reps[0]=f.Backs2,
a.reps[1]=f.Backs0,a.reps[2]=f.Backs1,a.reps[3]=f.Backs3):(a.reps[0]=f.Backs3,a.reps[1]=f.Backs0,a.reps[2]=f.Backs1,a.reps[3]=f.Backs2):(a.reps[0]=f.Backs0,a.reps[1]=f.Backs1,a.reps[2]=f.Backs2,a.reps[3]=f.Backs3):(a.reps[0]=y-4,a.reps[1]=f.Backs0,a.reps[2]=f.Backs1,a.reps[3]=f.Backs2));a._optimum[c].State=g;a._optimum[c].Backs0=a.reps[0];a._optimum[c].Backs1=a.reps[1];a._optimum[c].Backs2=a.reps[2];a._optimum[c].Backs3=a.reps[3];f=a._optimum[c].Price;h=C(a._matchFinder,-1);p=C(a._matchFinder,-a.reps[0]-
1-1);y=b&a._posStateMask;d=f+t[a._isMatch[(g<<4)+y]>>>2]+ba(K(a._literalEncoder,b,C(a._matchFinder,-2)),7<=g,p,h);v=a._optimum[c+1];l=0;d<v.Price&&(v.Price=d,v.PosPrev=c,v.BackPrev=-1,v.Prev1IsChar=0,l=1);f+=t[2048-a._isMatch[(g<<4)+y]>>>2];r=f+t[2048-a._isRep[g]>>>2];p!=h||v.PosPrev<c&&!v.BackPrev||(n=r+(t[a._isRepG0[g]>>>2]+t[a._isRep0Long[(g<<4)+y]>>>2]),n<=v.Price&&(v.Price=n,v.PosPrev=c,v.BackPrev=0,v.Prev1IsChar=0,l=1));n=Q(a._matchFinder)+1;v=n=4095-c<n?4095-c:n;if(!(2>v)){v>a._numFastBytes&&
(v=a._numFastBytes);if(!l&&p!=h&&(l=Math.min(n-1,a._numFastBytes),l=J(a._matchFinder,0,a.reps[0],l),2<=l)){z=F(g);q=b+1&a._posStateMask;d=d+t[2048-a._isMatch[(z<<4)+q]>>>2]+t[2048-a._isRep[z]>>>2];for(u=c+1+l;k<u;)a._optimum[++k].Price=268435455;d+=(x=a._repMatchLenEncoder._prices[272*q+(l-2)],x+L(a,0,z,q));l=a._optimum[u];d<l.Price&&(l.Price=d,l.PosPrev=c+1,l.BackPrev=0,l.Prev1IsChar=1,l.Prev2=0)}p=2;for(w=0;4>w;++w)if(h=J(a._matchFinder,-1,a.reps[w],v),!(2>h)){q=h;do{for(;k<c+h;)a._optimum[++k].Price=
268435455;d=r+(A=a._repMatchLenEncoder._prices[272*y+(h-2)],A+L(a,w,g,y));l=a._optimum[c+h];d<l.Price&&(l.Price=d,l.PosPrev=c,l.BackPrev=w,l.Prev1IsChar=0)}while(2<=--h);h=q;w||(p=h+1);if(h<n&&(l=Math.min(n-1-h,a._numFastBytes),l=J(a._matchFinder,h,a.reps[w],l),2<=l)){z=7>g?8:11;q=b+h&a._posStateMask;d=r+(B=a._repMatchLenEncoder._prices[272*y+(h-2)],B+L(a,w,g,y))+t[a._isMatch[(z<<4)+q]>>>2]+ba(K(a._literalEncoder,b+h,C(a._matchFinder,h-1-1)),1,C(a._matchFinder,h-1-(a.reps[w]+1)),C(a._matchFinder,
h-1));z=F(z);q=b+h+1&a._posStateMask;d+=t[2048-a._isMatch[(z<<4)+q]>>>2];d+=t[2048-a._isRep[z]>>>2];for(u=h+1+l;k<c+u;)a._optimum[++k].Price=268435455;d+=(D=a._repMatchLenEncoder._prices[272*q+(l-2)],D+L(a,0,z,q));l=a._optimum[c+u];d<l.Price&&(l.Price=d,l.PosPrev=c+h+1,l.BackPrev=0,l.Prev1IsChar=1,l.Prev2=1,l.PosPrev2=c,l.BackPrev2=w)}}if(e>v){e=v;for(m=0;e>a._matchDistances[m];m+=2);a._matchDistances[m]=e;m+=2}if(e>=p){for(f+=t[a._isRep[g]>>>2];k<c+e;)a._optimum[++k].Price=268435455;for(r=0;p>a._matchDistances[r];)r+=
2;for(h=p;;++h)if(e=a._matchDistances[r+1],d=f+Ma(a,e,h,y),l=a._optimum[c+h],d<l.Price&&(l.Price=d,l.PosPrev=c,l.BackPrev=e+4,l.Prev1IsChar=0),h==a._matchDistances[r]){if(h<n&&(l=Math.min(n-1-h,a._numFastBytes),l=J(a._matchFinder,h,e,l),2<=l)){z=7>g?7:10;q=b+h&a._posStateMask;d=d+t[a._isMatch[(z<<4)+q]>>>2]+ba(K(a._literalEncoder,b+h,C(a._matchFinder,h-1-1)),1,C(a._matchFinder,h-(e+1)-1),C(a._matchFinder,h-1));z=F(z);q=b+h+1&a._posStateMask;d+=t[2048-a._isMatch[(z<<4)+q]>>>2];d+=t[2048-a._isRep[z]>>>
2];for(u=h+1+l;k<c+u;)a._optimum[++k].Price=268435455;d+=(E=a._repMatchLenEncoder._prices[272*q+(l-2)],E+L(a,0,z,q));l=a._optimum[c+u];d<l.Price&&(l.Price=d,l.PosPrev=c+h+1,l.BackPrev=0,l.Prev1IsChar=1,l.Prev2=1,l.PosPrev2=c,l.BackPrev2=e+4)}r+=2;if(r==m)break}}}}}function Ma(a,b,c,d){var e=Y(c);if(128>b)b=a._distancesPrices[128*e+b];else{var f=a._posSlotPrices,h;h=131072>b?M[b>>6]+12:134217728>b?M[b>>16]+32:M[b>>26]+52;b=f[(e<<6)+h]+a._alignPrices[b&15]}return b+a._lenEncoder._prices[272*d+(c-2)]}
function L(a,b,c,d){var e;b?(e=t[2048-a._isRepG0[c]>>>2],1==b?e+=t[a._isRepG1[c]>>>2]:(e+=t[2048-a._isRepG1[c]>>>2],e+=S(a._isRepG2[c],b-2))):(e=t[a._isRepG0[c]>>>2],e+=t[2048-a._isRep0Long[(c<<4)+d]>>>2]);return e}function ga(a){var b=0,c;a:{c=a._matchFinder;var d=a._matchDistances,e,f,h,g,k,m,l,q,p,n,t,r,u,w,x;if(c._pos+c._matchMaxLen<=c._streamPos)p=c._matchMaxLen;else if(p=c._streamPos-c._pos,p<c.kMinMatchCheck){W(c);c=0;break a}r=0;n=c._pos>c._cyclicBufferSize?c._pos-c._cyclicBufferSize:0;f=
c._bufferOffset+c._pos;t=1;m=e=0;c.HASH_ARRAY?(h=X[c._bufferBase[f]&255]^c._bufferBase[f+1]&255,e=h&1023,h^=(c._bufferBase[f+2]&255)<<8,m=h&65535,l=(h^X[c._bufferBase[f+3]&255]<<5)&c._hashMask):l=c._bufferBase[f]&255^(c._bufferBase[f+1]&255)<<8;h=c._hash[c.kFixHashSize+l]||0;c.HASH_ARRAY&&(g=c._hash[e]||0,k=c._hash[1024+m]||0,c._hash[e]=c._pos,c._hash[1024+m]=c._pos,g>n&&c._bufferBase[c._bufferOffset+g]==c._bufferBase[f]&&(d[r++]=t=2,d[r++]=c._pos-g-1),k>n&&c._bufferBase[c._bufferOffset+k]==c._bufferBase[f]&&
(k==g&&(r-=2),d[r++]=t=3,d[r++]=c._pos-k-1,g=k),0!=r&&g==h&&(r-=2,t=1));c._hash[c.kFixHashSize+l]=c._pos;w=(c._cyclicBufferPos<<1)+1;x=c._cyclicBufferPos<<1;l=q=c.kNumHashDirectBytes;0!=c.kNumHashDirectBytes&&h>n&&c._bufferBase[c._bufferOffset+h+c.kNumHashDirectBytes]!=c._bufferBase[f+c.kNumHashDirectBytes]&&(d[r++]=t=c.kNumHashDirectBytes,d[r++]=c._pos-h-1);for(e=c._cutValue;;){if(h<=n||0==e--){c._son[w]=c._son[x]=0;break}g=c._pos-h;m=(g<=c._cyclicBufferPos?c._cyclicBufferPos-g:c._cyclicBufferPos-
g+c._cyclicBufferSize)<<1;u=c._bufferOffset+h;k=l<q?l:q;if(c._bufferBase[u+k]==c._bufferBase[f+k]){for(;++k!=p&&c._bufferBase[u+k]==c._bufferBase[f+k];);if(t<k&&(d[r++]=t=k,d[r++]=g-1,k==p)){c._son[x]=c._son[m];c._son[w]=c._son[m+1];break}}(c._bufferBase[u+k]&255)<(c._bufferBase[f+k]&255)?(c._son[x]=h,x=m+1,h=c._son[x],q=k):(c._son[w]=h,w=m,h=c._son[w],l=k)}W(c);c=r}a._numDistancePairs=c;0<a._numDistancePairs&&(b=a._matchDistances[a._numDistancePairs-2],b==a._numFastBytes&&(b+=J(a._matchFinder,b-
1,a._matchDistances[a._numDistancePairs-1],273-b)));++a._additionalOffset;return b}function Ja(a){a._matchFinder&&a._needReleaseMFStream&&(a._matchFinder._stream=null,a._needReleaseMFStream=0)}function ia(a){return 2048>a?M[a]:2097152>a?M[a>>10]+20:M[a>>20]+40}function sa(a,b){u(a._choice);for(var c=0;c<b;++c)u(a._lowCoder[c].Models),u(a._midCoder[c].Models);u(a._highCoder.Models)}function Na(a,b,c,d,e){var f,h,g,k;f=t[a._choice[0]>>>2];h=t[2048-a._choice[0]>>>2];g=h+t[a._choice[1]>>>2];h+=t[2048-
a._choice[1]>>>2];for(k=0;8>k;++k){if(k>=c)return;d[e+k]=f+aa(a._lowCoder[b],k)}for(;16>k;++k){if(k>=c)return;d[e+k]=g+aa(a._midCoder[b],k-8)}for(;k<c;++k)d[e+k]=h+aa(a._highCoder,k-8-8)}function ha(a,b,c,d){8>c?(w(b,a._choice,0,0),R(a._lowCoder[d],b,c)):(c-=8,w(b,a._choice,0,1),8>c?(w(b,a._choice,1,0),R(a._midCoder[d],b,c)):(w(b,a._choice,1,1),R(a._highCoder,b,c-8)));0==--a._counters[d]&&(Na(a,d,a._tableSize,a._prices,272*d),a._counters[d]=a._tableSize)}function ra(a){a._choice=n(2);a._lowCoder=
n(16);a._midCoder=n(16);a._highCoder=N({},8);for(var b=0;16>b;++b)a._lowCoder[b]=N({},3),a._midCoder[b]=N({},3);a._prices=[];a._counters=[];return a}function va(a,b){for(var c=0;c<b;++c)Na(a,c,a._tableSize,a._prices,272*c),a._counters[c]=a._tableSize}function K(a,b,c){return a.m_Coders[((b&a.m_PosMask)<<a.m_NumPrevBits)+((c&255)>>>8-a.m_NumPrevBits)]}function Fa(a,b,c){var d,e,f=1;for(e=7;0<=e;--e)d=c>>e&1,w(b,a.m_Encoders,f,d),f=f<<1|d}function ba(a,b,c,d){var e=1,f=7,h,g=0;if(b)for(;0<=f;--f)if(h=
c>>f&1,b=d>>f&1,g+=S(a.m_Encoders[(1+h<<8)+e],b),e=e<<1|b,h!=b){--f;break}for(;0<=f;--f)b=d>>f&1,g+=S(a.m_Encoders[e],b),e=e<<1|b;return g}function O(a,b){a.NumBitLevels=b;a.Models=n(1<<b);return a}function Z(a,b){var c,d=1;for(c=a.NumBitLevels;0!=c;--c)d=(d<<1)+A(b,a.Models,d);return d-(1<<a.NumBitLevels)}function N(a,b){a.NumBitLevels=b;a.Models=n(1<<b);return a}function R(a,b,c){var d,e,f=1;for(e=a.NumBitLevels;0!=e;)--e,d=c>>>e&1,w(b,a.Models,f,d),f=f<<1|d}function aa(a,b){var c,d,e=1,f=0;for(d=
a.NumBitLevels;0!=d;)--d,c=b>>>d&1,f+=S(a.Models[e],c),e=(e<<1)+c;return f}function Ia(a,b,c){var d,e,f=1;for(e=0;e<a.NumBitLevels;++e)d=c&1,w(b,a.Models,f,d),f=f<<1|d,c>>=1}function A(a,b,c){var d,e=b[c];d=(a.Range>>>11)*e;if((a.Code^-2147483648)<(d^-2147483648))return a.Range=d,b[c]=e+(2048-e>>>5)<<16>>16,a.Range&-16777216||(a.Code=a.Code<<8|I(a.Stream),a.Range<<=8),0;a.Range-=d;a.Code-=d;b[c]=e-(e>>>5)<<16>>16;a.Range&-16777216||(a.Code=a.Code<<8|I(a.Stream),a.Range<<=8);return 1}function u(a){for(var b=
a.length-1;0<=b;--b)a[b]=1024}function w(a,b,c,d){var e,f=b[c];e=(a.Range>>>11)*f;d?(a.Low=D(a.Low,ka(E(e),[4294967295,0])),a.Range-=e,b[c]=f-(f>>>5)<<16>>16):(a.Range=e,b[c]=f+(2048-f>>>5)<<16>>16);a.Range&-16777216||(a.Range<<=8,ja(a))}function Ha(a,b,c){for(--c;0<=c;--c)a.Range>>>=1,1==(b>>>c&1)&&(a.Low=D(a.Low,E(a.Range))),a.Range&-16777216||(a.Range<<=8,ja(a))}function ja(a){var b,c=a.Low,d;d=32;b=na(c,d);0>c[1]&&(b=D(b,la([2,0],63-d)));c=x(b);if(0!=c||0>H(a.Low,[4278190080,0])){a._position=
D(a._position,E(a._cacheSize));b=a._cache;do d=a.Stream,b+=c,d.buf[d.count++]=b<<24>>24,b=255;while(0!=--a._cacheSize);a._cache=x(a.Low)>>>24}++a._cacheSize;a.Low=la(ka(a.Low,[16777215,0]),8)}function S(a,b){return t[((a-b^-b)&2047)>>>2]}function Ra(a){for(var b=0,c=0,d,e,f,h=a.length,g=[],k=[];b<h;++b,++c){d=a[b]&255;if(d&128)if(192==(d&224)){if(b+1>=h)return a;e=a[++b]&255;if(128!=(e&192))return a;k[c]=(d&31)<<6|e&63}else if(224==(d&240)){if(b+2>=h)return a;e=a[++b]&255;if(128!=(e&192))return a;
f=a[++b]&255;if(128!=(f&192))return a;k[c]=(d&15)<<12|(e&63)<<6|f&63}else return a;else{if(!d)return a;k[c]=d}65535==c&&(g.push(String.fromCharCode.apply(String,k)),c=-1)}0<c&&(k.length=c,g.push(String.fromCharCode.apply(String,k)));return g.join("")}function Sa(a){var b=[],c,d=0,e,f=a.length;if("object"==typeof a)return a;for(e=c=0;e<f;++e)b[c++]=a.charCodeAt(e);for(e=0;e<f;++e)a=b[e],1<=a&&127>=a?++d:d=!a||128<=a&&2047>=a?d+2:d+3;c=[];for(e=d=0;e<f;++e)a=b[e],1<=a&&127>=a?c[d++]=a<<24>>24:(!a||
128<=a&&2047>=a?c[d++]=(192|a>>6&31)<<24>>24:(c[d++]=(224|a>>12&15)<<24>>24,c[d++]=(128|a>>6&63)<<24>>24),c[d++]=(128|a&63)<<24>>24);return c}function ca(a){return a[1]+a[0]}var da="function"==typeof setImmediate?setImmediate:setTimeout,V=[4294967295,-4294967296],ma=[0,-9223372036854775808],B=[0,0],Ga=[1,0],X=function(){var a,b,c,d=[];for(a=0;256>a;++a){c=a;for(b=0;8>b;++b)c=0!=(c&1)?c>>>1^-306674912:c>>>1;d[a]=c}return d}(),M=function(){var a,b,c,d=2,e=[0,1];for(c=2;22>c;++c)for(b=1<<(c>>1)-1,a=
0;a<b;++a,++d)e[d]=c<<24>>24;return e}(),t=function(){var a,b,c,d=[];for(b=8;0<=b;--b)for(c=1<<9-b-1,a=1<<9-b;c<a;++c)d[c]=(b<<6)+(a-c<<6>>>9-b-1);return d}(),Ta=function(){var a=[{s:16,f:64,m:0},{s:20,f:64,m:0},{s:19,f:64,m:1},{s:20,f:64,m:1},{s:21,f:128,m:1},{s:22,f:128,m:1},{s:23,f:128,m:1},{s:24,f:255,m:1},{s:25,f:255,m:1}];return function(b){return a[b-1]||a[6]}}();"undefined"==typeof onmessage||"undefined"!=typeof window&&"undefined"!=typeof window.document||function(){onmessage=function(a){a&&
a.data&&(2==a.data.action?LZMA.decompress(a.data.data,a.data.cbn):1==a.data.action&&LZMA.compress(a.data.data,a.data.mode,a.data.cbn))}}();return{compress:function(a,b,c,d){function e(){var a;for(a=(new Date).getTime();Ea(f.c.chunker);)if(h=ca(f.c.chunker.inBytesProcessed)/ca(f.c.length_0),200<(new Date).getTime()-a)return d?d(h):"undefined"!=typeof g&&G(h,g),da(e,0),0;d?d(1):"undefined"!=typeof g&&G(1,g);a=qa(f.c.output);c?c(a):"undefined"!=typeof g&&postMessage({action:1,cbn:g,result:a})}var f=
{},h,g;"function"!=typeof c&&(g=c,c=d=0);f.c=Oa({},Sa(a),Ta(b));d?d(0):"undefined"!=typeof g&&G(0,g);da(e,0)},decompress:function(a,b,c){function d(){var a;a=0;for(var l=(new Date).getTime();Ea(e.d.chunker);)if(0==++a%1E3&&200<(new Date).getTime()-l)return g&&(f=ca(e.d.chunker.decoder.nowPos64)/k,c?c(f):"undefined"!=typeof h&&G(f,h)),da(d,0),0;g&&(c?c(1):"undefined"!=typeof h&&G(1,h));a=Ra(qa(e.d.output));b?b(a):"undefined"!=typeof h&&postMessage({action:2,cbn:h,result:a})}var e={},f,h,g,k;"function"!=
typeof b&&(h=b,b=c=0);e.d=Pa({},a);k=ca(e.d.length_0);g=-1<k;c?c(g?0:-1):"undefined"!=typeof h&&G(g?0:-1,h);da(d,0)}}}();this.LZMA=this.LZMA_WORKER=LZMA;
