var MO=new function(){this.version="0.2.0";return this};MO.ELogger=new function(){this.Debug=0;this.Info=1;this.Warn=2;this.Error=3;this.Fatal=4;return this};MO.EProcess=new function(){this.Release=0;this.Process=1;this.Debug=2;return this};MO.EScope=new function(){this.Local=1;this.Session=2;this.Global=3;return this};
with(MO)MO.RRuntime=function(){this.processCd=EProcess.Release;this.isDebug=RRuntime_isDebug;this.isProcess=RRuntime_isProcess;this.isRelease=RRuntime_isRelease;this.setProcessCd=RRuntime_setProcessCd;this.empty=RRuntime_empty;this.nvl=RRuntime_nvl;this.subString=RRuntime_subString;this.className=RRuntime_className;return this},MO.RRuntime_isDebug=function(){return this._processCd==EProcess.Debug},MO.RRuntime_isProcess=function(){return this._processCd==EProcess.Process},MO.RRuntime_isRelease=function(){return this._processCd==
EProcess.Release},MO.RRuntime_setProcessCd=function(a){this._processCd=a},MO.RRuntime_empty=function(){},MO.RRuntime_nvl=function(a,b){return null!=a?a:b},MO.RRuntime_subString=function(a,b,d){if(null==a)return a;var e=0;if(null!=b){var f=a.indexOf(b);-1!=f&&(e=f+b.length)}b=a.length;null!=d&&(f=a.indexOf(d,length),-1!=f&&(b=f));return e>=b?"":a.substring(e,b)},MO.RRuntime_className=function(a){return a&&("function"==typeof a||(a=a.constructor))?this.subString(a.toString(),"function ","("):null},
MO.Runtime=new RRuntime;
with(MO)MO.TAttributes=function(){TDictionary.call(this);this.join=TAttributes_join;this.split=TAttributes_split;this.pack=TAttributes_pack;this.unpack=TAttributes_unpack;this.dump=TAttributes_dump;return this},MO.TAttributes_join=function(a,b){var d=new TString;a||(a="=");b||(b=",");for(var e=this._count,f=0;f<e;f++)0<f&&d.append(b),d.append(this.names[f]),d.append(a),d.append(this.values[f]);return d.flush()},MO.TAttributes_split=function(a,b,d){a=a.split(d);d=a.length;for(var e=0;e<d;e++){var f=
a[e];if(f.length){var g=f.split(b);2==g.length?this.set(RString.trim(g[0]),RString.trim(g[1])):this.set(RString.trim(f),"")}}},MO.TAttributes_pack=function(){for(var a=new TString,b=this._count,d=0;d<b;d++){var e=this.names[d],f=this.values[d],g=e.length;a.append(g.toString().length,g,e);null!=f?(f+="",e=f.length,a.append(e.toString().length,e,f)):a.append("0")}return a.flush()},MO.TAttributes_unpack=function(a){for(var b=this.count=0,d=a.length;b<d;){var e=parseInt(a.substr(b++,1)),f=parseInt(a.substr(b,
e)),g=a.substr(b+e,f),b=b+(e+f),e=parseInt(a.substr(b++,1)),h=null;0<e&&(f=parseInt(a.substr(b,e)),h=a.substr(b+e,f),b+=e+f);this.set(g,h)}},MO.TAttributes_dump=function(){var a=new TString,b=this._count;a.append(RRuntime.className(o)," : ",b);if(0<b){a.append(" (");for(var d=0;d<b;d++)0<d&&a.append(", "),a.append(this._names[d],"=",this._values[d]);a.append(")")}return a.flush()};
with(MO)MO.TDictionary=function(){TMap.call(this);this.dump=TDictionary_dump;return this},MO.TDictionary_dump=function(){var a=new TString,b=this._count;a.append(RRuntime.className(o),": ",b);if(0<b){a.append(" {\n");for(var d=0;d<b;d++)a.append("   ",this._names[d],"=[",this._values[d],"]\n");a.append("}")}return a.flush()};
with(MO)MO.TMap=function(){this._count=0;this._table={};this._names=[];this._values=[];this.isEmpty=TMap_isEmpty;this.count=TMap_count;this.contains=TMap_contains;this.containsValue=TMap_containsValue;this.indexOf=TMap_indexOf;this.indexOfValue=TMap_indexOfValue;this.first=TMap_first;this.last=TMap_last;this.nameAt=TMap_nameAt;this.name=TMap_name;this.at=this.valueAt=TMap_valueAt;this.value=TMap_value;this.setValueAt=TMap_setValueAt;this.setValue=TMap_setValue;this.get=TMap_get;this.set=TMap_set;
this.assign=TMap_assign;this.append=TMap_append;this.insert=TMap_insert;this.remove=TMap_remove;this.removeName=TMap_removeName;this.removeValue=TMap_removeValue;this.rebuild=TMap_rebuild;this.clear=TMap_clear;this.toString=TMap_toString;this.dispose=TMap_dispose;this.dump=TMap_dump;return this},MO.TMap_isEmpty=function(){return 0==this._count},MO.TMap_count=function(){return this._count},MO.TMap_contains=function(a){return null!=a&&null!=this._table[a.toString().toLowerCase()]?!0:!1},MO.TMap_containsValue=
function(a){return-1!=this.indexOfValue(a)},MO.TMap_indexOf=function(a){return null!=a&&(a=this._table[a.toString().toLowerCase()],null!=a)?a:-1},MO.TMap_indexOfValue=function(a){for(var b=this._count,d=0;d<b;d++)if(this._values[n]==a)return n;return-1},MO.TMap_first=function(){return 0<this._count?this._values[0]:null},MO.TMap_last=function(){return 0<this._count?this._values[this._count-1]:null},MO.TMap_nameAt=function(a){return this._names[a]},MO.TMap_name=function(a){return 0<=a&&a<this._count?
this._names[a]:null},MO.TMap_valueAt=function(a){return this._values[a]},MO.TMap_value=function(a){return 0<=a&&a<this._count?this._values[a]:null},MO.TMap_setValueAt=function(a,b){this._values[a]=b},MO.TMap_setValue=function(a,b){0<=a&&a<this._count&&(this._values[a]=b)},MO.TMap_get=function(a,b){if(null!=a){var d=this._table[a.toString().toLowerCase()];if(null!=d)return this._values[d]}return b},MO.TMap_set=function(a,b){if(null!=a){var d=a.toString().toLowerCase(),e=this._table[d];if(null==e||
e>=this._count)e=this._count++,this._names[e]=a,this._table[d]=e;this._values[e]=b}},MO.TMap_assign=function(a){this.clear();this.append(a)},MO.TMap_append=function(a){if(a)for(var b=a.count(),d=0;d<b;d++){var e=a.nameAt(d),f=a.valueAt(d);this.set(e,f)}},MO.TMap_insert=function(a,b,d){var e=this._count;if(0<=a&&a<=e){for(;e>a;e--)this._names[e]=this._names[e-1],this._values[e]=this._values[e-1];this._names[a]=b;this._values[a]=d;this._count++;this.rebuild()}},MO.TMap_remove=function(a){var b=null,
d=this._count;if(0<=a&&a<d){for(b=this._values[a];a<d;a++)this._names[a]=this._names[a+1],this._values[a]=this._values[a+1];this._count--;this.rebuild()}return b},MO.TMap_removeName=function(a){a=this.indexOf(a);return-1!=a?this.remove(a):null},MO.TMap_removeValue=function(a){for(var b=0,d=this._count,e=0;e<d;e++){var f=this._values[e];f!=a&&(b!=e&&(this._names[b]=this._names[e],this._values[b]=f),b++)}this._count=b;this.rebuild()},MO.TMap_rebuild=function(){var a=this._table,b;for(b in a)delete a[b];
b=this._count;for(var d=0;d<b;d++){var e=this._names[d].toLowerCase();a[e]=d}},MO.TMap_clear=function(){this._count=0;for(var a in this._table)delete this._table[a]},MO.TMap_toString=function(){return this.dump().toString()},MO.TMap_dispose=function(){this._count=0;var a=this._table;if(a){for(var b in a)a[b]=null;this._table=null}if(b=this._names){for(a=b.length-1;0<=a;a--)b[a]=null;this._names=null}if(b=this._values){for(a=b.length-1;0<=a;a--)b[a]=null;this._values=null}},MO.TMap_dump=function(){var a=
new TString,b=this._count;a.appendLine(RRuntime.className(o),": ",b);if(0<b){a.append(" {");for(var d=0;d<b;d++)a.appendLine(this._names[d],"=[",this._values[d],"]");a.append("}")}return a.flush()};
with(MO)MO.TObjects=function(){this._count=0;this._items=[];this.isEmpty=TObjects_isEmpty;this.count=TObjects_count;this.items=TObjects_items;this.contains=TObjects_contains;this.indexOf=TObjects_indexOf;this.first=TObjects_first;this.last=TObjects_last;this.at=this.getAt=TObjects_getAt;this.get=TObjects_get;this.setAt=TObjects_setAt;this.set=TObjects_set;this.assign=TObjects_assign;this.append=TObjects_append;this.insert=TObjects_insert;this.shift=TObjects_shift;this.unshift=TObjects_unshift;this.pop=
TObjects_pop;this.push=TObjects_push;this.pushUnique=TObjects_pushUnique;this.swap=TObjects_swap;this.sort=TObjects_sort;this.erase=TObjects_erase;this.remove=TObjects_remove;this.clear=TObjects_clear;this.dispose=TObjects_dispose;this.dump=TObjects_dump;return this},MO.TObjects_isEmpty=function(){return 0==this._count},MO.TObjects_count=function(){return this._count},MO.TObjects_items=function(){return this._items},MO.TObjects_contains=function(a){return-1!=this.indexOf(a)},MO.TObjects_indexOf=function(a){for(var b=
this._count,d=this._items,e=0;e<b;e++)if(d[e]==a)return e;return-1},MO.TObjects_first=function(){return this._count?this._items[0]:null},MO.TObjects_last=function(){return this._count?this._items[this._count-1]:null},MO.TObjects_getAt=function(a){return this._items[a]},MO.TObjects_get=function(a){return 0<=a&&a<this._count?this._items[a]:null},MO.TObjects_setAt=function(a,b){this._items[a]=b},MO.TObjects_set=function(a,b){0<=a&&a<this._count&&(this._items[a]=v)},MO.TObjects_assign=function(a){for(var b=
this._count=a._count,d=0;d<b;d++)this._items[d]=a._items[d]},MO.TObjects_append=function(a){for(var b=a._count,d=0;d<b;d++)this.push(a.at(d))},MO.TObjects_insert=function(a,b){var d=this._count;if(0<=a&&a<=d){for(;d>a;d--)this._items[d]=this._items[d-1];this._items[a]=b}},MO.TObjects_shift=function(){return this.erase(0)},MO.TObjects_unshift=function(a){return this.insert(0,a)},MO.TObjects_pop=function(){if(this._count)return this._items[--this._count]},MO.TObjects_push=function(a){var b=this._count++;
this._items[b]=a;return b},MO.TObjects_pushUnique=function(a){for(var b=this._count-1;0<=b;b--)if(this._items[b]==v)return b;b=this._count++;this._items[b]=a;return b},MO.TObjects_swap=function(a,b){if(0<=a&&a<this._count&&0<=b&&b<this._count&&a!=b){var d=this._items,e=d[a];d[a]=d[b];d[b]=e}},MO.TObjects_sort=function(a){var b=this._items;b.length!=this._count&&(b.length=this._count);b.sort(a)},MO.TObjects_erase=function(a){var b=null;if(0<=a&&a<this._count){for(var b=this._items[a],d=--this._count,
e=this._items;a<d;a++)e[a]=e[a+1];e[d]=null}return b},MO.TObjects_remove=function(a){var b=this._count;if(b){for(var d=0,e=this._items,f=d;f<b;f++)e[f]!=a&&(e[d++]=e[f]);for(f=d;f<b;f++)e[f]=null;this._count=d}return a},MO.TObjects_clear=function(){this._count=0},MO.TObjects_dispose=function(){for(var a in this._items)this._items[a]=null;this._count=0;this._items=null},MO.TObjects_dump=function(){var a=this._count,b=new TString;b.append(RRuntime.className(o),":",a);if(a)for(var d=0;d<a;d++)b.append(" [",
this._items[d],"]");return b.flush()};
with(MO)MO.TString=function(){this._count=0;this._memory=[];this.isEmpty=TString_isEmpty;this.assign=TString_assign;this.append=TString_append;this.appendIf=TString_appendIf;this.appendArray=TString_appendArray;this.appendLine=TString_appendLine;this.appendRepeat=TString_appendRepeat;this.push=TString_push;this.clear=TString_clear;this.toString=TString_toString;this.flush=TString_flush;this.dispose=TString_dispose;this.dump=TString_dump;return this},MO.TString_isEmpty=function(){return 0==this._count},
MO.TString_assign=function(){this.clear();this.appendArray(arguments,0,arguments.length)},MO.TString_append=function(a){this.appendArray(arguments,0,arguments.length)},MO.TString_appendIf=function(a){a&&this.appendArray(arguments,1,arguments.length-1)},MO.TString_appendArray=function(a,b,d){for(var e=0;e<d;e++){var f=a[b++];null!=f&&(this._memory[this._count++]=f)}},MO.TString_appendRepeat=function(a,b){for(var d=0;d<b;d++)this._memory[this._count++]=a},MO.TString_appendLine=function(){this.appendArray(arguments,
0,arguments.length);this._memory[this._count++]="\r\n"},MO.TString_push=function(){this.appendArray(arguments,0,arguments.length)},MO.TString_clear=function(){this._count=0},MO.TString_toString=function(){var a=this._memory;a.length!=this._count&&(a=a.slice(0,this._count));return a.join("")},MO.TString_flush=function(){var a=this.toString();this.dispose();return a},MO.TString_dispose=function(){this._count=0;var a=this._memory;if(a){for(var b=a.length-1;0<=b;b--)a[b]=null;this._memory=null}},MO.TString_dump=
function(){var a=this.toString();return RRuntime.className(o)+":"+a.length+"["+a+"]"};
with(MO)MO.RAssert=function(){this.isTrue=RAssert_isTrue;this.isFalse=RAssert_isFalse;this.debugEnd=this.debug=this.debugBegin=MO.Runtime.empty;this.debugTrue=RAssert_debugTrue;this.debugFalse=RAssert_debugFalse;this.debugNull=RAssert_debugNull;this.debugNotNull=RAssert_debugNotNull;this.debugEmpty=RAssert_debugEmpty;this.debugNotEmpty=RAssert_debugNotEmpty;return this},MO.RAssert_isTrue=function(a){if(!a)throw Error("Assert ture failure.");},MO.RAssert_isFalse=function(a){if(a)throw Error("Assert false failure.");
},MO.RAssert_debugTrue=function(a){if(!a)throw Error("Assert true failure.");},MO.RAssert_debugFalse=function(a){if(a)throw Error("Assert false failure.");},MO.RAssert_debugNull=function(a){if(null!=a)throw Error("Assert null failure.");},MO.RAssert_debugNotNull=function(a){if(null==a)throw Error("Assert not null failure.");},MO.RAssert_debugEmpty=function(a){if(null!=a)throw Error("Assert empty failure.");},MO.RAssert_debugNotEmpty=function(a){if(null==a)throw Error("Assert not empty failure.");
};
with(MO)MO.RMemory=function(){this._entryUnused=null;this._pools={};this.entryAlloc=RMemory_entryAlloc;this.entryFree=RMemory_entryFree;this.alloc=RMemory_alloc;this.free=RMemory_free;this.refresh=RMemory_refresh;return this},MO.RMemory_entryAlloc=function(){var a=null,b=this._entryUnused;b?(a=b,this._entryUnused=b.next):a=new SMemoryPoolEntry;return a},MO.RMemory_entryFree=function(a){RAssert.debugNotNull(a);a.next=this._entryUnused;this._entryUnused=a},MO.RMemory_alloc=function(a){RAssert.debugNotNull(a);var b=
RRuntime.className(a),d=this._pools,e=d[b];e||(e=new TMemoryPool,e._constructor=a,d[b]=e);return e.alloc()},MO.RMemory_free=function(a){RAssert.debugNotNull(a);var b=a.__pool;RAssert.debugNotNull(b);b.free(a)},MO.RMemory_refresh=function(){CollectGarbage()},MO.Memory=new RMemory;
with(MO)MO.SMemoryPoolEntry=function(){this.value=this.next=null;this.dispose=SMemoryPoolEntry_dispose;return this},MO.SMemoryPoolEntry_dispose=function(){var a=this.value;a&&(a.__pool=null,a.dispose());this.value=this.next=null};
with(MO)MO.TMemoryPool=function(){this._unused=this._constructor=null;this._freeCount=this._allocCount=this._createCount=0;this.alloc=TMemoryPool_alloc;this.free=TMemoryPool_free;this.dispose=TMemoryPool_dispose;this.dump=TMemoryPool_dump;return this},MO.TMemoryPool_alloc=function(){var a=null,b=this._unused;b?(a=b.value,this._unused=b.next,RMemory.entryFree(b)):(a=new this._constructor,a.__pool=o,this._createCount++);this._allocCount++;return a},MO.TMemoryPool_free=function(a){RAssert.debugNotNull(a);
var b=RMemory.entryAlloc();b.value=a;b.next=this._unused;this._unused=b;this._freeCount++},MO.TMemoryPool_dispose=function(){for(var a=this._unused;a;){var b=a,a=b.next;b.dispose();RMemory.entryFree(b)}},MO.TMemoryPool_dump=function(){var a=new TString;a.append("Pool:");a.append("create=",this._createCount);a.append(", alloc=",this._allocCount);a.append(", free=",this._freeCount);return a.flush()};
with(MO)MO.SLooperEntry=function(){this.value=this.next=this.prior=null;this.dispose=SLooperEntry_dispose;return this},MO.SLooperEntry_dispose=function(){this.value=this.next=this.prior=null};
with(MO)MO.TLooper=function(){this._recordCount=this._count=0;this._current=null;this.innerPush=TLooper_innerPush;this.innerRemove=TLooper_innerRemove;this.innerRemoveCurrent=TLooper_innerRemoveCurrent;this.innerRemoveValue=TLooper_innerRemoveValue;this.isEmpty=TLooper_isEmpty;this.count=TLooper_count;this.record=TLooper_record;this.unrecord=TLooper_unrecord;this.contains=TLooper_contains;this.current=TLooper_current;this.next=TLooper_next;this.push=TLooper_push;this.pushUnique=TLooper_pushUnique;
this.removeCurrent=TLooper_removeCurrent;this.remove=TLooper_remove;this.clear=TLooper_clear;this.dispose=TLooper_dispose;this.dump=TLooper_dump;return this},MO.TLooper_innerPush=function(a){var b=this._current;if(b){var d=b.prior;a.prior=d;a.next=b;d.next=a;b.prior=a}else a.prior=a,this._current=a.next=a;this._count++},MO.TLooper_innerRemove=function(a){var b=a.prior,d=a.next;b.next=d;d.prior=b;this._count--;this._current=0<this._count?d:null;RMemory.free(a)},MO.TLooper_innerRemoveCurrent=function(){var a=
null;if(0<this._count){var b=this._current,a=b.value;this.innerRemove(b)}return a},MO.TLooper_innerRemoveValue=function(a){if(0<this._count)if(this._current.value==a)this.innerRemoveCurrent();else for(var b=this._current,d=b.next;d!=b;){if(d.value==a){this.innerRemove(d);this._current=b;break}d=d.next}},MO.TLooper_isEmpty=function(){return 0==this._count},MO.TLooper_count=function(){return this._count},MO.TLooper_record=function(){this._recordCount=this._count},MO.TLooper_unrecord=function(a){this._recordCount=
-1},MO.TLooper_contains=function(a){if(this._current)for(var b=this._current,d=this._count,e=0;e<d;e++){if(b.value==a)return!0;b=b.next}return!1},MO.TLooper_current=function(){var a=this._current;return a?a.value:null},MO.TLooper_next=function(){this._current&&(this._current=this._current.next);var a=this._recordCount;if(0<a)this._recordCount--;else if(0==a)return null;return this._current?this._current.value:null},MO.TLooper_push=function(a){var b=RMemory.alloc(SLooperEntry);b.value=a;this.innerPush(b)},
MO.TLooper_pushUnique=function(a){this.contains(a)||this.push(a)},MO.TLooper_removeCurrent=function(){return this.innerRemoveCurrent()},MO.TLooper_remove=function(a){this.innerRemoveValue(a)},MO.TLooper_clear=function(){var a=this._current;if(a)for(a.prior.next=null;a;)a=a.next,MO.Memory.free(a);this._count=0;this._current=null},MO.TLooper_dispose=function(){this.clear()},MO.TLooper_dump=function(){var a=this._count,b=new TString;b.append(RClass.name(this),": ",a);if(0<a)for(var d=this._current,e=
0;e<a;e++)b.append(" [",d.value,"]"),d=d.next;return b.flush()};
with(MO)MO.RGlobal=function(){this._instances=new TDictionary;this.get=RGlobal_get;this.set=RGlobal_set;this.globalGet=RGlobal_globalGet;this.globalSet=RGlobal_globalSet;return this},MO.RGlobal_get=function(a){return this._instances.get(a)},MO.RGlobal_set=function(a,b){this._instances.set(a,b)},MO.RGlobal_globalGet=function(a){var b=null;return b=top.MO.Global?top.MO.Global.get(a):this._instances.get(a)},MO.RGlobal_globalSet=function(a,b){top.MO.Global?top.MO.Global.set(a,b):this._instances.set(a,
b)},MO.Global=new RGlobal;with(MO)MO.AAnnotation=function(a){this._annotationCd=null;this._duplicate=this._inherit=!1;this._name=a;this.annotationCd=AAnnotation_annotationCd;this.name=AAnnotation_name;this.code=AAnnotation_code;this.value=AAnnotation_value;return this},MO.AAnnotation_annotationCd=function(){return this._annotationCd},MO.AAnnotation_name=function(){return this._name},MO.AAnnotation_code=function(){return this._name},MO.AAnnotation_value=function(){return null};
with(MO)MO.AEnum=function(a,b){this.inherit=!0;this.annotation=EAnnotation.Enum;this.name=a;this.linker=b;return this};with(MO)MO.ALinker=function(a,b){this.inherit=!0;this.annotation=EAnnotation.Linker;this.name=a;this.linker=b;return this};
with(MO)MO.AProperty=function(a,b){AAnnotation.call(this,a);this._inherit=!0;this._annotationCd=EAnnotation.Property;this._linker=null;this._force=!1;this.code=AProperty_code;this.build=AProperty_build;this.load=AProperty_load;this.save=AProperty_save;this.toString=AProperty_toString;var d=null;null==b?(d=RString.startsWith(n,"_")?n.substring(1):n,d=RString.toUnderline(d)):d=b;this._linker=d;return this},MO.AProperty_code=function(){return this._linker},MO.AProperty_build=function(){},MO.AProperty_load=
function(a,b){a[this._name]=b.get(this._linker)},MO.AProperty_save=function(a,b){b.set(this._linker,a[this._name])},MO.AProperty_toString=function(){return"<"+this._annotationCd+",linker="+this._linker+">"};MO.EAnnotation=new function(){this.Property="property";this.Event="enum";this.Event="event";this.Linker="linker";this.Style="style";this.StyleIcon="icon";return this};MO.EBoolean=new function(){this.True="Y";this.False="N";return this};
MO.ECharCase=new function(){this.Upper="U";this.Lower="L";this.Word="W";return this};MO.EDataType=new function(){this.Unknown=0;this.Int8=1;this.Int16=2;this.Int32=3;this.Int64=4;this.Uint8=5;this.Uint16=6;this.Uint32=7;this.Uint64=8;this.Float16=9;this.Float32=10;this.Float64=11;this.String=12;return this};MO.EEndian=new function(){this.Big=0;this.Little=1;return this};MO.ENodeType=new function(){this.Node=1;this.Text=3;this.Data=4;return this};
MO.ENumber=new function(){this.Integer="I";this.PositiveInteger="PI";this.NegativeInteger="NI";this.Float="F";this.PositiveFloat="PF";this.NegativeFloat="NF";return this};MO.ERegExp=new function(){this.I=/^-?[1-9]\d*|0$/;this.PI=/^[1-9]\d*$/;this.NI=/^-[1-9]\d*$/;this.F=/^-?([1-9]\d*\.\d*|0\.\d*[1-9]\d*|0?\.0+|0)$/;this.PF=/^[1-9]\d*\.\d*|0\.\d*[1-9]\d*$/;this.NF=/^-([1-9]\d*\.\d*|0\.\d*[1-9]\d*)$/;this.U=/[1-9]{1}[0-9]/;this.E=/^\w{1,}[@]{1}[a-zA-Z]{1,}[.]{1}[a-zA-Z]{1,}$/;return this};
MO.EResult=new function(){this.Success=0;this.Continue=1;this.Skip=2;this.Finish=3;this.Failure=-1;this.Cancel=-2;return this};with(MO)MO.MInstance=function(a){a=RClass.inherits(this,a);a.__free=!1;a.instanceCreate=RMethod.empty;a.instanceAlloc=RMethod.empty;a.instanceFree=RMethod.empty;a.instanceRelease=RMethod.empty;return a};with(MO)MO.MInvoke=function(a){a=RClass.inherits(this,a);a.invoke=RMethod.virtual(a,"invoke");return a};
with(MO)MO.MPoolAble=function(a){a=RClass.inherits(this,a);a._poolCode=null;a.poolCode=MPoolAble_poolCode;a.setPoolCode=MPoolAble_setPoolCode;return a},MO.MPoolAble_poolCode=function(){return this._code},MO.MPoolAble_setPoolCode=function(a){this._poolCode=a};with(MO)MO.SArguments=function(){this.owner=null;return this};with(MO)MO.SEnumItem=function(){this.name=null;this.value=0;return this};
with(MO)MO.FConsole=function(a){a=RClass.inherits(this,a,FObject);a._scopeCd=EScope.Global;a.scopeCd=FConsole_scopeCd;return a},MO.FConsole_scopeCd=function(){return this._scopeCd};
with(MO)MO.FObjectPool=function(a){a||(a=this);a.__class=null;a.__hash=0;a.__dispose=!1;a.construct=FObject_construct;a.hashCode=FObject_hashCode;a.toString=FObject_toString;a.dispose=FObject_dispose;a.innerDump=FObject_innerDump;a.dump=FObject_dump;return a},MO.FObject_construct=function(){this.__dispose=!1},MO.FObject_hashCode=function(){var a=this.__hash;a||(a=this.__hash=RObject.nextId());return a},MO.FObject_toString=function(){return RClass.dump(this)},MO.FObject_dispose=function(){RObject.free(this);
this.__dispose=!0},MO.FObject_innerDump=function(a,b){a.append(RClass.dump(this))},MO.FObject_dump=function(){var a=new TString;this.innerDump(a,0);return a.flush()};
with(MO)MO.FObjectPool=function(a){a=RClass.inherits(this,a,FObject);a._items=null;a._frees=null;a._allocCount=0;a._freeCount=0;a.construct=FObjectPool_construct;a.hasFree=FObjectPool_hasFree;a.alloc=FObjectPool_alloc;a.free=FObjectPool_free;a.push=FObjectPool_push;a.dispose=FObjectPool_dispose;a.innerDump=FObjectPool_innerDump;return a},MO.FObjectPool_construct=function(){this.__base.FObject.construct.call(this);this._items=new TObjects;this._frees=new TObjects},MO.FObjectPool_hasFree=function(){return!this._frees.isEmpty()},
MO.FObjectPool_alloc=function(){var a=null;this._frees.isEmpty()||(a=this._frees.pop());this._allocCount++;return a},MO.FObjectPool_free=function(a){this._frees.push(a);this._freeCount++},MO.FObjectPool_push=function(a){this._items.push(a);this._frees.push(a)},MO.FObjectPool_dispose=function(){this._items=RObject.dispose(this._items);this._frees=RObject.dispose(this._frees);this.__base.FObject.dispose.call(this)},MO.FObjectPool_innerDump=function(a,b){a.append("Pool:");a.append("total=",this._items.count());
a.append(", free=",this._frees.count());a.append(", alloc_count=",this._allocCount);a.append(", free_count=",this._freeCount)};
with(MO)MO.FObjectPools=function(a){a=RClass.inherits(this,a,FObject);a._pools=null;a.construct=FObjectPools_construct;a.pool=FObjectPools_pool;a.alloc=FObjectPools_alloc;a.free=FObjectPools_free;a.dispose=FObjectPools_dispose;return a},MO.FObjectPools_construct=function(){this.__base.FObject.construct.call(this);this._pools=new TDictionary},MO.FObjectPools_pool=function(a){var b=this._pools.get(a);b||(b=RClass.create(FObjectPool),this._pools.set(a,b));return b},MO.FObjectPools_alloc=function(a){return this.pool(a).alloc()},
MO.FObjectPools_free=function(a,b){return this.pool(a).free(b)},MO.FObjectPools_push=function(a,b){return this.pool(a).push(b)},MO.FObjectPools_dispose=function(){for(var a=this._pools,b=a.count(),d=0;d<b;d++)a.valueAt(d).dispose();a.dispose();this.__base.FObject.dispose.call(this)};
with(MO)MO.FTimer=function(a){a=RClass.inherits(this,a,FObject);a._count=0;a._startTime=0;a._beginTime=0;a._endTime=0;a._stopTime=0;a._span=0;a._spanSecond=0;a.setup=FTimer_setup;a.current=FTimer_current;a.span=FTimer_span;a.spanSecond=FTimer_spanSecond;a.rate=FTimer_rate;a.update=FTimer_update;return a},MO.FTimer_setup=function(){var a=(new Date).getTime();this._endTime=this._beginTime=this._startTime=a},MO.FTimer_current=function(){return this._lastTime},MO.FTimer_span=function(){return this._span},
MO.FTimer_spanSecond=function(){return this._spanSecond},MO.FTimer_rate=function(){return 0==this._count?0:parseInt(1E3*this._count/(this._lastTime-this._startTime))},MO.FTimer_update=function(){this._count++;var a=this._beginTime=this._endTime;this._spanSecond=(this._span=(this._endTime=(new Date).getTime())-a)/1E3};
with(MO)MO.RArray=function(){this.array1=Array(1);this.array2=Array(2);this.array3=Array(3);this.array4=Array(4);this.array9=Array(9);this.array12=Array(12);this.array16=Array(16);this.equals=RArray_equals;this.count=RArray_count;this.contains=RArray_contains;this.find=RArray_find;this.search=RArray_search;this.reverse=RArray_reverse;this.copy=RArray_copy;this.move=RArray_move;this.remove=RArray_remove;this.sortPartition=RArray_sortPartition;this.sortArray=RArray_sortArray;this.sort=RArray_sort;this.nameMaxLength=
RArray_nameMaxLength;return this},MO.RArray_equals=function(a,b){if(a&&b&&a.length==b.length){for(var d=a.length,e=0;e<d;e++)if(a[e]!=b[e])return!1;return!0}return!1},MO.RArray_count=function(a){for(var b in a)b++;return 0},MO.RArray_contains=function(a,b){for(var d=a.length,e=0;e<d;e++)if(a[e]==b)return!0;return!1},MO.RArray_find=function(a,b){for(var d=a.length,e=0;e<d;e++)if(a[e]==b)return e;return-1},MO.RArray_search=function(a,b){for(var d in a)if(a[d]==b)return d;return null},MO.RArray_reverse=
function(a,b,d){for(var e=d+1-b>>1,f=0;f<e;f++){var g=a[b+f];a[b+f]=a[d-f];a[d-f]=g}},MO.RArray_copy=function(a,b){for(var d in a)b[d]=a[d]},MO.RArray_move=function(a,b,d,e){if(b>e)for(var f=0;f<d;f++)a[e-f]=a[b+f];else if(b<e)for(f=0;f<d;f++)a[e+d-f-1]=a[b+d-f-1]},MO.RArray_remove=function(a,b){return a.slice(0,b).concat(a.slice(b+1))},MO.RArray_sortPartition=function(a,b,d){var e=b;d+=1;for(var f=a[e];;){for(;a[++e]<f;);for(;a[--d]>f;);if(e>d)break;var g=a[e];a[e]=a[d];a[d]=g}a[b]=a[d];a[d]=f;return d},
MO.RArray_sortArray=function(a,b,d){if(b<d){var e=this.sortPartition(a,b,d);this.sortArray(a,b,e-1);this.sortArray(a,e+1,d)}},MO.RArray_sort=function(a,b){var d=a.length-1;this.sortArray(a,0,d);b&&this.reverse(a,0,d);return a},MO.RArray_nameMaxLength=function(a){for(var b in a)a=b.length,a>b&&(b=a);return 0},MO.RArray=new RArray;
with(MO)MO.RBoolean=function(){this.format=RBoolean_format;this.parse=RBoolean_parse;this.toString=RBoolean_toString;return this},MO.RBoolean_format=function(a){return a?EBoolean.True:EBoolean.False},MO.RBoolean_parse=function(a){if(null!=a){if(a.constructor==Boolean)return a;if(a.constructor==String)return a==EBoolean.True;if(a.constructor==Number)return 0<a;throw new TError(this,"Unknown type.");}return!1},MO.RBoolean_toString=function(a,b,d){null==b&&(b=EBoolean.True);null==d&&(d=EBoolean.False);
return a?b:d},MO.Boolean=new RBoolean;with(MO)MO.RByte=function(){this.copy=RByte_copy;return this},MO.RByte_copy=function(a,b,d,e,f){for(var g=0;g<f;g++)a[b++]=d[e++]},MO.Byte=new RByte;with(MO)MO.RChar=function(){this.parse=RChar_parse;this.toString=RChar_toString;return this},MO.RChar_parse=function(a){return String.fromCharCode(a)},MO.RChar_toString=function(a){return a},MO.Char=new RChar;
with(MO)MO.RClass=function(){this.codes=[];this.classes={};this.isBase=RClass_isBase;this.isBaseName=RClass_isBaseName;this.isBaseDataName=RClass_isBaseDataName;this.isBaseType=RClass_isBaseType;this.isBaseDataType=RClass_isBaseDataType;this.isName=RClass_isName;this.isClass=RClass_isClass;this.typeOf=RClass_typeOf;this.safeTypeOf=RClass_safeTypeOf;this.checkClass=RClass_checkClass;this.code=RClass_code;this.name=RClass_name;this.inherits=RClass_inherits;this.forName=RClass_forName;this.find=RClass_find;
this.register=RClass_register;this.createBase=RClass_createBase;this.createClass=RClass_createClass;this.create=RClass_create;this.createByName=RClass_createByName;this.innerCopy=RClass_innerCopy;this.build=RClass_build;this.free=RClass_free;this.dump=RClass_dump;return this},MO.RClass_isBase=function(a){return null!=a?RClass.isBaseName(typeof a):!1},MO.RClass_isBaseName=function(a){return null==a||"boolean"!=a&&"number"!=a&&"date"!=a&&"string"!=a&&"function"!=a?!1:!0},MO.RClass_isBaseDataName=function(a){return null==
a||"boolean"!=a&&"number"!=a&&"date"!=a&&"string"!=a?!1:!0},MO.RClass_isBaseType=function(a){return null==a||a!=Boolean&&a!=Number&&a!=Date&&a!=String&&a!=Function?!1:!0},MO.RClass_isBaseDataType=function(a){return null==a||a!=Boolean&&a!=Number&&a!=Date&&a!=String?!1:!0},MO.RClass_isName=function(a,b){return this.name(a)==b},MO.RClass_isClass=function(a,b){if(a&&b){var d=this.name(b);return a.__base?null!=a.__base[d]:this.name(a)==d}return!1},MO.RClass_typeOf=function(a){return a&&a.constructor?
RString.mid(a.constructor.toString(),"function ","("):"Null"},MO.RClass_safeTypeOf=function(a,b){if(null==a)return"Null";try{var d=a.constructor;if(d==Boolean)return"Boolean";if(d==Number)return"Number";if(d==String)return"String";if(d==Function||d.constructor==Function)return RString.mid(d.toString(),"function ","(");if(a.__class)return a.__class.name;if(a.tagName)return"Html";for(var e in a)return"Object"}catch(f){}return"Unknown"},MO.RClass_checkClass=function(a,b){if(!this.isClass(a,b))throw Error("Invalid class "+
o.name(o)+"<>"+o.name(b));},MO.RClass_code=function(a){for(var b=this.codes,d=b.length,e=0;e<d;e++)if(b[e]==a)return e;b[d]=a;return d},MO.RClass_name=function(a){if(a){if(a.__name)return a.__name;if(a.__class)return a.__class.name;if("function"==typeof a)return RMethod.name(a);if(a=a.constructor)return RString.mid(a.toString(),"function ","(")}return null},MO.RClass_inherits=function(a,b){var d=RRuntime.nvl(b,a);d.__inherits=[];for(var e=arguments,f=e.length,g=2;g<f;g++)d.__inherits.push(RMethod.name(e[g]));
return d},MO.RClass_forName=function(a){var b=null;null!=a&&(b=this.classes[a],b||(b=this.createClass(a),this.build(b)));return b},MO.RClass_find=function(a){var b=null;null!=a&&(a.__class?b=a.__class.name:a.constructor==Function?b=RMethod.name(a):a.constructor!=String&&RLogger.fatal(this,null,"Find class failure. (value={1})",a));return this.classes[b]},MO.RClass_register=function(a,b,d){a=RMethod.name(a.constructor);this.classes[a].register(b);a=b.value();return null!=a?a:d},MO.RClass_createBase=
function(a){return a?eval("function "+a+"(){return this;} new "+a+"();"):null},MO.RClass_createClass=function(a){var b=this.classes[a]=new TClass;b.name=a;b.base=this.createBase(a);b.clazz=new b.base.constructor;eval(a)(b.clazz);return b},MO.RClass_create=function(a){var b=typeof a;"function"==b?a=RMethod.name(a):"string"!=b&&RLogger.fatal(this,null,"Param is invlid (name={1})",a);return this.createByName(a)},MO.RClass_createByName=function(a){(a=this.forName(a))||RLogger.fatal(this,null,"Cant find class. (name={1})",
a);return a.newInstance()},MO.RClass_innerCopy=function(a,b){if(null!=a&&null!=b)for(var d in a){var e=a[d];if(null!=e){var f=typeof e;if("function"==f){f=b[d];null==f?b[d]=e:RMethod.isVirtual(f)?b[d]=e:!RMethod.isVirtual(e)&&RMethod.isEmpty(f)?b[d]=e:RMethod.isVirtual(e)||RMethod.isEmpty(e)||(b[d]=e);continue}else if(!RClass.isBaseName(f)){null==b[d]&&(b[d]=new e.constructor);this.innerCopy(e,b[d]);continue}}b[d]=e}},MO.RClass_build=function(a){var b=a.clazz.__inherits;if(b&&b.constructor==Array)for(var d=
!1,e=b.length,f=0;f<e;f++){var g=b[f];RString.startsWith(g,"F")&&(d&&RLogger.fatal(this,null,"Parent class is too many. (name={1})",g),a.parent=RClass.forName(g),d=!0)}d=a.instance=new a.base.constructor;if(b&&b.constructor==Array)for(e=b.length,f=0;f<e;f++)if(g=b[f],!RString.startsWith(g,"F")){var h=RClass.forName(g);null==h&&RLogger.fatal(this,null,"Parent class is not exists. (name={1})",g);RClass.innerCopy(h.instance,d);a.assign(h)}a.parent&&(this.innerCopy(a.parent.instance,d),a.assign(a.parent));
d.__base||(d.__base=new TClassBase);d.__base[a.name]=new a.base.constructor;var h=a.clazz,k;for(k in h)"__base"!=k&&(null==h[k]&&null==d[k]?d[k]=null:null!=h[k]&&(null==d[k]||null!=d[k]&&h[k]!=d[k])&&(d[k]=h[k]));if(b&&b.constructor==Array)for(e=b.length,f=0;f<e;f++)for(k in g=b[f],h=RClass.forName(g),g=d.__base[g]=new h.base.constructor,h=h.instance,h)if("__base"!=k){var l=h[k],m=d[k];null!=l&&null!=m&&l!=m&&l.constructor==Function&&m.constructor==Function&&(g[k]=h[k])}a.build();if(RRuntime.isRelease())for(k in a.instance)null==
a.instance[k]&&delete a.instance[k]},MO.RClass_free=function(a){var b=a.__class;b&&b.free(a)},MO.RClass_dump=function(a){if(null==a)return"@null";var b=this.safeTypeOf(a);switch(b){case "Boolean":return"Boolean:"+a;case "Number":return"Number:"+a;case "String":return b+"<"+a.length+">:"+a;case "Function":return b+"<"+RMethod.name(a)+">@"+this.code(a);case "Html":return b+"<"+a.tagName+">@"+this.code(a);default:if(a.__name)return b+"<"+a.__name+">@"+this.code(a)}return b+"@"+this.code(a)},MO.Class=
new RClass;
with(MO)MO.RConsole=function(){this.ConsolePreFix="console:";this._registers=new TObjects;this._consoles=new TDictionary;this._localConsoles=new TDictionary;this.initialize=RConsole_initialize;this.register=RConsole_register;this.create=RConsole_create;this.createByName=RConsole_createByName;this.get=RConsole_get;this.find=RConsole_find;this.release=RConsole_release;return this},MO.RConsole_initialize=function(){for(var a=this._registers,b=0;b<a;b++){var d=a.get(b);d.force&&this.find(d.clazz)}},MO.RConsole_register=
function(a){this._registers.push(a)},MO.RConsole_create=function(a){var b=null;if(a){var b=RClass.create(a),d;for(d in b)if(RString.startsWith(d,"lnk")){var e=b[d];if("string"==typeof e&&RString.startsWith(e,"&")){var f=this.find(e.substr(1));if(!f)return RMessage.fatal(this,null,"Can't link console. (name={0}, property={1}:{2})",a,d,e);b[d]=f}}}return b},MO.RConsole_createByName=function(a){var b=null;if(a){var b=RClass.createByName(a),d;for(d in b)if(RString.startsWith(d,"lnk")){var e=b[d];if("string"==
typeof e&&RString.startsWith(e,"&")){var f=this.find(e.substr(1));if(!f)return RMessage.fatal(this,null,"Can't link console. (name={0}, property={1}:{2})",a,d,e);b[d]=f}}}return b},MO.RConsole_get=function(a){a=RClass.name(a);return this._consoles.get(a)},MO.RConsole_find=function(a){var b=null;if(a.constructor=String)b=RClass.name(a);else if(a.constructor==Function)b=a;else return RLogger.fatal(this,null,"Parameter type is invalid. (console={1})",a);if((a=RGlobal.get(this.ConsolePreFix+b))||(a=this._consoles.get(b)))return a;
var d=RClass.forName(b).instance.scopeCd();switch(d){case EScope.Global:a=top.RConsole.createByName(b);RGlobal.set(this.ConsolePreFix+b,a);this._consoles.set(b,a);break;case EScope.Local:a=this.createByName(b);this._localConsoles.set(b,a);this._consoles.set(b,a);break;default:return RLogger.fatal(this,"Unknown scope code. (name={1})",b)}RLogger.info(this,"Create console. (name={1}, scope={2})",b,REnum.decode(EScope,d));return a},MO.RConsole_release=function(){this._registers&&(this._registers.dispose(),
this._registers=null);var a=this._localConsoles;if(a){for(var b=a.count(),d=0;d<b;d++)a.value(d).dispose();a.dispose()}this._localConsoles=null;this._consoles&&this._consoles.dispose();this._consoles=null},MO.Console=new RConsole;
with(MO)MO.RConst=function(){this.PI_2=Math.PI/2;this.PI=Math.PI;this.PI2=2*Math.PI;this.RADIAN_RATE=180/Math.PI;this.DEGREE_RATE=Math.PI/180;this.PERCENT_10=.1;this.PERCENT_100=.01;this.PERCENT_1000=.001;this.identity3x3=[1,0,0,0,1,0,0,0,1];this.identity4x4=[1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1];return this},MO.Const=new RConst;
with(MO)MO.RDate=function(){this.MinYear=1800;this.MaxYear=2400;this.Pattern="n-: /";this.Chars="0123456789-:/";this.DisplayFormat="yyyy-mm-dd hh24:mi:ss";this.DataFormat="yyyymmddhh24miss";this.MonthDays=[0,31,28,31,30,31,30,31,31,30,31,30,31];this.DaySeconds=1E3;this.Parts="YYYY MM DD HH24 MI SS".split(" ");this.PartsDefine={YYYY:["Year",4],MM:["Month",2],DD:["Day",2],HH24:["Hour",2],MI:["Minute",2],SS:["Second",2]};this.nvl=RDate_nvl;this.make=RDate_make;this.format=RDate_format;this.formatDate=
RDate_formatDate;this.formatText=RDate_formatText;this.monthDays=RDate_monthDays;this.splitFormat=RDate_splitFormat;this.makeDate=RDate_makeDate;this.checkItems=RDate_checkItems;this.check=RDate_check;this.parse=RDate_parse;this.splitDate=RDate_splitDate;this.splitTime=RDate_splitTime;this.autoParse=RDate_autoParse;this.getFormat=RDate_getFormat;return this},MO.RDate_nvl=function(a){return a?a:new TDate},MO.RDate_make=function(a,b,d,e,f,g){return new TDate(new Date(a,b,d))},MO.RDate_format=function(a){return this.formatDate(new TDate,
a)},MO.RDate_formatText=function(a,b){if(!a)return!1;b=b.toLowerCase();b=b.replace(/yyyy/g,a.substring(0,4));a=a.substring(4);b=b.replace(/mm/g,a.substring(0,2));a=a.substring(2);b=b.replace(/dd/g,a.substring(0,2));a=a.substring(2);b=b.replace(/hh24/g,a.substring(0,4));a=a.substring(4);b=b.replace(/mi/g,a.substring(0,2));a=a.substring(2);b=b.replace(/ss/g,a.substring(0,2));a.substring(2);return b},MO.RDate_formatDate=function(a,b){if(!a)return"";b=b?b.toLowerCase():this.DataFormat;b=b.replace(/yyyy/g,
RInteger.format(a.year,4));b=b.replace(/yy/g,RInteger.format(a.year%100,2));b=b.replace(/mm/g,RInteger.format(a.month,2));b=b.replace(/dd/g,RInteger.format(a.day,2));b=b.replace(/hh24/g,RInteger.format(a.hour,2));b=b.replace(/mi/g,RInteger.format(a.minute,2));b=b.replace(/ss/g,RInteger.format(a.second,2));return b=b.replace(/ms/g,RInteger.format(a.ms,3))},MO.RDate_monthDays=function(a,b){if(!a||!b)return 0;a=parseInt(a);b=parseInt(b);this.MonthDays[2]=0!=a%4&&0!=a%400||0==a%100?28:29;return this.MonthDays[b]},
MO.RDate_splitFormat=function(a,b){if(!a)return!1;b=b.toLowerCase();for(var d=[];0<b.length;)0==b.indexOf("yyyy")?(d.year=a.substring(0,4),b=b.substring(4),a=a.substring(4)):0==b.indexOf("mm")?(d.month=a.substring(0,2),b=b.substring(2),a=a.substring(2)):0==b.indexOf("dd")?(d.day=a.substring(0,2),b=b.substring(2),a=a.substring(2)):0==b.indexOf("hh24")?(d.hour=a.substring(0,2),b=b.substring(4),a=a.substring(2)):0==b.indexOf("mi")?(d.minute=a.substring(0,2),b=b.substring(2),a=a.substring(2)):0==b.indexOf("ss")?
(d.second=a.substring(0,2),b=b.substring(2),a=a.substring(2)):0==b.indexOf("ms")?(d.ms=a.substring(0,2),b=b.substring(2),a=a.substring(3)):(b=b.substring(1),a=a.substring(1));return d},MO.RDate_checkItems=function(a){if(!a)return!1;var b=RInteger.parse(a.year);if(b<this.MinYear||b>this.MaxYear)return!1;var d=RInteger.parse(a.month);if(1>d||12<d)return!1;var e=RInteger.parse(a.day);if(1>e||e>this.monthDays(b,d))return!1;b=RInteger.parse(a.hour);if(0>b||23<b)return!1;b=RInteger.parse(a.second);if(0>
b||59<b)return!1;a=RInteger.parse(a.ms);return 0>a||99<a?!1:!0},MO.RDate_check=function(a,b){return this.checkItems(this.splitFormat(a,b))},MO.RDate_makeDate=function(a,b){var d=new Date(RInteger.parse(b.year),RInteger.parse(b.month)-1,RInteger.parse(b.day),RInteger.parse(b.hour),RInteger.parse(b.minute),RInteger.parse(b.second),RInteger.parse(b.ms));return a?(a.setDate(d),a):new TDate(d)},MO.RDate_parse=function(a,b,d){d||(d=this.DataFormat);b=this.splitFormat(b,d);return this.checkItems(b)?this.makeDate(a,
b):null},MO.RDate_splitDate=function(a,b){if(b){var d=null;-1!=b.indexOf("-")||-1!=b.indexOf("/")?(-1!=b.indexOf("-")?d=b.split("-"):-1!=b.indexOf("/")&&(d=b.split("/")),1<=d.length&&(a.year=RInteger.parse(d[0])),2<=d.length&&(a.month=RInteger.parse(d[1])),3<=d.length&&(a.day=RInteger.parse(d[2]))):-1!=b.indexOf(":")?this.splitTime(a,b):14==b.length?(a.year=RInteger.parse(b.substr(0,4)),a.month=RInteger.parse(b.substr(4,2)),a.day=RInteger.parse(b.substr(6,2)),a.hour=RInteger.parse(b.substr(8,2)),
a.minute=RInteger.parse(b.substr(10,2)),a.second=RInteger.parse(b.substr(12,2))):8==b.length?(a.year=RInteger.parse(b.substr(0,4)),a.month=RInteger.parse(b.substr(4,2)),a.day=RInteger.parse(b.substr(6,2))):6==b.length?(a.year=RInteger.parse(b.substr(0,4)),a.month=RInteger.parse(b.substr(4,2))):4==b.length&&(a.year=RInteger.parse(b))}},MO.RDate_splitTime=function(a,b){if(b)if(-1!=b.indexOf(":")){var d=b.split(":");1<=d.length&&(a.hour=RInteger.parse(d[0]));2<=d.length&&(a.minute=RInteger.parse(d[1]));
3<=d.length&&(a.second=RInteger.parse(d[2]))}else 6==b.length?(a.hour=RInteger.parse(b.substr(0,2)),a.minute=RInteger.parse(b.substr(2,2)),a.second=RInteger.parse(b.substr(4,2))):4==b.length?(a.hour=RInteger.parse(b.substr(0,2)),a.minute=RInteger.parse(b.substr(2,2))):2==b.length&&(a.hour=RInteger.parse(b.substr(0,2)))},MO.RDate_autoParse=function(a,b){if(!b)return null;a=this.nvl(a);var d=[];d.year=2E3;d.month=1;d.day=1;d.hour=0;d.minute=0;d.second=0;b=RString.trim(b);if(-1==b.indexOf(" "))this.splitDate(d,
b);else{var e=b.split(" ");2==e.length&&(this.splitDate(d,e[0]),this.splitTime(d,e[1]))}return this.checkItems(d)?this.makeDate(a,d):null},MO.RDate_getFormat=function(a){var b="",d="";if(a){if(-1!=a.indexOf(":"))if(a=RString.split(a," "),1==a.length)a=RString.split(a[0],":"),1==a.length?(b+="HH24",d=1==a[0].length?d+("0"+a[0]):d+a[0]):2==a.length?(b+="HH24MI",1==a[0].length?d+="0"+a[0]:2==a[0].length&&(d+=a[0]),1==a[1].length?d+="0"+a[1]:2==a[1].length&&(d+=a[1])):3==a.length&&(b+="HH24MISS",1==a[0].length?
d+="0"+a[0]:2==a[0].length&&(d+=a[0]),1==a[1].length?d+="0"+a[1]:2==a[1].length&&(d+=a[1]),1==a[2].length?d+="0"+a[2]:2==a[2].length&&(d+=a[2]));else{if(2==a.length){var e=RString.split(a[0],"-");3==e.length?(b+="YYYYMMDD",4==e[0].length&&(d+=e[0]),1==e[1].length?d+="0"+e[1]:2==e[1].length&&(d+=e[1]),1==e[2].length?d+="0"+e[2]:2==e[2].length&&(d+=e[2])):2==e.length?(b+="YYYYMM",1==e[0].length&&(d+=e[0]),1==e[1].length?d+="0"+e[1]:2==e[1].length&&(d+=e[1])):1==e.length&&(b+="YYYY",4==e[0].length&&
(d+=e[0]));a=RString.split(a[1],":");1==a.length?(b+="HH24",d=1==a[0].length?d+("0"+a[0]):d+a[0]):2==a.length?(b+="HH24MI",1==a[0].length?d+="0"+a[0]:2==a[0].length&&(d+=a[0]),1==a[1].length?d+="0"+a[1]:2==a[1].length&&(d+=a[1])):3==a.length&&(b+=" HH24MISS",1==a[0].length?d+="0"+a[0]:2==a[0].length&&(d+=a[0]),1==a[1].length?d+="0"+a[1]:2==a[1].length&&(d+=a[1]),1==a[2].length?d+="0"+a[2]:2==a[2].length&&(d+=a[2]))}}else a=RString.split(a,"-"),3==a.length?(b+="YYYYMMDD",4==a[0].length&&(d+=a[0]),
1==a[1].length?d+="0"+a[1]:2==a[1].length&&(d+=a[1]),1==a[2].length?d+="0"+a[2]:2==a[2].length&&(d+=a[2])):2==a.length?(b="YYYYMM",4==a[0].length&&(d+=a[0]),1==a[1].length?d+="0"+a[1]:2==a[1].length&&(d+=a[1])):1==a.length&&(b+="YYYY",4==a[0].length&&(d+=a[0]));a=Array(2);a[0]=b;a[1]=d;return a}},MO.Date=new RDate;
with(MO)MO.REnum=function(){this.contains=REnum_contains;this.tryEncode=REnum_tryEncode;this.encode=REnum_encode;this.tryDecode=REnum_tryDecode;this.decode=REnum_decode;this.parse=REnum_encode;this.format=REnum_decode;return this},MO.REnum_contains=function(){},MO.REnum_tryEncode=function(a,b,d){if(null!=a)for(var e in a)if(e.toLowerCase()==b.toLowerCase())return a[e];return d},MO.REnum_encode=function(a,b){var d=this.tryEncode(a,b);if(null==d)throw new TError(this,"Invalid value (enum={1}, value={2})",
RClass.dump(a),b);return d},MO.REnum_tryDecode=function(a,b,d){if(null!=a)for(var e in a)if(a[e]==b)return e;return d},MO.REnum_decode=function(a,b){var d=this.tryDecode(a,b);if(null==d)throw new TError(this,"Invalid value (enum={1}, value={2})",RClass.dump(a),b);return d},MO.Enum=new REnum;
with(MO)MO.RFile=function(){this.pictures=["jpg","png","gif","bmp"];this.knowns="jpg png gif bmp doc docx vsd xls xlsx".split(" ");this.inPicture=RFile_inPicture;this.isPicture=RFile_isPicture;this.isKnown=RFile_isKnown;this.name=RFile_name;this.extension=RFile_extension;return this},MO.RFile_inPicture=function(a){if(a){a=a.toLowerCase();for(var b in this.pictures)if(this.pictures[b]==a)return!0}},MO.RFile_isPicture=function(a){return this.inPicture(this.extension(a))},MO.RFile_isKnown=function(a){a=
this.extension(a).toLowerCase();for(var b in this.knowns)if(this.knowns[b]==a)return!0;return!1},MO.RFile_name=function(a){if(a){a=a.replace(/\\/g,"/");var b=a.lastIndexOf("/");-1!=b&&(a=a.substring(b+1));b=a.lastIndexOf(".");return-1!=b?a.substring(0,b):a}return""},MO.RFile_extension=function(a){if(a){a=a.replace(/\\/g,"/");var b=a.lastIndexOf("/");-1!=b&&(a=a.substring(b+1));b=a.lastIndexOf(".");return-1!=b?a.substring(b+1):a}return""},MO.File=new RFile;
with(MO)MO.RFloat=function(){this.NUMBER=this.Chars="0123456789-.%";this.LEFT_CHAR="0";this.isFloat=RFloat_isFloat;this.parse=RFloat_parse;this.format=RFloat_format;this.nvl=RFloat_nvl;this.toRange=RFloat_toRange;this.sum=RFloat_sum;this.calculate=RFloat_calculate;this.attach=RFloat_attach;this.fill=RFloat_fill;this.copy=RFloat_copy;return this},MO.RFloat_isFloat=function(a){return RString.isPattern(a,"n")},MO.RFloat_parse=function(a){if(null==a||""==a)return 0;a=RString.trim(a.toString());if(null==
a)return 0;for(;"0"==a.charAt(0);)a=a.substr(1);a=0<a.length?parseFloat(a):0;-1!=RString.findChars(a,"%")&&(a/=100);return isNaN(a)?0:a},MO.RFloat_format=function(a,b,d,e,f){null==b&&(b=0);null==d&&(d=this.LEFT_CHAR);null==e&&(e=6);null==f&&(f=this.LEFT_CHAR);var g=a.toString(),h=g.indexOf(".");-1==h?(a=g,g=""):(a=g.substring(0,h),g=g.substring(h+1,h+e+1));b=RString.lpad(a,b,d);e=RString.rpad(g,e,f);return b+"."+e},MO.RFloat_nvl=function(a,b){return a?a:b?b:0},MO.RFloat_toRange=function(a,b,d){null==
a&&(a=0);return Math.min(Math.max(a,b),d)},MO.RFloat_sum=function(){for(var a=arguments,b=0,d=a.length-1;0<=d;d--){var e=a[n];null!=e&&(b+=parseFloat(e))}return b},MO.RFloat_calculate=function(a,b,d){b=RFloat.nvl(b);d=RFloat.nvl(d);b=parseFloat(b);d=parseFloat(d);return a?(b+d).toString():(b-d).toString()},MO.RFloat_attach=function(a,b,d){for(var e=!1,f=0;f<d;f++)a[f]!=b[f]&&(a[f]=b[f],e=!0);return e},MO.RFloat_fill=function(a,b,d,e){for(var f=0;f<d;f++)a[b++]=e},MO.RFloat_copy=function(a,b,d,e,f){for(var g=
0;g<f;g++)a[b++]=d[e++]},MO.Float=new RFloat;with(MO)MO.RHex=function(){this.NUMBER="0x123456789ABCDEF";this.PAD="0";this.isValid=RHex_isValid;this.parse=RHex_parse;this.format=RHex_format;return this},MO.RHex_isValid=function(a){return RString.isPattern(a,this.NUMBER)},MO.RHex_parse=function(a){return a?parseInt("0x"+a):"0"},MO.RHex_format=function(a,b){var d=null,d=a?a.toString(16):"0";return b?RString.lpad(d,b,this.PAD):d},MO.Hex=new RHex;
with(MO)MO.RInstance=function(){this._pools=new TDictionary;this.pool=RInstance_pool;this.get=RInstance_get;this.alloc=RInstance_alloc;this.free=RInstance_free;return this},MO.RInstance_pool=function(a){a=RClass.name(a);var b=this._pools.get(a);null==b&&(b=new TInstancePool,this._pools.set(a,b));return b},MO.RInstance_get=function(a){return this.pool(a).instance(a)},MO.RInstance_alloc=function(a){return this.pool(p).alloc(p)},MO.RInstance_free=function(a){this.pool(p).free(p)},MO.RInstance=new RInstance;
with(MO)MO.RInteger=function(){this.NUMBER=this.Chars="0123456789-%";this.LEFT_CHAR="0";this.MAX_UINT16=65535;this.MAX_UINT32=4294967295;this.isInteger=this.isInt=RInteger_isInt;this.nvl=RInteger_nvl;this.strideByte=RInteger_strideByte;this.strideBit=RInteger_strideBit;this.parse=RInteger_parse;this.format=RInteger_format;this.toRange=RInteger_toRange;this.pow2=RInteger_pow2;this.sum=RInteger_sum;this.calculate=RInteger_calculate;this.copy=RInteger_copy;this.toString=RInteger_toString;return this},
MO.RInteger_isInt=function(a){return RString.isPattern(a,"n")},MO.RInteger_nvl=function(a,b){return a?a:b?b:0},MO.RInteger_strideByte=function(a){return 65535<a?4:255<a?2:1},MO.RInteger_strideBit=function(a){return 65535<a?32:255<a?16:8},MO.RInteger_parse=function(a,b){null==b&&(b=0);if(null==a||""==a)return b;for(a=RString.trim(a.toString());"0"==a.charAt(0);)a=a.substr(1);var d=0<a.length?parseInt(a):b;return isNaN(d)?b:d},MO.RInteger_format=function(a,b,d){d||(d=this.LEFT_CHAR);a=a.toString();
for(b=parseInt(b)-a.length-1;0<=b;b--)a=d+a;return a},MO.RInteger_toRange=function(a,b,d){null==a&&(a=0);isNaN(a)&&(a=0);a<b&&(a=b);a>d&&(a=d);return a},MO.RInteger_pow2=function(a){return 4096<a?8192:2048<a?4096:1024<a?2048:512<a?1024:256<a?512:128<a?256:64<a?128:32<a?64:16<a?32:8<a?16:4<a?8:2<a?4:1<a?2:1},MO.RInteger_sum=function(){for(var a=0,b=arguments,d=b.length,e=0;e<d;e++)null!=b[e]&&(a+=parseInt(b[e]));return a},MO.RInteger_calculate=function(a,b,d){b=RInteger.parse(b);d=RInteger.parse(d);
var e="";"+"==a?e=b+d:"-"==a?e=b-d:"x"==a?e=b*d:"/"==a&&(e=b/d);return e.toString()},MO.RInteger_copy=function(a,b,d,e,f){for(var g=0;g<f;g++)a[b++]=d[e++]},MO.RInteger_toString=function(a){return null==a?"0":a.toString()},MO.RInteger=new RInteger;with(MO)MO.RJson=function(){this.parse=RJson_parse;this.toString=RJson_toString;return this},MO.RJson_parse=function(a,b){var d=null;try{d=JSON.parse(a)}catch(e){b&&(d=new b)}return d},MO.RJson_toString=function(a){return JSON.stringify(a)},MO.RJson=new RJson;
with(MO)MO.RLogger=function(){this._statusError=!1;this._labelLength=40;this.lsnsOutput=new TListeners;this.output=RLogger_output;this.debug=RLogger_debug;this.info=RLogger_info;this.warn=RLogger_warn;this.error=RLogger_error;this.fatal=RLogger_fatal;this.show=RLogger_show;return this},MO.RLogger_output=function(a,b){this.lsnsOutput.process(a,b)},MO.RLogger_debug=function RLogger_debug(b,d,e){var f=RMethod.name(RLogger_debug.caller),f=f.replace("_","."),g=new TString;g.append(RDate.format("yymmdd-hh24miss.ms"));
g.append("|D ["+RString.rpad(f,this._labelLength)+"] ");for(var h=arguments,k=h.length,f=2;f<k;f++){var l=h[f],m="";null!=l&&(m="function"==typeof l?RMethod.name(l):l.toString());d=d.replace("{"+(f-1)+"}",m)}g.append(d);this.output(b,g.flush())},MO.RLogger_info=function RLogger_info(b,d,e){var f=RMethod.name(RLogger_info.caller),f=f.replace("_","."),g=new TString;g.append(RDate.format("yymmdd-hh24miss.ms"));g.append("|I ["+RString.rpad(f,this._labelLength)+"] ");for(var h=arguments,k=h.length,f=2;f<
k;f++){var l=h[f],m="";null!=l&&(m="function"==typeof l?RMethod.name(l):l.toString());d=d.replace("{"+(f-1)+"}",m)}g.append(d);this.output(b,g.flush())},MO.RLogger_warn=function RLogger_warn(b,d,e){var f=RMethod.name(RLogger_warn.caller),f=f.replace("_","."),g=new TString;g.append(RDate.format("yymmdd-hh24miss.ms"));g.append("|W ["+RString.rpad(f,this._labelLength)+"] ");for(var h=arguments,k=h.length,f=2;f<k;f++){var l=h[f],m="";null!=l&&(m="function"==typeof l?RMethod.name(l):l.toString());d=d.replace("{"+
(f-1)+"}",m)}g.append(d);this.output(b,g.flush())},MO.RLogger_error=function RLogger_error(b,d,e){var f=RMethod.name(RLogger_error.caller),f=f.replace("_","."),g=new TString;g.append(RDate.format("yymmdd-hh24miss.ms"));g.append("|E ["+RString.rpad(f,this._labelLength)+"] ");for(var h=arguments,k=h.length,f=2;f<k;f++){var l=h[f],m="";null!=l&&(m="function"==typeof l?RMethod.name(l):l.toString());d=d.replace("{"+(f-1)+"}",m)}g.append(d);this.output(b,g.flush())},MO.RLogger_fatal=function RLogger_fatal(b,
d,e,f){if(!this._statusError){this._statusError=!0;for(var g=new TString,h=[],k=RLogger_fatal.caller;k&&!RArray.contains(h,k);)h.push(k),k=k.caller;for(var l=h.length,m=0;m<l;m++)k=h[m],0<m&&g.appendLine(),g.append("   "+(l-m)+": "+RMethod.name(k));h=new TString;h.appendLine(RContext.get("RMessage:fatal"));h.appendLine(RString.repeat("-",60));h.append(RClass.dump(b),": ");if(e)for(k=arguments,l=k.length,m=3;m<l;m++){var q=k[m];"function"==typeof q&&(q=RMethod.name(q));e=e.replace("{"+(m-2)+"}",q)}h.appendLine(e);
h.appendLine(RString.repeat("-",60));h.appendLine("Stack:");h.append(g);throw Error(h.toString());}},MO.RLogger_show=function RLogger_show(b,d,e){var f=RMethod.name(RLogger_show.caller),f=f.replace("_","."),g=new TString;g.append(RDate.format("yymmdd-hh24miss.ms"));g.append("|I ["+RString.rpad(f,this._labelLength)+"] ");for(var h=arguments,k=h.length,f=2;f<k;f++){var l=h[f],m="";null!=l&&(m="function"==typeof l?RMethod.name(l):l.toString());d=d.replace("{"+(f-1)+"}",m)}g.append(d);alert(g.flush())},
MO.RLogger=new RLogger;
with(MO)MO.RMethod=function(){this._virtuals={};this.isFunction=RMethod_isFunction;this.isEmpty=RMethod_isEmpty;this.isVirtual=RMethod_isVirtual;this.name=RMethod_name;this.fullName=RMethod_fullName;this.empty=RMethod_empty;this.emptyTrue=RMethod_emptyTrue;this.emptyFalse=RMethod_emptyFalse;this.emptyCall=RMethod_emptyCall;this.virtual=RMethod_virtual;this.empty.__empty=!0;this.emptyTrue.__empty=!0;this.emptyFalse.__empty=!0;return this},MO.RMethod_isFunction=function(a){return"function"==typeof a},
MO.RMethod_isEmpty=function(a){return a&&a.__empty},MO.RMethod_isVirtual=function(a){return a&&a.__virtual},MO.RMethod_name=function(a){return a&&"function"==typeof a?a.__name?a.__name:a.__name=RString.mid(a.toString(),"function ","("):null},MO.RMethod_fullName=function(a){return a&&a.constructor==Function?a.__fullname?a.__fullname:a.__fullname=RString.mid(a.toString(),"function ",")")+")":null},MO.RMethod_empty=function(){},MO.RMethod_emptyTrue=function(){return!0},MO.RMethod_emptyFalse=function(){return!1},
MO.RMethod_emptyCall=function(){},MO.RMethod_virtual=function(a,b){var d=RClass.name(a)+"."+b;if(this._virtuals[d])return this._virtuals[d];var e=function(){throw Error("Virtual method be called.("+d+")");};e.__virtual=!0;e.__name=d;return this._virtuals[d]=e},MO.RMethod=new RMethod;
with(MO)MO.RObject=function(){this._hash=1;this.nextId=RObject_nextId;this.nvl=RObject_nvl;this.clone=RObject_clone;this.copy=RObject_copy;this.free=RObject_free;this.dispose=RObject_dispose;this.release=RObject_release;return this},MO.RObject_nextId=function(a){return this._hash++},MO.RObject_nvl=function(a){for(var b=arguments,d=b.length,e=0;e<d;e++)if(null!=b[e])return b[e];return null},MO.RObject_clone=function(a){var b=new a.constructor,d;for(d in a){var e=a[d];null!=e&&(RClass.isBaseType(e.constructor)||
(e=RObject.clone(e)));b[d]=e}return b},MO.RObject_copy=function(a,b){if(null!=a&&null!=b)for(var d in a){var e=a[d];null==e||RClass.isBaseType(e.constructor)||(null==b[d]&&(b[d]=new c),RObject.copy(e,b[d]));b[d]=e}},MO.RObject_free=function(a){if(a)if(RRuntime.isDebug())for(var b in a)if("__base"==b||"__inherits"==b||"__class"==b)a[b]=null;else{var d=a[b];if(null!=d){if(!RClass.isBaseType(d.constructor))throw new TError(RObject,"Free object is not base object.");a[b]=null}}else for(b in a)a[b]=null},
MO.RObject_dispose=function(a){a&&(a.__dispose||a.dispose());return null},MO.RObject_release=function(a){if(a)for(var b in p){var d=a[b];"Object"==typeof d&&RObject.release(d);a[b]=null}},MO.RObject=new RObject;
with(MO)MO.RRect=function(){this.nvl=RRect_nvl;this.pack=RRect_pack;this.unpack=RRect_unpack;return this},MO.RRect_nvl=function(a){return a?a:new TRect},MO.RRect_pack=function(a){var b=null;a&&(b=a.left+","+a.top+","+a.right+","+a.bottom);return b},MO.RRect_unpack=function(a,b){b=this.nvl(b);if(a){var d=a.split(",");4==d.length&&(b.left=RInt.parse(d[0]),b.top=RInt.parse(d[1]),b.right=RInt.parse(d[2]),b.bottom=RInt.parse(d[3]))}return b},MO.RRect=new RRect;
with(MO)MO.RRegExp=function(){this.test=RRegExp_test;this.testRgexp=RRegExp_testRgexp;return this},MO.RRegExp_test=function(a,b){return a&&null!=b?a.test(b):!1},MO.RRegExp_testRgexp=function(a,b){return a&&b?(new R,a.test(b)):!1},MO.RRegExp=new RRegExp;with(MO)MO.RSet=function(){this.contains=RSet_contains;this.containsString=RSet_containsString;return this},MO.RSet_contains=function(a,b){return(a&b)==b},MO.RSet_containsString=function(a,b){return null!=a&&null!=s?-1!=a.indexOf(s):!1},MO.RSet=new RSet;
with(MO)MO.RString=function(){this.EMPTY="";this.SPACE="   ";this.PAD=" ";this.TRIM=" \t\r\n";this.LOWER="abcdefghijklmnopqrstuvwxyz";this.UPPER="ABCDEFGHIJKLMNOPQRSTUVWXYZ";this.CodeLowerA=97;this.CodeLowerZ=122;this.CodeUpperA=65;this.CodeUpperZ=90;this.isEmpty=RString_isEmpty;this.isBlank=RString_isBlank;this.isAnsi=RString_isAnsi;this.isDbcs=RString_isDbcs;this.isPattern=RString_isPattern;this.inChars=RString_inChars;this.contains=RString_contains;this.equals=RString_equals;this.startsWith=RString_startsWith;
this.endsWith=RString_endsWith;this.findChars=RString_findChars;this.inRange=RString_inRange;this.nvl=RString_nvl;this.nvlString=RString_nvlString;this.empty=RString_empty;this.firstUpper=RString_firstUpper;this.firstLower=RString_firstLower;this.firstLine=RString_firstLine;this.format=RString_format;this.formatLines=RString_formatLines;this.repeat=RString_repeat;this.pad=RString_pad;this.lpad=RString_lpad;this.rpad=RString_rpad;this.trim=RString_trim;this.ltrim=RString_ltrim;this.rtrim=RString_rtrim;
this.mid=RString_mid;this.toLine=RString_toLine;this.toUnderline=RString_toUnderline;this.toLower=RString_toLower;this.toUpper=RString_toUpper;this.split=RString_split;this.splitTwo=RString_splitTwo;this.splitParts=RString_splitParts;this.splitPattern=RString_splitPattern;this.replace=RString_replace;this.replaceChar=RString_replaceChar;this.remove=RString_remove;this.removeChars=RString_removeChars;return this},MO.RString_isEmpty=function(a){return null!=a?0==a.length:!0},MO.RString_isBlank=function(a){return null!=
a?0==a.trim().length:!0},MO.RString_isAnsi=function(a){if(null!=a){for(var b=a.length,d=0;d<b;d++)if(255<a.charCodeAt(d))return!1;return!0}return!1},MO.RString_isDbcs=function(a){if(null==a){a=a.length;for(var b=0;b<a;b++)if(256>value.charCodeAt(b))return!1;return!0}return!1},MO.RString_isPattern=function(a,b){if(null!=a){null==b&&(b="$a$A$f");b=b.replace(/\a/g,this.LOWER);b=b.replace(/\A/g,this.UPPER);b=b.replace(/\f/g,RFloat.NUMBER);b=b.replace(/\n/g,RInteger.NUMBER);for(var d=a.length,e=0;e<d;e++)if(-1==
b.indexOf(a.charAt(e)))return!1;return!0}return!1},MO.RString_inChars=function(a,b){return-1!=this.findChars(b,a)?!0:!1},MO.RString_contains=function(a,b){return null!=a&&null!=b?-1!=a.toString().indexOf(b):!1},MO.RString_equals=function(a,b,d){null==a?a="":a.constructor!=String&&(a=a.toString());null==b?b="":b.constructor!=String&&(b=b.toString());return d?a==b:a.toLowerCase()==b.toLowerCase()},MO.RString_startsWith=function(a,b){return null==b?!0:null!=a?0==a.indexOf(b):!1},MO.RString_endsWith=
function(a,b){if(null==b)return!0;var d=null!=a?a.indexOf(b):-1;return-1!=d?d==a.length-b.length:!1},MO.RString_findChars=function(a,b){if(null!=a&&null!=b)for(var d=a.length,e=0;e<d;e++)if(-1!=b.indexOf(a.charAt(e)))return e;return-1},MO.RString_inRange=function(a,b,d){if(a&&b){d||(a=a.toLowerCase());for(var e=b.length,f=0;f<e;f++){var g=b[f];if(null!=g)if(d){if(a==g)return!0}else if(a==g.toLowerCase())return!0}}return!1},MO.RString_nvl=function(a,b){if(null!=a){var d=null,d=a.constructor!=String?
a.toString():a;if(0<d.length)return d}return null!=b?b:this.EMPTY},MO.RString_nvlString=function(a){null==a&&(a=new TString);return a},MO.RString_empty=function(a){if(null!=a){var b=null,b=a.constructor!=String?a.toString():a;if(0<b.length)return b}return null},MO.RString_firstUpper=function(a){return null!=a?a.charAt(0).toUpperCase()+a.substr(1):a},MO.RString_firstLower=function(){return null!=v?v.charAt(0).toLowerCase()+v.substr(1):v},MO.RString_firstLine=function(a){if(a){var b=Math.min(a.indexOf("\r"),
a.indexOf("\n"));return-1!=b?a.substr(0,b):a}return""},MO.RString_format=function(a,b){for(var d=arguments,e=d.length,f=1;f<e;f++)b=d[f],"function"==typeof b?b=RMethod.name(b):null==b&&(b=""),a=a.replace("{"+(f-1)+"}",b);return a},MO.RString_formatLines=function(a){a=a.replace(/\\r/g,"");a=a.split("\n");for(var b=a.length,d=new TString,e=0;e<b;e++){var f=a[e],f=this.trim(f);this.isEmpty(f)||this.startsWith(f,"//")||d.appendLine(f)}return d.toString()},MO.RString_repeat=function(a,b){return Array(b+
1).join(a)},MO.RString_pad=function(a,b,d){a=null!=a?a.toString():this.EMPTY;b-=a.length;if(0<b){null==d&&(d=this.PAD);var e=0==b%2?b/2:(b-1)/2;return Array(e+1).join(d)+a+Array(b-e+1).join(d)}return a},MO.RString_lpad=function(a,b,d){a=null!=a?a.toString():this.EMPTY;b-=a.length;return 0<b?(null==d&&(d=this.PAD),b=Array(b),b[b.length]=a,b.join(d)):a},MO.RString_rpad=function(a,b,d){a=null!=a?a.toString():this.EMPTY;b-=a.length;return 0<b?(null==d&&(d=this.PAD),a+Array(b+1).join(d)):a},MO.RString_trim=
function(a,b){a=this.nvl(a);b=this.nvl(b,this.TRIM);for(var d=0,e=a.length-1;d<e&&-1!=b.indexOf(a.charAt(d));d++);for(;e>=d&&-1!=b.indexOf(a.charAt(e));e--);return d==e+1?null:0!=d||e!=a.length-1?a.substring(d,e+1):a},MO.RString_ltrim=function(a,b){a=this.nvl(value);b=this.nvl(trims,this.TRIM);for(var d=0,e=a.length-1;d<e&&-1!=b.indexOf(a.charAt(d));d++);return 0!=d?a.substring(d,e+1):a},MO.RString_rtrim=function(a,b){a=this.nvl(a);b=this.nvl(b,this.TRIM);for(var d=a.length-1;0<=d&&-1!=b.indexOf(a.charAt(d));d--);
return d!=a.length-1?a.substring(0,d+1):a},MO.RString_mid=function(a,b,d){if(null==a)return a;var e=0;if(null!=b){var f=a.indexOf(b);-1!=f&&(e=f+b.length)}b=a.length;null!=d&&(f=a.indexOf(d,e),-1!=f&&(b=f));return a.substring(e,b)},MO.RString_toLine=function(a){return a.replace(/\n/g,"\\n").replace(/\r/g,"\\r").replace(/\t/g,"\\t")},MO.RString_toUnderline=function(a){var b=null;if(a){for(var b=new TString,d=a.length,e=0;e<d;e++){var f=a.charAt(e);f.toUpperCase()==f?(0<e&&b.append("_"),b.append(f.toLowerCase())):
b.append(f)}b=b.toString()}return b},MO.RString_toLower=function(a){return null!=a?a.toLowerCase():this.EMPTY},MO.RString_toUpper=function(a){return null!=a?a.toUpperCase():this.EMPTY},MO.RString_split=function(a,b){return a&&b?a.split(b):null},MO.RString_splitTwo=function(a,b){if(a&&b){var d=[],e=a.indexOf(b);-1==e?d.push(a):(d.push(a.substring(0,e)),d.push(a.substring(e+b.length)));return d}return null},MO.RString_splitParts=function(a,b){for(var d=[],e=0,f=a.length,g=0;g<f;g++)for(var h in b)if(this.startsWith(b[h],
a.charAt(g))&&this.equals(a.substr(g,b[h].length),b[h])){d[e++]=b[h];g=g+b[h].length-1;break}return d},MO.RString_splitPattern=function(a,b){var d=[];if(a)for(var e=a.length,f=b.length,g="",h=0;h<e;h++){for(var k=!1,l=0;l<f;l++){var m=b[l];if(-1==a.indexOf(m)){g.length&&(d[d.length]=g,g="");d[d.length]=m;a=a.substring(m.length);k=!0;break}}k||(g+=a.charAt(0),a=a.substring(1))}return d},MO.RString_replace=function(a,b,d){return a.replace(new RegExp(b,"g"),d)},MO.RString_replaceChar=function(a,b,d){if(null!=
a){for(var e=a.length,f=[],g=0;g<e;g++){var h=a.charAt(g);f[f.length]=h==b?d:h}return f.join("")}return a},MO.RString_remove=function(a,b){return a.replace(b,"")},MO.RString_removeChars=function(a,b){if(null!=a){for(var d=a.length,e=[],f=0;f<d;f++){var g=a.charAt(f);-1==b.indexOf(g)&&(e[e.length]=g)}return e.join("")}return a},MO.RString=new RString;
with(MO)MO.RTimer=function(){this._count=this._lastTime=this._startTime=0;this.setup=RTimer_setup;this.now=RTimer_now;this.current=RTimer_current;this.rate=RTimer_rate;this.update=RTimer_update;return this},MO.RTimer_setup=function(){var a=(new Date).getTime();this._lastTime=this._startTime=a},MO.RTimer_now=function(){return(new Date).getTime()},MO.RTimer_current=function(){return this._lastTime},MO.RTimer_rate=function(){return 0==this._count?0:parseInt(1E3*this._count/(this._lastTime-this._startTime))},
MO.RTimer_update=function(){this._count++;this._lastTime=(new Date).getTime()},MO.RTimer=new RTimer;
with(MO)MO.SValue3=function(a,b,d){this.x=RRuntime.nvl(a,0);this.y=RRuntime.nvl(b,0);this.z=RRuntime.nvl(d,0);this.isEmpty=SValue3_isEmpty;this.assign=SValue3_assign;this.setMin=SValue3_setMin;this.setMax=SValue3_setMax;this.set=SValue3_set;this.absolute=SValue3_absolute;this.normalize=SValue3_normalize;this.negative=SValue3_negative;this.serialize=SValue3_serialize;this.unserialize=SValue3_unserialize;this.parse=SValue3_parse;this.toString=SValue3_toString;return this},MO.SValue3_isEmpty=function(a){return 0==
this.x&&0==this.y&&0==this.z},MO.SValue3_assign=function(a){this.x=a.x;this.y=a.y;this.z=a.z},MO.SValue3_setMin=function(){this.z=this.y=this.x=Number.MIN_VALUE},MO.SValue3_setMax=function(){this.z=this.y=this.x=Number.MAX_VALUE},MO.SValue3_set=function(a,b,d){this.x=a;this.y=b;this.z=d},MO.SValue3_normalize=function(){var a=this.absolute();0!=a&&(a=1/a,this.x*=a,this.y*=a,this.z*=a);return this},MO.SValue3_absolute=function(){return Math.sqrt(this.x*this.x+this.y*this.y+this.z*this.z)},MO.SValue3_negative=
function(a){var b=null,b=p?a:new this.constructor;b.x=-this.x;b.y=-this.y;b.z=-this.z;return b},MO.SValue3_serialize=function(a){a.writeFloat(this.x);a.writeFloat(this.y);a.writeFloat(this.z)},MO.SValue3_unserialize=function(a){this.x=a.readFloat();this.y=a.readFloat();this.z=a.readFloat()},MO.SValue3_parse=function(a){var b=a.split(",");if(3==b.length)this.x=parseFloat(b[0]),this.y=parseFloat(b[1]),this.z=parseFloat(b[2]);else throw new TError(o,"Parse value failure. (value={1})",a);},MO.SValue3_toString=
function(){return this.x+","+this.y+","+this.z};
with(MO)MO.SValue3=function(a,b,d,e){this.x=RRuntime.nvl(a,0);this.y=RRuntime.nvl(b,0);this.z=RRuntime.nvl(d,0);this.w=RRuntime.nvl(e,1);this.assign=SValue4_assign;this.set=SValue4_set;this.absolute=SValue4_absolute;this.normalize=SValue4_normalize;this.negative=SValue4_negative;this.serialize=SValue4_serialize;this.unserialize=SValue4_unserialize;this.parse=SValue4_parse;this.toString=SValue4_toString;return this},MO.SValue4_assign=function(a){this.x=a.x;this.y=a.y;this.z=a.z;this.w=a.w},MO.SValue4_set=
function(a,b,d,e){this.x=a;this.y=b;this.z=d;this.w=e},MO.SValue4_absolute=function(){return Math.sqrt(this.x*this.x+this.y*this.y+this.z*this.z+this.w*this.w)},MO.SValue4_normalize=function(){var a=this.absolute();0!=a&&(a=1/a,this.x*=a,this.y*=a,this.z*=a,this.w*=a)},MO.SValue4_negative=function(a){var b=null,b=a?a:new this.constructor;b.x=-this.x;b.y=-this.y;b.z=-this.z;b.w=-this.w;return b},MO.SValue4_serialize=function(a){a.writeFloat(this.x);a.writeFloat(this.y);a.writeFloat(this.z);a.writeFloat(this.w)},
MO.SValue4_unserialize=function(a){this.x=a.readFloat();this.y=a.readFloat();this.z=a.readFloat();this.w=a.readFloat()},MO.SValue4_parse=function(a){var b=a.split(",");if(4==b.length)this.x=parseFloat(b[0]),this.y=parseFloat(b[1]),this.z=parseFloat(b[2]),this.w=parseFloat(b[3]);else throw new TError(o,"Parse value failure. (value={1})",a);},MO.SValue4_toString=function(){return this.x+","+this.y+","+this.z+","+this.w};
