var MO=new function(){this.version="0.2.0";return this};MO.ELogger=new function(){this.Debug=0;this.Info=1;this.Warn=2;this.Error=3;this.Fatal=4;return this};MO.EProcess=new function(){this.Release=0;this.Process=1;this.Debug=2;return this};
with(MO)MO.RRuntime=function(){this.processCd=EProcess.Release;this.isDebug=RRuntime_isDebug;this.isProcess=RRuntime_isProcess;this.isRelease=RRuntime_isRelease;this.setProcessCd=RRuntime_setProcessCd;this.empty=RRuntime_empty;this.nvl=RRuntime_nvl;this.subString=RRuntime_subString;this.className=RRuntime_className;return this},MO.RRuntime_isDebug=function(){return this._processCd==EProcess.Debug},MO.RRuntime_isProcess=function(){return this._processCd==EProcess.Process},MO.RRuntime_isRelease=function(){return this._processCd==
EProcess.Release},MO.RRuntime_setProcessCd=function(a){this._processCd=a},MO.RRuntime_empty=function(){},MO.RRuntime_nvl=function(a,b){return null!=a?a:b},MO.RRuntime_subString=function(a,b,c){if(null==a)return a;var d=0;if(null!=b){var e=a.indexOf(b);-1!=e&&(d=e+b.length)}b=a.length;null!=c&&(e=a.indexOf(c,length),-1!=e&&(b=e));return d>=b?"":a.substring(d,b)},MO.RRuntime_className=function(a){return a&&("function"==typeof a||(a=a.constructor))?this.subString(a.toString(),"function ","("):null},
MO.Runtime=new RRuntime;
with(MO)MO.TAttributes=function(){TDictionary.call(this);this.join=TAttributes_join;this.split=TAttributes_split;this.pack=TAttributes_pack;this.unpack=TAttributes_unpack;this.dump=TAttributes_dump;return this},MO.TAttributes_join=function(a,b){var c=new TString;a||(a="=");b||(b=",");for(var d=this._count,e=0;e<d;e++)0<e&&c.append(b),c.append(this.names[e]),c.append(a),c.append(this.values[e]);return c.flush()},MO.TAttributes_split=function(a,b,c){a=a.split(c);c=a.length;for(var d=0;d<c;d++){var e=
a[d];if(e.length){var f=e.split(b);2==f.length?this.set(RString.trim(f[0]),RString.trim(f[1])):this.set(RString.trim(e),"")}}},MO.TAttributes_pack=function(){for(var a=new TString,b=this._count,c=0;c<b;c++){var d=this.names[c],e=this.values[c],f=d.length;a.append(f.toString().length,f,d);null!=e?(e+="",d=e.length,a.append(d.toString().length,d,e)):a.append("0")}return a.flush()},MO.TAttributes_unpack=function(a){for(var b=this.count=0,c=a.length;b<c;){var d=parseInt(a.substr(b++,1)),e=parseInt(a.substr(b,
d)),f=a.substr(b+d,e),b=b+(d+e),d=parseInt(a.substr(b++,1)),g=null;0<d&&(e=parseInt(a.substr(b,d)),g=a.substr(b+d,e),b+=d+e);this.set(f,g)}},MO.TAttributes_dump=function(){var a=new TString,b=this._count;a.append(RRuntime.className(o)," : ",b);if(0<b){a.append(" (");for(var c=0;c<b;c++)0<c&&a.append(", "),a.append(this._names[c],"=",this._values[c]);a.append(")")}return a.flush()};
with(MO)MO.TDictionary=function(){TMap.call(this);this.dump=TDictionary_dump;return this},MO.TDictionary_dump=function(){var a=new TString,b=this._count;a.append(RRuntime.className(o),": ",b);if(0<b){a.append(" {\n");for(var c=0;c<b;c++)a.append("   ",this._names[c],"=[",this._values[c],"]\n");a.append("}")}return a.flush()};
with(MO)MO.TMap=function(){this._count=0;this._table={};this._names=[];this._values=[];this.isEmpty=TMap_isEmpty;this.count=TMap_count;this.contains=TMap_contains;this.containsValue=TMap_containsValue;this.indexOf=TMap_indexOf;this.indexOfValue=TMap_indexOfValue;this.first=TMap_first;this.last=TMap_last;this.nameAt=TMap_nameAt;this.name=TMap_name;this.at=this.valueAt=TMap_valueAt;this.value=TMap_value;this.setValueAt=TMap_setValueAt;this.setValue=TMap_setValue;this.get=TMap_get;this.set=TMap_set;
this.assign=TMap_assign;this.append=TMap_append;this.insert=TMap_insert;this.remove=TMap_remove;this.removeName=TMap_removeName;this.removeValue=TMap_removeValue;this.rebuild=TMap_rebuild;this.clear=TMap_clear;this.toString=TMap_toString;this.dispose=TMap_dispose;this.dump=TMap_dump;return this},MO.TMap_isEmpty=function(){return 0==this._count},MO.TMap_count=function(){return this._count},MO.TMap_contains=function(a){return null!=a&&null!=this._table[a.toString().toLowerCase()]?!0:!1},MO.TMap_containsValue=
function(a){return-1!=this.indexOfValue(a)},MO.TMap_indexOf=function(a){return null!=a&&(a=this._table[a.toString().toLowerCase()],null!=a)?a:-1},MO.TMap_indexOfValue=function(a){for(var b=this._count,c=0;c<b;c++)if(this._values[n]==a)return n;return-1},MO.TMap_first=function(){return 0<this._count?this._values[0]:null},MO.TMap_last=function(){return 0<this._count?this._values[this._count-1]:null},MO.TMap_nameAt=function(a){return this._names[a]},MO.TMap_name=function(a){return 0<=a&&a<this._count?
this._names[a]:null},MO.TMap_valueAt=function(a){return this._values[a]},MO.TMap_value=function(a){return 0<=a&&a<this._count?this._values[a]:null},MO.TMap_setValueAt=function(a,b){this._values[a]=b},MO.TMap_setValue=function(a,b){0<=a&&a<this._count&&(this._values[a]=b)},MO.TMap_get=function(a,b){if(null!=a){var c=this._table[a.toString().toLowerCase()];if(null!=c)return this._values[c]}return b},MO.TMap_set=function(a,b){if(null!=a){var c=a.toString().toLowerCase(),d=this._table[c];if(null==d||
d>=this._count)d=this._count++,this._names[d]=a,this._table[c]=d;this._values[d]=b}},MO.TMap_assign=function(a){this.clear();this.append(a)},MO.TMap_append=function(a){if(a)for(var b=a.count(),c=0;c<b;c++){var d=a.nameAt(c),e=a.valueAt(c);this.set(d,e)}},MO.TMap_insert=function(a,b,c){var d=this._count;if(0<=a&&a<=d){for(;d>a;d--)this._names[d]=this._names[d-1],this._values[d]=this._values[d-1];this._names[a]=b;this._values[a]=c;this._count++;this.rebuild()}},MO.TMap_remove=function(a){var b=null,
c=this._count;if(0<=a&&a<c){for(b=this._values[a];a<c;a++)this._names[a]=this._names[a+1],this._values[a]=this._values[a+1];this._count--;this.rebuild()}return b},MO.TMap_removeName=function(a){a=this.indexOf(a);return-1!=a?this.remove(a):null},MO.TMap_removeValue=function(a){for(var b=0,c=this._count,d=0;d<c;d++){var e=this._values[d];e!=a&&(b!=d&&(this._names[b]=this._names[d],this._values[b]=e),b++)}this._count=b;this.rebuild()},MO.TMap_rebuild=function(){var a=this._table,b;for(b in a)delete a[b];
b=this._count;for(var c=0;c<b;c++){var d=this._names[c].toLowerCase();a[d]=c}},MO.TMap_clear=function(){this._count=0;for(var a in this._table)delete this._table[a]},MO.TMap_toString=function(){return this.dump().toString()},MO.TMap_dispose=function(){this._count=0;var a=this._table;if(a){for(var b in a)a[b]=null;this._table=null}if(b=this._names){for(a=b.length-1;0<=a;a--)b[a]=null;this._names=null}if(b=this._values){for(a=b.length-1;0<=a;a--)b[a]=null;this._values=null}},MO.TMap_dump=function(){var a=
new TString,b=this._count;a.appendLine(RRuntime.className(o),": ",b);if(0<b){a.append(" {");for(var c=0;c<b;c++)a.appendLine(this._names[c],"=[",this._values[c],"]");a.append("}")}return a.flush()};
with(MO)MO.TObjects=function(){this._count=0;this._items=[];this.isEmpty=TObjects_isEmpty;this.count=TObjects_count;this.items=TObjects_items;this.contains=TObjects_contains;this.indexOf=TObjects_indexOf;this.first=TObjects_first;this.last=TObjects_last;this.at=this.getAt=TObjects_getAt;this.get=TObjects_get;this.setAt=TObjects_setAt;this.set=TObjects_set;this.assign=TObjects_assign;this.append=TObjects_append;this.insert=TObjects_insert;this.shift=TObjects_shift;this.unshift=TObjects_unshift;this.pop=
TObjects_pop;this.push=TObjects_push;this.pushUnique=TObjects_pushUnique;this.swap=TObjects_swap;this.sort=TObjects_sort;this.erase=TObjects_erase;this.remove=TObjects_remove;this.clear=TObjects_clear;this.dispose=TObjects_dispose;this.dump=TObjects_dump;return this},MO.TObjects_isEmpty=function(){return 0==this._count},MO.TObjects_count=function(){return this._count},MO.TObjects_items=function(){return this._items},MO.TObjects_contains=function(a){return-1!=this.indexOf(a)},MO.TObjects_indexOf=function(a){for(var b=
this._count,c=this._items,d=0;d<b;d++)if(c[d]==a)return d;return-1},MO.TObjects_first=function(){return this._count?this._items[0]:null},MO.TObjects_last=function(){return this._count?this._items[this._count-1]:null},MO.TObjects_getAt=function(a){return this._items[a]},MO.TObjects_get=function(a){return 0<=a&&a<this._count?this._items[a]:null},MO.TObjects_setAt=function(a,b){this._items[a]=b},MO.TObjects_set=function(a,b){0<=a&&a<this._count&&(this._items[a]=v)},MO.TObjects_assign=function(a){for(var b=
this._count=a._count,c=0;c<b;c++)this._items[c]=a._items[c]},MO.TObjects_append=function(a){for(var b=a._count,c=0;c<b;c++)this.push(a.at(c))},MO.TObjects_insert=function(a,b){var c=this._count;if(0<=a&&a<=c){for(;c>a;c--)this._items[c]=this._items[c-1];this._items[a]=b}},MO.TObjects_shift=function(){return this.erase(0)},MO.TObjects_unshift=function(a){return this.insert(0,a)},MO.TObjects_pop=function(){if(this._count)return this._items[--this._count]},MO.TObjects_push=function(a){var b=this._count++;
this._items[b]=a;return b},MO.TObjects_pushUnique=function(a){for(var b=this._count-1;0<=b;b--)if(this._items[b]==v)return b;b=this._count++;this._items[b]=a;return b},MO.TObjects_swap=function(a,b){if(0<=a&&a<this._count&&0<=b&&b<this._count&&a!=b){var c=this._items,d=c[a];c[a]=c[b];c[b]=d}},MO.TObjects_sort=function(a){var b=this._items;b.length!=this._count&&(b.length=this._count);b.sort(a)},MO.TObjects_erase=function(a){var b=null;if(0<=a&&a<this._count){for(var b=this._items[a],c=--this._count,
d=this._items;a<c;a++)d[a]=d[a+1];d[c]=null}return b},MO.TObjects_remove=function(a){var b=this._count;if(b){for(var c=0,d=this._items,e=c;e<b;e++)d[e]!=a&&(d[c++]=d[e]);for(e=c;e<b;e++)d[e]=null;this._count=c}return a},MO.TObjects_clear=function(){this._count=0},MO.TObjects_dispose=function(){for(var a in this._items)this._items[a]=null;this._count=0;this._items=null},MO.TObjects_dump=function(){var a=this._count,b=new TString;b.append(RRuntime.className(o),":",a);if(a)for(var c=0;c<a;c++)b.append(" [",
this._items[c],"]");return b.flush()};
with(MO)MO.TString=function(){this._count=0;this._memory=[];this.isEmpty=TString_isEmpty;this.assign=TString_assign;this.append=TString_append;this.appendIf=TString_appendIf;this.appendArray=TString_appendArray;this.appendLine=TString_appendLine;this.appendRepeat=TString_appendRepeat;this.push=TString_push;this.clear=TString_clear;this.toString=TString_toString;this.flush=TString_flush;this.dispose=TString_dispose;this.dump=TString_dump;return this},MO.TString_isEmpty=function(){return 0==this._count},
MO.TString_assign=function(){this.clear();this.appendArray(arguments,0,arguments.length)},MO.TString_append=function(a){this.appendArray(arguments,0,arguments.length)},MO.TString_appendIf=function(a){a&&this.appendArray(arguments,1,arguments.length-1)},MO.TString_appendArray=function(a,b,c){for(var d=0;d<c;d++){var e=a[b++];null!=e&&(this._memory[this._count++]=e)}},MO.TString_appendRepeat=function(a,b){for(var c=0;c<b;c++)this._memory[this._count++]=a},MO.TString_appendLine=function(){this.appendArray(arguments,
0,arguments.length);this._memory[this._count++]="\r\n"},MO.TString_push=function(){this.appendArray(arguments,0,arguments.length)},MO.TString_clear=function(){this._count=0},MO.TString_toString=function(){var a=this._memory;a.length!=this._count&&(a=a.slice(0,this._count));return a.join("")},MO.TString_flush=function(){var a=this.toString();this.dispose();return a},MO.TString_dispose=function(){this._count=0;var a=this._memory;if(a){for(var b=a.length-1;0<=b;b--)a[b]=null;this._memory=null}},MO.TString_dump=
function(){var a=this.toString();return RRuntime.className(o)+":"+a.length+"["+a+"]"};
with(MO)MO.RAssert=function(){this.isTrue=RAssert_isTrue;this.isFalse=RAssert_isFalse;this.debugEnd=this.debug=this.debugBegin=MO.Runtime.empty;this.debugTrue=RAssert_debugTrue;this.debugFalse=RAssert_debugFalse;this.debugNull=RAssert_debugNull;this.debugNotNull=RAssert_debugNotNull;this.debugEmpty=RAssert_debugEmpty;this.debugNotEmpty=RAssert_debugNotEmpty;return this},MO.RAssert_isTrue=function(a){if(!a)throw Error("Assert ture failure.");},MO.RAssert_isFalse=function(a){if(a)throw Error("Assert false failure.");
},MO.RAssert_debugTrue=function(a){if(!a)throw Error("Assert true failure.");},MO.RAssert_debugFalse=function(a){if(a)throw Error("Assert false failure.");},MO.RAssert_debugNull=function(a){if(null!=a)throw Error("Assert null failure.");},MO.RAssert_debugNotNull=function(a){if(null==a)throw Error("Assert not null failure.");},MO.RAssert_debugEmpty=function(a){if(null!=a)throw Error("Assert empty failure.");},MO.RAssert_debugNotEmpty=function(a){if(null==a)throw Error("Assert not empty failure.");
};
with(MO)MO.RMemory=function(){this._entryUnused=null;this._pools={};this.entryAlloc=RMemory_entryAlloc;this.entryFree=RMemory_entryFree;this.alloc=RMemory_alloc;this.free=RMemory_free;this.refresh=RMemory_refresh;return this},MO.RMemory_entryAlloc=function(){var a=null,b=this._entryUnused;b?(a=b,this._entryUnused=b.next):a=new SMemoryPoolEntry;return a},MO.RMemory_entryFree=function(a){RAssert.debugNotNull(a);a.next=this._entryUnused;this._entryUnused=a},MO.RMemory_alloc=function(a){RAssert.debugNotNull(a);var b=
RRuntime.className(a),c=this._pools,d=c[b];d||(d=new TMemoryPool,d._constructor=a,c[b]=d);return d.alloc()},MO.RMemory_free=function(a){RAssert.debugNotNull(a);var b=a.__pool;RAssert.debugNotNull(b);b.free(a)},MO.RMemory_refresh=function(){CollectGarbage()};with(MO)MO.SMemoryPoolEntry=function(){this.value=this.next=null;this.dispose=SMemoryPoolEntry_dispose;return this},MO.SMemoryPoolEntry_dispose=function(){var a=this.value;a&&(a.__pool=null,a.dispose());this.value=this.next=null};
with(MO)MO.TMemoryPool=function(){this._unused=this._constructor=null;this._freeCount=this._allocCount=this._createCount=0;this.alloc=TMemoryPool_alloc;this.free=TMemoryPool_free;this.dispose=TMemoryPool_dispose;this.dump=TMemoryPool_dump;return this},MO.TMemoryPool_alloc=function(){var a=null,b=this._unused;b?(a=b.value,this._unused=b.next,RMemory.entryFree(b)):(a=new this._constructor,a.__pool=o,this._createCount++);this._allocCount++;return a},MO.TMemoryPool_free=function(a){RAssert.debugNotNull(a);
var b=RMemory.entryAlloc();b.value=a;b.next=this._unused;this._unused=b;this._freeCount++},MO.TMemoryPool_dispose=function(){for(var a=this._unused;a;){var b=a,a=b.next;b.dispose();RMemory.entryFree(b)}},MO.TMemoryPool_dump=function(){var a=new TString;a.append("Pool:");a.append("create=",this._createCount);a.append(", alloc=",this._allocCount);a.append(", free=",this._freeCount);return a.flush()};
